dart-lang/language

working/class-capabilities/class-capabilities.md
Leaf mentioned that it might be useful to bring these notes back from the old evolution repo, so here they are. I didn't commit them directly because I wasn't sure if this was where you wanted and I wanted to make sure that Erik was OK with me putting his words out there.
What do you think?
=> Resurrect old notes around class modifiers.

working/bazel/module-structure.md
I've added this as a working reference for future language enhancements or experiments that intend to tackle the concept of either packages-in-the-language, modules-in-the-language, visibility restrictions, "friends", etc - i.e. such as https://github.com/dart-lang/language/issues/11.
=> Add a working introduction to Bazel.

working/0047. Spread Collections/examples/postfix-ellipses/build_methods.dart, working/0047. Spread Collections/examples/postfix-ellipses/other.dart, working/0047. Spread Collections/examples/prefix-ellipses/build_methods.dart, working/0047. Spread Collections/examples/prefix-ellipses/other.dart, working/0047. Spread Collections/spread-collections.md
=> Add proposal for "Spread Collections".

working/enhanced-type-promotion/feature-specification.md
Was originally at: https://github.com/dart-lang/sdk/pull/29624
=> Move over "Enhanced Type Promotion" proposal.

working/spread-collections/feature-specification.md
The discussion on #63 convinced me this is desirable and feasible, so I updated the proposal.
How does this look?
=> Support spread elements in const collections.

accepted/future-releases/generalized-typedef-2018/feature-specification.md, working/spread-collections/feature-specification.md
The feature specification for constructs like `typedef F<X> = List<X>;` was added a few days ago, but it turns out that we need to discuss one element of the design ("is it allowed to use a type alias as a class?, e.g. `class C extends F<int> {}`, `new F()`, where `F` denotes a type alias").
This CL makes it explicit that that particular decision has not yet been made, and it indicates two likely outcomes of the discussion. This should be sufficient to put readers in a good position to understand what's going on.
=> Adjusted generalized type alias feature spec to indicate ongoing discussion

accepted/future-releases/set-literals/implementation-plan.md
Here's a first cut at an implementation plan for set literals.  I experimented with specifying the tasks as a DAG instead of linear phases, not sure it's worth the overhead, but we can see how people like it.  
The schedule needs input from the implementation team leads.
@lrhn @mit-mit @eernstg @munificent @JekCharlsonYu 
Please take a look.  Feel free to push updates or changes.  We can land this and then ask for feedback, or we can try soliciting feedback and sign off from the implementation teams on this PR as somebody (Michael?) recently suggested.
=> Initial draft of implementation plan for set literals

accepted/future-releases/contravariant-superinterface-2018/feature-specification.md, accepted/future-releases/contravariant-superinterface-2018/implementation-plan.md
Introduce documents in `accepted/future-releases` for feature #39.
=> New files added, for contravariant-superinterface-2018

working/0125-static-immutability/feature-specification.md
cc @aam @mraleph @munificent @lrhn for comment.
=> Add initial draft of static immutability

working/control-flow-collections/feature-specification.md, working/control-flow-collections/implementation-plan.md
The main changes are:
- Allow `for` in const collections.
- Now that Set literals are on the way, incorporate them into this
proposal.
- Add a more detailed specification of const collections since we can't
rely on imperative dynamic semantics for those.
- Couple more clarifications and copy-edits.
I'm not entirely sold on allow `for` in consts. It's quite restricted, but also allows you to make giant constants if you really want to. I'm not sure if it's useful enough in practice to be worth adding. What do you think?
=> Revise "Control Flow Collections" and add implementation plan.

accepted/future-releases/set-literals/feature-specification.md
Use `LinkedHashSet<Null>` as the comparison, not `Set<Null>`. This ensures that:
```dart
LinkedHashSet<int> s = {};
```
is valid. Since we guarantee to return a `LinkedHashSet`, that is perfectly fine code.
=> Change type requirements for `{}` being a set literal.

accepted/future-releases/control-flow-collections/implementation-plan.md
`for` is prohibited in constant expressions.
=> Remove references to constant evaluation of `for`

accepted/future-releases/control-flow-collections/implementation-plan.md
- split the Grok work out from IntelliJ (they're pretty disjoint)
- refactor categories to call out where the work will happen
- also mention VS Code (its syntax highlighting grammar is based on the one from Atom; if one needs as update, they both will, and the files are similar enough that a fix into one can be used as the basis for a fix into the other)
=> Update the implementation plan for control flow collections

resources/type-system/subtyping.md
This updates the informal description of the subtyping rules (including the derivation of the algorithmic syntax directed rules) for non-null by default types.  It also adds rules for handling the legacy types planned for use during the migration when non-opted-in libraries interact with opted-in libraries.
cc @stereotype441 @bwilkerson @kmillikin @lrhn
=> Subtyping rules for nullable types and legacy migration types

accepted/future-releases/spread-collections/feature-specification.md
- Specify that the element type is dynamic when spreading dynamic.
- Make it a compile-time error to spread Object.
=> Tweak type inference on spread.

accepted/future-releases/spread-collections/implementation-plan.md
Adds a section for the linter, suggesting a rule that flags opportunities to use spread operators.
See also: https://github.com/dart-lang/linter/issues/1402.
/cc @munificent @leafpetersen
=> add lint rule deliverable

accepted/future-releases/spread-collections/benchmarks/bin/lrhn_benchmark.dart, accepted/future-releases/spread-collections/benchmarks/bin/profile_map.dart
I started hacking on a benchmark to try to get a sense of what the performance for various map spread desugaring looks like. I'll update the corresponding bug with some preliminary notes.
=> Add a benchmark to test map spread performance.

working/terminating-tokens/feature-specification.md
This is the maximally compatible robust approach to optional semicolons.
I'll start working on a simpler more conservative alternative soon.
This PR is just the proposal doc. I have a bunch of other supplementary material:
* A handful of small scripts for scraping a corpus and counting occurrences of certain forms.
* A fork of the front_end and dart_style packages with a prototype implementation of the rules.
* A Makefile for running tests on a big corpus of code.
The scripts reuse some existing helper code I wrote for other ui-as-code language features, so I'd have to duplicate some stuff to migrate it all into here. The front_end and dart_style packages are fairly large. Do you think it's worth bringing this stuff in?
=> Add working spec for "terminating tokens".

specification/.gitignore, specification/Makefile, specification/dart.sty, specification/dartLangSpec.tex, specification/scripts/addlatexhash.dart
This is the branch https://dart-review.googlesource.com/c/sdk/+/93540, that is, it includes the single-line change that disables the generalized type aliases.
=> Moving dartLangSpec.tex to this repo

specification/dart.sty, specification/dartLangSpec.tex
This is needed in order to make `pdflatex dartLangSpec.tex` succeed.
Also, the version number of the front page was changed to 2.2.
=> Fix dart.sty, update version

specification/dartLangSpec.tex
Cf. https://github.com/dart-lang/language/issues/247, this PR reformats a few paragraphs such that we avoid 'Overfull \hbox' issues of a size greater than 20pt, except for a handful of long function types.
=> Resolved the worst "overfull \hbox" issues

specification/dartLangSpec.tex
Cf. [this discussion](https://groups.google.com/a/google.com/d/msgid/dart-analysis-team/CAO1uDzZeY3Yekn9MMWzD3UMHDqJs%3DQPDNR3VOSokTgW%2BHhO-dA%40mail.gmail.com?utm_medium=email&utm_source=footer), the spec omitted the case where a constant expression is an identifier denoting a function which is subject to generic function instantiation. This PR adds that case.
=> Added missing constant: function with generic function instantiation

accepted/future-releases/unified-collections/feature-specification.md
If you spread a collection whose static type is dynamic or where the
element types are supertypes of the collection literal's type, implicit
downcasts need to be inserted since they can fail, as in:
```dart
List<num> n = [1.2];
List<int> i = [...n];
```
Or:
```dart
dynamic d = {"s": 1};
Map<bool, double> m = {...d};
```
cc @nshahan @jmesserly @MichaelRFairhurst
=> Perform runtime checks on each element, key, and value when spreading.

templates/implementation_meta_issue.txt
We need to make sure that the build systems which use the analyzer to
resolve code work correctly with the new feature - if it requires adding
a flag when we construct the `AnalysisDriver` we need to know about it.
=> Clarify implementation step for validating codegen

specification/dartLangSpec.tex
The specification of a for-in statement used to rely on having an `iterator` member on the iterable, and on being able to do `moveNext()` and `current` on the returned object. With this change, we insist that the iterable must actually have type `Iterable<T>` for some `T`.
Note that deployed code already requires this (verified with `dart` and `dart2js`), and it is already specified for an asynchronous for-in that it is a dynamic error for the iterable to not be a `Stream`. So this is more consistent, not breaking in practice, and more strongly typed.
=> Adjusted spec of For-In to insist on Iterable

specification/dartLangSpec.tex
Accidentally landed 'spec_fix_for_in_mar19' without the review based updates; they're here.
=> Review response for spec_fix_for_in_mar19

accepted/future-releases/static-extension-methods/feature-specification.md
Since the feature can be disabled using the language versioning feature, the interaction between extension declarations and non-enabled code is elaborted here.
=> Add notes on interaction with non-migrated libraries.

accepted/future-releases/nnbd/feature-specification.md, resources/type-system/subtyping.md
Adding the constraint that to be considered nullable, a type `T` must not be a subtype of `Object` (in other words, not a * of a nullable type).
Also adding S* to the syntactic list of non-nullable types, as implied by the semantic definition.
=> Correct and clarify potentially non-nullable definition

specification/dartLangSpec.tex
This CL updates the language specification section 'Constant Constructors' to cover the right kinds of constructors only, and moves a long commentary on potentially constant expressions to the section 'Constants' where potentially constant expressions are defined. This resolves #289.
Note that the grammar rule for `<literal>` was also moved as well: From 'Constants' (where there was no justification for having it) to just before the rule for `<primary>`, which is the place where `<literal>` occurs in the grammar. The individual kinds of literals (such as `<booleanLiteral>` and `<setLiteral>`) have always been defined elsewhere, each in their own section on the associated kind of object.
=> Update section "Constant Constructors"

resources/type-system/upper-lower-bounds.md
This adds a specification for the current behavior of Dart 2.0 upper and lower bounds, along with some commentary on known issues.
=> Dart 2.0 upper and lower bounds

resources/type-system/subtyping.md
There was a conjecture that `FutureOr<A> <: FutureOr<B>` iff `A <: B`.  Our current implementations use this rule.  This commit adds a counter-example.
=> Add counter-example to conjecture on FutureOr subtyping

resources/type-system/upper-lower-bounds.md
This takes the specification of lower and upper bounds as implemented and adds in:
- `Never`
- Nullable types `T?`
- Legacy types `T*`
- Required named parameters
It does not try to fix up any of the known issues, but rather to add the minimal delta to account for NNBD.
cc @scheglov @stereotype441 @stefantsov @lrhn @eernstg @munificent
=> Lower and upper bounds adjusted for NNBD

accepted/future-releases/static-extension-methods/feature-specification.md
- Specify that extensions cannot declare members with the same name as `Object` members.
- Specify that extension override "expressions" cannot be used anywhere they are evaluated for their value, only as receivers of member lookups.
- Specfiy that `extension` is a built-in identifier, and `on` is not.
- Specify that the name of an extension must not be a built-in identifier.
=> Specify some details for extension methods.

accepted/future-releases/static-extension-methods/feature-specification.md
The `TypedEquals` example needs an `on T` clause in order to conform to the grammar and define `T` as described.
=> Typo correction

accepted/future-releases/static-extension-methods/implementation-plan.md
The implementations already use "extension-method" so let's just change the implementation plan to match that.
=> Change the name of the extension method flag

specification/Makefile
It now uses 4 iterations, which may eliminate the issue where index references refer to an incorrect page (e.g., it says page 11, but it is on page 15).
Also added a couple of file patterns to the `cleanish` goal, to maintain the property that it removes all intermediate generated files.
Addresses https://github.com/dart-lang/site-www/issues/1735.
=> Adjusted `Makefile` to use an extra iteration when generating PDF

specification/dartLangSpec.tex
This PR moves a sentence about imports a couple of lines down; this is needed because it comes before two other sentences that refer to earlier material (involving a prefix `$p$`), and this sentence is about the next case, where `$p$` is not defined.
=> Moved sentence as described in language issue 379

.travis.yml
The existing logic for skipping the generation of a PDF spec file would skip if there exists a file which differs (across `$TRAVIS_COMMIT_RANGE`) which is not 'significant' (that is, we expect that this change does not matter for the PDF). In particular, any change which _also_ changes the `Makefile` would cause the PDF generation to be skipped, even in the case where `dartLangSpec.tex` is changed as well.
This PR changes the logic such that the PDF is generated whenever any of the significant files changes, and it does not matter whether any insignificant files are changed as well.
It also changes the `Makefile` to be a significant file, which is needed because changes to this file could certainly give rise to changes in the generated PDF.
=> Adjusted .travis.yml logic for skipping PDF generation

specification/dart.sty, specification/dartLangSpec.tex
This PR is a revision of the section Exports (it was one of those sections that needed a revision). It clarifies the situations where clashing names are eliminated (by shadowing) and the situations where it is an error. The choice I made was to make local names (from current lib) shadow everything else, and re-exported non-system library names shadow re-exported system library names, and making remaining name clashes an error.
=> Revised section Exports

specification/dartLangSpec.tex
This is a language specification update that transfers several elements from Dart.g to the language specification.
The grammar rule for `<declaration>` contains a correction which makes a difference: It allows for `late final x;` as well as `late final x = 42;`, which wasn't allowed previously.
A `<topLevelVariableDeclaration>` has been added, because the use of `<variableDeclaration>` created the problem that it allowed `const x;` and `final x;` as top level declarations, and we already have a separate alternative in `<topLevelDefinition>` to allow for `const` and `final` variables as we want to allow them at the top level.
At the same time, a handful of declarations do not have `<metadata>` at the beginning any more (because it's now handled `<metadata> <topLevelDefinition>` in general, …
=> Transferred several grammar adjustments from Dart.g to the spec

accepted/future-releases/static-extension-methods/feature-specification.md
The feature spec does not explicitly make accesses to static members using explicit extension member syntax (like `E(e).staticMember`) an error, it just says that a static member _can_ be accessed using the normal static member syntax `E.staticMember`.
This PR changes the rule for overriding access (like `E(e).m`) such that it is explicitly mentioned that the member (`m`) must be an extension _instance_ member.
=> Clarify static extension method access

resources/type-system/strict-raw-types.md, working/0516 - strict-raw-types/strict-raw-types.md
=> Add spec for strict-raw-types

resources/type-system/strict-inference.md, working/0508 - strict-inference/strict-inference.md
We need a formal specification for  "strict-inference", so that it can be properly implemented and 
tested (e.g. two in progress CRs, [112142](https://dart-review.googlesource.com/c/sdk/+/112142) and [111740](https://dart-review.googlesource.com/c/sdk/+/111740)). @leafpetersen wrote that we can land a spec in this language repository.
Fixes https://github.com/dart-lang/language/issues/508
=> Add strict-inference specification

accepted/future-releases/nnbd/feature-specification.md
'final late x' is a compile time error. The correct order of modifiers is 'late final x'
=> Fix order of modifiers in code example

specification/dartLangSpec.tex
This PR updates the language specification such that it specifies "bundling" of getters and setters for all parts of Dart except imports and exports, that is, whenever an identifier is looked up in the enclosing lexical scopes.
It defines a new concept of 'lexical lookup' which will look for `id` as well as `id=` and select the lexically nearest declaration with one of those names, and make it an error if we are looking up `id` and the selected scope has an `id=` but no `id`, and vice versa; or if we look up `id`/`id=` and nothing is in scope, conclude that we must use an instance member, and the class interface doesn't have the required getter-or-setter, and so on. It's a substantial rewrite, clarification, and bug fix.
In any case, the newly specified approach is what we already …
=> Bundle getter/setter names for lexical lookups

specification/dartLangSpec.tex
This is a tiny thing which has been on the table for a long time: `class C extends List<Function<X>> {}` is an error, superinterfaces must be covariant.
Resolves issue #387.
=> Added the "superinterface must be covariant" rule

resources/type-system/strict-inference.md
I missed both typedefs and "generic function types" (right terminology?) in the strict-inference spec. Both things can have omitted return types, and in both cases that return type is assumed to be dynamic.
=> Add typedefs and generic function types to strict-inference

templates/implementation_meta_issue.txt
Add missing entries for VM, VM service, web debugging, VSCode, Codemirror, and highlight.js to the meta issue template.
=> Implementation plan updates

specification/dartLangSpec.tex
The current specification of mixin application does not say that
the mixin application class implements the mixin's interface.
Instead it implements the implemented interfaces of the mixin declaration
directly.
This is clearly wrong, since the mixin application class must implement
the mixin interface (`is MyMixin` must work!).
When we add the mixin interface to the mixin application class as an immediate
super-interface, we no longer need to have the mixin's implemented interfaces
as immediate superinterfaces.
This change will affect the max-depth of the inheritance chain of the mixin
application if an implemented interface of the mixin was currently the longest
inheritance chain leading to the mixin interface. By inserting the
mixin interface, the max-depth increases by one. This may …
=> Make mixin application implement the mixin's interface.

resources/type-system/subtyping.md
Add syntax for `required` parameters in rule 'Named Function Types' of subtyping.md, and add the constraint that such parameters and their requiredness cannot be forgotten by subsumption.
=> Add subtyping for function types with required named parameters

README.md
These show up as trailing whitespace in the default configuration of
`git diff-index --check`.
=> Strip windows carriage returns from readme

resources/null-shorting/nullshort.sml
The plan is to tell UniPro that they can use this program to expand expressions, such that they can test null-shorting by writing an expression `e` and testing the resulting value for equality between `e` and the transformed expression `xlate e`, probably in a function where they pass in various different values for subexpressions, such that the same pair of `e` and `xlate e` expressions can be tested for having the same behavior with a null receiver and with a non-null receiver in each relevant location.
=> Added SML program implementing the null-shorting transformation

specification/dartLangSpec.tex
Tests allow a deferred import to use a `<configurableUri>`, but the grammar doesn't. Should we add that, or make the tests omit `deferred`? This PR adds that feature to the spec grammar.
A couple of other long-standing grammar corrections included.
=> Grammar corrections

specification/dart.sty, specification/dartLangSpec.tex
The section on cascades had no specification matching expressions like `e..m1..m2` (anything containing more than one `<cascadeSection>` was either incorrectly specified or completely unspecified, depending on the interpretation of the unspecified term _suffix_).
This PR fixes that issue, and includes conditional cascades (`?..`) as well.
It uses a `let ..` in commentary (only) because we don't otherwise use that in the specification, but is prepared for using it as normative text by having a `TODO` comment to that effect.
=> Spec fix cascades

specification/dart.sty, specification/dartLangSpec.tex
Yet another piece of Dart.g transferred to the language specification: String literals. As a result, the language specification is unfortunately more verbose, but in return it is much more precise, and the approach has been tested using the spec parser.
=> Transfer the string rules from Dart.g to the language specification

specification/dartLangSpec.tex
Cf. #594 which needs to rely on this change.
This PR adds a specification of how to perform the static analysis of an invocation of  a callable object, which was missing. We require that the callee is an instance of a class with a `call` method (and #594, if accepted, would then need to generalize this to 'a `call` member').
=> Added missing spec for static analysis of callable object invocation

specification/dartLangSpec.tex
One more thing: Right after the `<uri>` string literal sentences we had 2 identical copies of 'it's a compile-time error if the uri doesn't provide a library'. Obviously (based on the `\rationale{}` in the next paragraph), this used to be a compile-time vs. a run-time error.
So I changed the first one to cover both deferred libraries and non-deferred ones (assuming that we do want to check that a deferred library exists already at compile-time, because otherwise we couldn't emit errors for, say, calling a function exported by such a library), and the second one to be a dynamic error.
We don't indicate that it might be an error if the compile-time inspection of a deferred import yields a different library than the one that is loaded during the execution of `loadLibrary`. Obviously, if we …
=> Clarified constraints on string literals in libraryImport

specification/dart.sty, specification/dartLangSpec.tex
We have a couple of issues with the completeness of the language specification with this addition: It refers to context types and type inference many times, with no definitions.
The current approach is to simply give a brief intuitive explanation when those concepts are first used, such that we just need to adjust references to these concepts when we add suitable sections about inference etc.
Note that I've changed the specification of element evaluation such that they rely on the simplest possible syntax (\FOR{} statements), rather than specifying actions such as evaluating `collection.iterator` etc., because the \FOR{} statements are already specified to do just that.
Similarly, I'm using the notion of `$S$ implements $T$` which means that `$T$` is a superinterface (not just a …
=> Integrate UI-as-code features into the language specification

specification/dartLangSpec.tex
The specification of constants left this possibility open (because the syntax `e.length` could previously only call the instance getter, but now it can also invoke/tear-off an extension member). The update avoids saying 'extension method' because those are not yet in the language specification.
=> Specify that a constant e.length cannot use an extension method

accepted/2.6/static-extension-members/feature-specification.md
Not escaped `|` is treated as end of the column and it looks like
| Member invocation on target X | Corresponding member name                                    |
| :---------------------------- | :----------------------------------------------------------- |
| `X binop expr2`               | `+`, `-`, `*`, `/` , `~/`, `%`, `<`, `<=`, `>`, `>=`, `<<`, `>>`, `>>>`, `^`, `|`, `&` |
=> Fix markdown. Escape column end character

accepted/future-releases/static-extension-methods/feature-specification.md
Allow extensions imported with a prefix to be accessible for implicit invocation, but make them less specific than any extension imported without a prefix.
=> Update extension methods specification for prefix imports.

accepted/future-releases/nnbd/roadmap.md
We had at least one person in PDX who was able to find the roadmap but not the spec :)
=> Add a link from the NNBD roadmap to the spec draft

resources/variance/showWidening.sml, resources/variance/testWiden.sml, resources/variance/typeModel.sml, resources/variance/widen.sml
This adds some SML source code to `resources/variance`, modeling the computation of effective member signatures for member accesses where the receiver class may have declaration-site variance modifiers on its type parameters, and the receiver type may have use-site variance modifiers on its actual type arguments, and the member signature itself may also have use-site variance modifiers.
Running `sml showWidening.sml` yields a long list of cases, systematically iterating over all combinations of a small number of types. Here is one of the examples:
```dart
class Cl<X> {
Ci<Ci<X>> get g => ...;
}
Cl<out T> c; // c.g widened: Ci<out Ci<out T>>
```
This says that with a class `Cl` whose type argument is legacy, with a getter `g` with return type `Ci<Ci<X>>` where `Ci` has a type argument …
=> Resource: use-site widening function

specification/dartLangSpec.tex
Just a tiny fix: We used to leave the type arguments of the fields of an `Invocation` which is passed by language semantics to `noSuchMethods` ambiguous; this PR makes it explicit exactly which type arguments they must have, and in particular that the dynamic type of `typeArguments` must have `List<Type>` as a superinterface.
Cf. https://github.com/dart-lang/sdk/issues/39175: The vm currently provides a `List<dynamic>` when the failed invocation targeted a generic method, so it's useful to eliminate the ambiguity at the same time as the VM gets adjusted to deliver a `List<Type>`.
=> Made type arguments of Invocation fields explicit

accepted/future-releases/nnbd/feature-specification.md
This clarifies the semantics of instance checks and casts in legacy and opted-in libraries, in both weak and strong checking mode.
cc @crelier @nshahan @sigmundch @rakudrama @lrhn @munificent @eernstg
=> Clarify runtime instance check and cast behavior

accepted/future-releases/nnbd/feature-specification.md
The nnbd specification used to have the rule that a getter-only override of a getter which was introduced by a `late final` variable with no initializing expression would also implicitly induce a setter which would always throw. This PR removes that rule, cf. #705.
=> Remove the rule about a throwing setter in a late-variable override

resources/type-system/upper-lower-bounds.md
This addresses a quirk observed by @scheglov that `UP(Never*, int*) ==  int?`, which is somewhat surprising.  This change ensures that `UP(S, T)` is never of the form `Q?` unless one of `T` or `S` is a `?` type.
cc @eernstg @munificent @lrhn
=> Ensure that upper bounds preserve legacy

accepted/future-releases/nnbd/feature-specification.md
Fixes https://github.com/dart-lang/language/issues/715 .
=> Fix warnings for null aware operators to take legacy types into account

accepted/future-releases/nnbd/feature-specification.md
- Allow elision of default value in abstract methods
- **CHANGE** Allow operations on `Never` and specify the typing
- Specify the type signature for calling Object methods on nullable types
- Specify implicit conversion behavior
- Allow potentially constant type variables in instance checks and casts
- Specify the error thrown by the null check operator
- Specify `fromEnvironment` and `Iterator.current` library breaking changes
=> Integrate several small changes to the spec

accepted/future-releases/nnbd/feature-specification.md
Eliminate incorrect language implying that opted in methods inherited through legacy classes preserved their opted-in types, but clarify that override checking is still done against the original declared type (whether inherited through legacy classes or not).
=> Clarify override checking

accepted/future-releases/nnbd/feature-specification.md
This specifies the interaction of legacy types with runtime type object equality, and the treatment of const evaluation and canonicalization in weak and strong checking modes.
=> Specify runtime type equality and weak checking const canonicalization

specification/dartLangSpec.tex
Cf. https://github.com/dart-lang/language/issues/770: A tiny CL specifying that the contents of a library is derived from `<libraryDeclaration>`, and the contents of a part is derived from `<partDeclaration>`, and adding commentary to the effect that those non-terminals are then the "start symbols" of the grammar.
Cleaned up the grammar non-terminal names to use `...Declaration` rather than `...Definition`. It is inconsistent to have many occurrences of 'class declaration' and zero occurrences of 'class definition', and still insist that the non-terminal is named `<classDefinition>`. Similarly, `<classMemberDefinition> ::= <declaration> ...` indicates an inconsistency, and it is actually fair to say that every class member 'definition' is a declaration. Note that we have already taken …
=> Add a few words about start symbols of the Dart grammar

accepted/future-releases/nnbd/feature-specification.md
cc @lrhn @munificent @scheglov @stereotype441 
Per discussion, this specifies that inherited signatures that are mediated by an intervening class use the consolidated signature from the intervening class.
=> Clarify mixed mode inheritance of conflicting signatures

accepted/future-releases/nnbd/feature-specification.md
This is a **change** in the instance check semantics around `null` values.  This change will affect the back end implementations.
@nshahan has prepared tests for this.
cc @munificent 
cc @nshahan @sigmundch @liamappelbe @alexmarkov @crelier @johnniwinther @stefantsov
=> Change strong and weak instance checks to a uniform interpretation

accepted/future-releases/nnbd/feature-specification.md
Also remove the reference to `CastError`. The language specification doesn't mention `CastError` any more, and there is no need to reintroduce it here.
=> Mixins: No have uninitialized non-nullable fields.

accepted/future-releases/language-versioning/package-config-file-v2.md
It was previously just a "should", but tools must be consistent, so make it a "must".
=> Make it a tool requirement to use a package_config.json instead of a .packages file

specification/dartLangSpec.tex
The current language specification text about a noSuchMethod forwarded member seems to imply that `m` is _not_ nsm forwarded when an implementation named `m` is inherited. As is implied by the example a few lines later, this was never the intention: We must have an implementation named `m` which is a correct override of the member signature named `m` in the interface of the class, and if we don't have that then `m` is nsm forwarded.
=> Clarify the notion of being noSuchMethod forwarded

specification/dartLangSpec.tex
Cf. #829; if we decide to proceed as recommended there, this PR will do it.
=> Adjust yield/yield* typing to explicitly apply to each element

specification/dartLangSpec.tex
We decided dart-lang/sdk#33415 that `await e` cannot be a compile-time error when the static type of `e` is `void` (that would have been nice, but it was too breaking). This PR updates the language specification to specify this.
=> Specify that 'await voidExpression' is allowed

specification/dartLangSpec.tex
PR #830 changed the language specification to use a compositional approach to `yield*` (that is, it allowed things like `yield* <num>[1]` in a synchronous generator returning `Iterable<int>`, and it would then be checked per element that each of them could be yielded).
However, this conflicts with an earlier decision (and with the currently implemented behavior). Cf. https://github.com/dart-lang/sdk/issues/40538#issuecomment-589399667, https://github.com/dart-lang/sdk/issues/40538#issuecomment-589885343.
This PR changes the specification to require that the static type of `e` in `yield* e` is assignable to the declared return type of the enclosing generator function, and also that the dynamic type of the `yield*`'ed object is a subtype of the declared return type.
=> Make yield* non-compositional

specification/dartLangSpec.tex
As a follow-up on #856, this PR deletes a few rules about the static checks on `yield*`. This is because they turn out to be provable from other rules, that is, we don't need them.
=> Removed yield* rules that are now implied by other rules

accepted/2.3/spread-collections/feature-specification.md
Replace an extra double quotes with single quotes in the spread collections feature spec so that they match the other quotes.
=> Use single quotes throughout the spread spec

accepted/future-releases/nnbd/feature-specification.md
Complementing https://dart-review.googlesource.com/c/sdk/+/139817, this PR proposes a few adjustments to the nnbd spec in locations where the description of mixed-mode inheritance differs from recent discussions about the approach and the implementation.
=> Adjust mixed mode rules

resources/type-system/upper-lower-bounds.md
This specifies an extension to the lower bound algorithm.  The analyzer has always implemented this as part of its merge algorithm for inference constraints, but not as part of the lower bound computation.  This is a specification change for the NNBD DOWN algorithm to make the merge algorithm and the lower bound algorithm consistent.  See [here](https://github.com/dart-lang/sdk/issues/37439) for discussion.
Proposed tests for this change [here](https://dart-review.googlesource.com/c/sdk/+/141841).
cc @johnniwinther @stefantsov @scheglov @stereotype441 @lrhn @munificent @eernstg 
@scheglov I will file an implementation issue for the analyzer once this has landed.
=> Extend GLB to handle FutureOr

accepted/future-releases/nnbd/feature-specification.md
This PR makes it explicit that override checks in a legacy class are performed relative to the direct superinterfaces (rather than just 'the superinterfaces'). I believe it makes no difference, because the legacy subtype relationship ignores the differences that could occur, but it seems reasonable to reinforce the general rule that all relevant properties of a class (member signatures, implemented superinterfaces) are available on the class itself, and it is never necessary to search the entire superinterface graph.
(PS: We still need to search the entire superinterface graph when checking the correctness of the declared type of a covariant formal parameter relative to the overridden declarations of the same parameter, but that step is separate from regular override checks, and there are …
=> Clarify legacy override check

accepted/future-releases/nnbd/feature-specification.md
Clarify the behavior of boolean conditional expressions in strong and weak mode.
cc @nshahan @sigmundch @rakudrama @alexmarkov @lrhn @eernstg @munificent
=> Clarify boolean conditional evaluation

accepted/future-releases/nnbd/feature-specification.md
This changes the specification of NNBD_TOP_MERGE to resolve any conflicting top types to `Object?`, per discussion [here](https://github.com/dart-lang/language/issues/793).
Initial set of tests [here](https://dart-review.googlesource.com/c/sdk/+/141847), more to follow.
[Edit: more tests [here](https://dart-review.googlesource.com/c/sdk/+/142802)]
cc @eernstg @munificent @lrhn
=> Make TOP_MERGE resolve to `Object?`

accepted/future-releases/nnbd/feature-specification.md
Cf. https://github.com/dart-lang/language/issues/932.
=> Added specification of nnbd error for "await voidExpression"

specification/dartLangSpec.tex
This was a stale TODO (waiting for instantiation to bound to be specified, but we've had that for a while now). It updates the language specification to specify the behavior that the implementations already have.
=> Update dynamic invocation type argument rule to use i2b

accepted/future-releases/nnbd/feature-specification.md
Thanks to @johnniwinther for raising this. The null-safety specification does not seem to specify how to perform static checking of an expression of the form `e1 == e2`. This expression needs special attention because it amounts to some checks for null, possibly followed by an invocation of `operator ==`, and hence the static analysis needs to allow null as the value of `e1` as well as the value of `e2`.
It is possible to declare an overriding `operator ==` with a covariant parameter, and we should preserve the property that this gives rise to a stronger constraint on the expression. Both `e1` and `e2` can still be null, but when `e1` is not null and the operator will be invoked, `e2` should be assignable to `T?` where `T` is the (covariant) parameter type of `operator ==` in the …
=> Add rule about static check on `e1 == e2`

accepted/future-releases/nnbd/feature-specification.md
This PR on the nnbd spec introduces the requirement "`S` assignable to `T_v` or` flatten(S) <: T_v`" (aka model 1) for a return statement in an `async` function, where `S` is the static type of the returned expression, and `T_v` is the future value type of the function.
This PR also specifies the dynamic semantics, using an approach where the presence/absence of an `await` step is statically determined whenever possible.
The new dynamic semantics is the same as the pre-null-safety dynamic semantics (that is, the one which is currently specified in `dartLangSpec.tex`), except for the case where the returned object dynamic type is a subtype of as well `T_v` as `Future<T_v>`, and the returned object static type is not `dynamic`, but it is a subtype of `T_v`. This case is expected to be very …
=> Specify null-safety `async` returns

accepted/future-releases/nnbd/feature-specification.md
This PR performs those missing changes discussed in reviews. Also, the changes to several occurrences of `flatten(T)` to `$T_v$` are required for the same reasons that caused the change in the "`S` is assignable to `Tv` or `flatten(S) <: Tv` case.
=> Update on top of #941: Some review responses got lost, and `flatten(S)` must be changed in some locations

accepted/2.6/static-extension-members/feature-specification.md
This PR introduces text corresponding to the decision in issue #677.
This update uses `let`, which is a non-standard device in Dart specifications. It does seem to serve the purpose, though, and we can change it when this feature specification gets integrated into the language specification. In any case, an obvious alternative is to spell out the semantics of the desugared form using a fresh variable.
=> Specify null-aware explicit extension method invocation

accepted/future-releases/nnbd/feature-specification.md
Two more occurrences have slipped in since we last removed them.
=> Remove uses of `CastError`.

resources/type-system/normalization.md
This adjusts the normalization rules around Never.  The original specification, interpreted as an algorithm, does not terminate.
=> Adjust normalization rules around Never

resources/type-system/flow-analysis.md
In the specification of the Dart [flow analysis rule about variable or getter evaluation](https://github.com/dart-lang/language/blob/master/resources/type-system/flow-analysis.md#expressions), we have this:
> Otherwise if T is non-nullable then:
> - Let null(N) = before(N).
> - Let notNull(N) = unreachable(before(N)).
This PR makes an adjustment such that this rule expects the null continuation to be unreachable, rather than the non-null continuation.
=> Typo fix: Adjust variable/getter flow rule

resources/type-system/inference.md
Cf. issue https://github.com/dart-lang/sdk/issues/41803, this PR changes the computation of the imposed context type for a returned expression in an `async` function literal such that it uses a variant of `futureValueType` that handles type schemes, rather than _flatten()_.
=> Adjust function literal return type inference to use future value type

resources/type-system/flow-analysis.md
The existing definition of `unassigned` in flow-analysis.md had 'is known not to have been definitely assigned at the given point in the source code', which is confusing (or even misleading) because it is identical to the wording about `assigned` except for including 'not', which makes it difficult to interpret `unassigned` as anything other than the negation of `assigned` (which would of course be useless).
My interpretation of '`v` is definitely assigned at _N_' is that every path in the flow graph from the root to _N_ contains a node which is an assignment to `v`, and there is at least one such path; and '`v` is definitely unassigned at _N_' means that no path in the flow graph from the root to _N_ contains any node which is an assignment to `v`.
The new text explicitly defines …
=> Adjust definitions of the `assigned` and `unassigned` bits

accepted/future-releases/nnbd/feature-specification.md, resources/type-system/inference.md
Here is yet another twist with the static checks on return statements: The new rules are treating the return type `dynamic` (along with `dynamic?` and `dynamic*`) the same as `Object?`, which causes a substantial amount of breakage. For instance:
```dart
f() async {
return; // Error!
}
```
I think we do not want this breakage, so this PR adds one extra alternative to the definition of `futureValueType` and `futureValueTypeSchema` such that an `async` function returning `dynamic` (and its variants) will have future value type `dynamic`.
Konstantin has implemented this addition, and it removes the breakage as expected.
So do you agree that we should do this, @lrhn, @leafpetersen, @munificent?
=> Adjust futureValueType{,Schema} to propagate `dynamic`

accepted/future-releases/nnbd/feature-specification.md, resources/type-system/flow-analysis.md, resources/type-system/inference.md
Several small updates to questions and clarifications that have been resolved in the issue tracker but not moved to the spec.
=> Batched small updates

resources/type-system/flow-analysis.md
This change ensures that we properly reject the following unsound program:
```dart
f(Object x) {
void Function()? g;
while (true) {
if (x is int) {
g?.call();
print(x.isEven); // UNSOUND
}
g = () {
x = 'bad';
}
}
}
```
(The program is unsound because the second time through the loop, a
closure exists that writes to `x`, therefore after (A) there is no
guarantee that `x` is still an `int`.)
Note that this bug has already been fixed in the implementation (see
https://github.com/dart-lang/sdk/commit/88b76997c49b6a86bec2ef5afc6e97b329e5a2eb).
=> Fix flow analysis handling of write-captured variables in loops and try-blocks.

accepted/future-releases/nnbd/number-operation-typing.md
After writing tests, I gave the rules a serious look.
They were both too complex and too imprecise.
I changed them so that `x + y` will take the type of `x` where possible (not `int + double`, but `int + int`, `double + num` etc.)
This ensures that a variable which has a type variable (possibly promoted) as type will be safe to do `x += 1` and `x++` because such an operation *always* has the same type as `x` (as long as `x` is a non-`Never` subtype of `num`).
That makes the rules asymmetric, but I think most users will readily accept that the type of the LHS is more important than the RHS. It is a method call after all.
(Most users will also not have type variables that are subtypes of `num` or `int` at all).
=> Update to new number operation rules

specification/dartLangSpec.tex
Cf. https://github.com/dart-lang/language/issues/1059, this PR adds the rule that it is a compile-time error for a generator function to have return type `void`.
If and when this lands, update https://github.com/dart-lang/sdk/issues/32192.
=> Add rule about generators and return type void

resources/type-system/flow-analysis.md
Without this clarifiation, it seems as though they cover the entirety
of for loops and switch statements, when in fact they should only
cover the recurrent part.
Note that the implementation of flow analysis already conforms to this
clarification.  See tests in
https://github.com/dart-lang/sdk/commit/fe9596bac320765a5311335ccb637c07052cae2c.
=> In flow analysis, clarify the scope covered by assignedIn and capturedIn.

resources/type-system/flow-analysis.md
When the `conservativeJoin` function makes a conservative
approximation of the result of a join (e.g. at the top of a loop, when
accounting for incoming control flow from the bottom of the loop),
possibly-assigned variables need to have their `unassigned` flag set
to false, otherwise we would emit a bogus error for code like this:
```dart
f() {
late int x;
for (int i = 0; i < 2; i++) {
if (i == 1) {
print(x); // Bogus error: late variable definitely unassigned
}
if (i == 0) {
x = 10;
}
}
}
```
This is already handled correctly in the implementation (see
`VariableModel.discardPromotionsAndMarkNotUnassigned`), and several
test cases would be broken if it weren't:
- language/nnbd/flow_analysis/late_var_assigned_in_try_test
- language/nnbd/flow_analysis/late_var_used_before_assignment_in_local …
=> Fix conservativeJoin's handling of unassigned.

specification/dartLangSpec.tex
Addendum to #1012: It turns out that there is support in the language team for deleting the rule about `library` name clashes in imports, rather than changing it from a warning to an error. Hence, this PR deletes that rule.
=> Changed warnings to errors, cf. language issue #1012

specification/dartLangSpec.tex
Following up on #1083, we need to remove the rule about library name clashes in exports as well. This PR does that.
=> Remove rule about library name clashes in exports

resources/type-system/inference.md
Cf. https://github.com/dart-lang/language/issues/1063, in particular https://github.com/dart-lang/language/issues/1063#issuecomment-658078704.
This PR changes function literal return type inference to infer `void` from context (rather than using the bottom-up computed actual returned type when the context type is `void` or, for an `async` function, `Future<void>` and similar types like `FutureOr<void>?`). This means that the usual diagnostics emitted for void functions will now also be emitted for function literals passed where the context type has return type `void`/`Future<void>`.
=> Make function literal return type inference infer void from context

accepted/future-releases/nnbd/feature-specification.md
To maintain the result of discussions: This PR adds a specification of how to compute the combined member signature with null-safety, and how to compute various associated types for a `<spreadElement>` with null-safety.
=> Spec null-safety combined member signature and spread type

resources/type-system/inference.md
This PR adds phrases like 'Without null safety, ...' and 'with null safety, ...' in inference.md at locations where the rules differ for legacy code and opted-in code. The PR re-introduces the wording from before the change that added support for null safety where needed, such that we now specify both legacy code and code with null safety, and make the distinction explicit.
It also changes the definition of `futureValueTypeSchema` to use `?` to denote the type schema that imposes no constraints, because the rest of inference.md uses that notation.
(We could also change all these occurrences of `?` to `_`. But given that `_` is allowed as an identifier that denotes a type, we may need to choose some other notation which is syntactically not a type.)
Note that this PR has no associated …
=> Make it explicit when inference rules are null-safety specific

resources/type-system/inference.md
In #1102, Leaf said 'I have an open PR which is changing all uses of `?` to `_`, so let's keep this as `_`.' (click the only 'Show resolved' link on #1102 to see it).
This PR is a tiny fix that changes `?` back to `_` and deletes a commentary paragraph about `?`. It is needed because I forgot to upload a commit which did the same thing just before landing #1102.
=> Typo fix: Change `?` to `_`

specification/dartLangSpec.tex
This PR changes the language specification such that `$S$ implements $T$` is generalized to allow `$S$` to be a type variable whose nearest non-type-variable bound is an interface type that has `$T$` as a superinterface. This means that we are relying on the interface associated with `$S$` rather than `$S$` itself. In particular, `X extends C` is treated the same as `C`, which is also what is needed for meaningful and useful behavior of the rules.
For example, the current definition makes this an error, and that is neither intended nor helpful:
```dart
void f<X extends Iterable<int>>(X x) {
var v = [...x]; // Error!
}
```
The error occurs because the static type of `a` is required to be a type that "implements `Iterable<T>`" for some `T`. We already have special cases for the situation …
=> Adjust `<type> implements` to include type variables

specification/dartLangSpec.tex
Issue https://github.com/dart-lang/language/issues/1108 reports that the rules about initializing formals use `$T_{id}$` in a location where it is undefined. This PR resolves that, and several other imprecision issues at that location in the specification.
Note that the syntax of `<fieldFormalParameter>` was changed to allow an old-style function type to be nullable, but that there is no corresponding implementation effort because the analyzer as well as the CFE already supports this syntax.
Resolves #1108.
=> Clarify rules about initializing formals

resources/type-system/flow-analysis.md
When promoting via a test on type T, the type that should be added to
the test set is T, even if the actual promoted type is different.
This brings the spec in line with the implementation.
=> Flow analysis: Fix promote()'s update of tested set.

accepted/future-releases/nnbd/feature-specification.md, resources/type-system/upper-lower-bounds.md
In response to https://github.com/dart-lang/sdk/issues/42706, this specifies the set of super-interfaces used in computing upper bounds in mixed mode.
No modification to the super-interfaces is performed when computing from an opted in library, but the `LEGACY_ERASURE` is used when computing from an opted out library.
=> Specify the set of super-interfaces used for mixed mode upper bounds

accepted/future-releases/nnbd/feature-specification.md
This PR adds a compile-time error for an uninitialized final instance
variable in the case where there are no generative constructors at all
in the enclosing class.
Cf. https://github.com/dart-lang/language/issues/1131.
=> Add error for uninitialized final instance variable

resources/type-system/flow-analysis.md
Previously, we specified flow states `null()` and `nonNull()` (similar
to `true()` and `false()`), and the special behaviors of `== null` and
`!= null` checks fell out of a general analysis of `E1 == E2`.  But it
didn't work in practice, because it required doing joins like
`join(null(E1), null(E2))`, which isn't sound in general (because it
carries the flow control implication that either E1 or E2 is evaluated
but not both).  Because of these problems, the implementation never
matched this specification, and instead used ad-hoc pattern matching
to recognize `== null` and `!= null`.
In the new formulation, we remove the flow states `null()` and
`nonNull()` and retain the ad-hoc pattern matching for `== null` and
`!= null`, consistent with the current implementation.  However, we
also add …
=> Rework flow analysis of `==` and `!=`.

accepted/future-releases/nnbd/feature-specification.md
This is a proposal for new rules about `main`, adding a new section in the null safety spec (which will replace the section 'Scripts' in the language specification in the future).
Potentially noteworthy aspects (compared to [this](https://github.com/dart-lang/language/issues/1120#issuecomment-670097180)):
This proposal maintains that the initial function has the name `main`. I think it's helpful for developers to know for sure that the initial function has this name, so that they don't suddenly have to use some other name, just because they have switched to use a different compiler.
This proposal still defines the term _script_; however, it is now a very straightforward concept. If we think the word 'script' sounds too "PHP-ish" then we can rename it (here, and later in the language …
=> Propose rules about `main` for null-safety

resources/type-system/flow-analysis.md
Promotion by initialization is not part of Dart at this point, so 'flow-analysis.md' should not mention it. This PR removes a few lines to get that effect.
=> Remove specification of promotion by initialization

resources/type-system/flow-analysis.md
This change, together with the corresponding implementation fix at
https://dart-review.googlesource.com/c/sdk/+/162581, fixes
https://github.com/dart-lang/sdk/issues/43136.
=> Clarify behavior of assignedIn() for initialized variables.

resources/type-system/upper-lower-bounds.md
As mentioned in #1193, the rules for **UP** involving type variables need to be adjusted for soundness. This PR makes an adjustment to achieve this (as a special case of instantiation to bound plus a check).
It also adjusts the rules for **UP**(`T Function<...>(...)`, `T2`) and **UP**(`T1`, `T Function<...>(...)`), where the current rule rule may incorrectly discard nullability.
=> Adjust UP for null safety, cf. language issue #1193

accepted/future-releases/nnbd/feature-specification.md
Change inference with a Null initializer to not use a subtype rule, and eliminate some out of date wording.
=> Small fixes

accepted/future-releases/nnbd/feature-specification.md
Clarify that when a variable type is inferred from an initializer which has a promoted type variable type, the inferred variable has the intersection type as a type of interest.
=> Clarify initialization promotion on intersection types

resources/type-system/flow-analysis.md
It's not necessary, because a method invocation is only valid if
either the target is already non-nullable, in which case it would have
no effect, or the method is available on a nullable type
(e.g. toString()), in which case we shouldn't be promoting the type of
the target anyhow.
=> Do not use promoteToNonNull in flow analysis of method invocations.

accepted/future-releases/nnbd/feature-specification.md
When `T` is a type literal denoting a class, mixin, or extension `C` (`T` could be `C` or `p.C`), `T.m()` will invoke the static method `m` declared by `C`. In that case `T?.m()` was previously equivalent to `T.m()` and caused no diagnostic messages. This PR changes it to be a warning.
This was discussed by mail in May-June ('ClassName?.foo diagnostics'), but apparently hasn't yet been specified.
=> Add nnbd warning for cases like `C?.staticMethod()`

resources/type-system/upper-lower-bounds.md
This PR proposes a set of rules about **UP** with arguments including `FutureOr` based on the discussion in https://github.com/dart-lang/language/issues/1250. It does not introduce `FutureOr` as the result of **UP** when `FutureOr` is not among the arguments.
=> Add rules about FutureOr to UP

accepted/future-releases/nnbd/feature-specification.md
@johnniwinther just noted that the wording about errors on `main` introduced by https://github.com/dart-lang/language/pull/1146 needs to be clarified: It is not the intention that `main` can be a getter (and the old text says so explicitly in commentary), but the word `function` in the spec refers to "functions" (with a `<formalParameterPart>`) as well as setters, getters, and constructors.
In the context we already know that `main` is a top-level declaration, so it can't be a constructor. It can't be a setter because a setter name ends in `=`. So we just need to specify that it can't be a getter. This PR does that.
=> Clarify that `main` cannot be a getter

accepted/future-releases/nnbd/feature-specification.md
Cf. #1081, this PR updates the null-safety spec of null shorting to say that it does _not_ use the equivalence between operator invocations and method invocations that the language specification specifies.
For instance `-e` is specified as equivalent to `e.unaryMinus()` (for a suitable declaration of method `unaryMinus`), and similarly for `e1 + e2` respectively `e1.plus(e2)`.
The tools already treat operators in this manner, so there are no implementation issues.
=> Specify that null shorting does not include operators

accepted/future-releases/nnbd/feature-specification.md
Cf. https://github.com/dart-lang/sdk/issues/43093.
Update: That issue is now closed, and more recent discussions can be found in #1163.
=> Added null-shorting rule to treat selector `!` like other selectors

specification/dart.sty, specification/dartLangSpec.tex
The PR #534 was blocked for a long time because of the worries about a breaking change. This PR is a manually rebased version of the same update, that is, it integrates the changes that were made to the updated sections (esp. 'Imports' and 'Exports') after #534 was created. (An actual `git rebase` was not helpful, because of all the conflicts).
The first version of this PR contains the manually rebased PR #534. The last commit includes responses to the partial review which was added to PR #534.
=> Revise spec section imports (rebased PR)

specification/dartLangSpec.tex
Thanks for all the hard work on 1161! Here's a follow-up, clarifying that conflict merging never considers import prefixes as conflicted.
=> Clarify conflict merging

specification/dartLangSpec.tex
This one is basically a bunch of typos, shouldn't be heavy.
In preparation for releasing a stable 2.8 specification, this PR makes a number of corrections to the language specification grammar rules.
It does not remove elements (like `\LATE{}` and `?` on types) associated with null safety, that will be done later.
Note that `<metadata>` was corrected in several rules (added or removed). CL https://dart-review.googlesource.com/c/sdk/+/167801 tests that tools accept metadata in all locations specified by the grammar, after this change.
To avoid some clutter, a number of terms were simplified as in `\LATE{}?` --> `\LATE?`.
In a few locations `>>>` and `>>` were swapped. This is needed in the spec parser (Dart.g), because it only parses as '>' '>' '>' and the longest match must come first. So …
=> Grammar fixes

specification/dartLangSpec.tex
Cf. https://github.com/dart-lang/sdk/issues/42730:
This PR adds an implementation specific compile-time error at `external` function declarations. It is intended to allow for the behavior of `dart2js` in the situation where an external function does not have a `@JS(...)` annotation. It does not mention that specific motivation, because the same text should allow for an error in situations that are similar, but not identical.
=> Add possible compile-time error for external function

accepted/future-releases/nnbd/feature-specification.md
We may wish to update the nnbd spec to use the sound/unsound terminology rather than weak/strong. This CL performs such a rename. The `expect.dart` library and language tests have recently been changed similarly.
=> Change terminology to use unsound/sound rather than weak/strong

tools/plaintext_grammar.dart
When working on Markdown feature specs, I end up copying pieces of the grammar out of the spec. In Chrome, it ends up putting `h` before and after every grammar rule and does some other weird stuff. I got tired of fixing that up manually every time, so this little script extracts all of the grammar rules from the spec, cleans them up, and prints them out.
Kind of hacky, but it seems to work. :)
cc @leafpetersen @lrhn
=> Little script to extract the spec's grammar as plaintext.

specification/dartLangSpec.tex
I am writing a tool to automatically scrape the context-free grammar rules from the Latex file for the spec. I found this minor syntax error in the spec using EBNF. (I plan to scrape the grammar directly from the implementation, but first thing first.)
=> Correcting EBNF syntax error in grammar rule (':=" should be "::=").

specification/dartLangSpec.tex
=> Adjust grammar to allow metadata of the form `@variableName`

accepted/future-releases/generalized-typedef-2018/feature-specification.md
Cf. #848; we agreed that at should be an error to have instance creations like `new F<C>()` when `F` is a type alias of the form `typedef F<X> = X;`. This PR adds that rule to the non-function type alias feature specification.
=> Is an error to create an instance of a type alias that expands to a type variable

specification/dartLangSpec.tex
The language specification is currently too vague on the ability to look up `.call` on a receiver whose type is function type bounded. This PR specifies that the `.call` is available, and gives its type.
Example: When `F extends void Function(int)`, with `F f`, `f.call` is allowed and has type `void Function(int)`.
Cf. https://github.com/dart-lang/sdk/issues/44506: The action requested there relies on the interpretation which is made explicit with this PR. We already specify explicitly that any object whose static type is function type bounded [can be called](https://github.com/dart-lang/language/blob/988d82bd0f126192fa4af8616654f75e76f675eb/specification/dartLangSpec.tex#L10612), and it would be inconsistent to allow `f(42)` and disallow `f.call(42)`, just because the static type of `f` …
=> Clarify .call on function type bounded types

accepted/future-releases/nnbd/feature-specification.md
Specify canonicalization for type literals and constant objects with respect to legacy types.  Remove the warning when
an overriding method uses a different default value.  Specify that constant object canonicalization uses normalization on type parameters.
https://github.com/dart-lang/sdk/issues/44246
https://github.com/dart-lang/language/issues/1350
https://github.com/dart-lang/language/issues/1346
=> Specify type literal and const object canonicalization

specification/dartLangSpec.tex
The static scope of a class is not implemented, and #550 gathered support for eliminating it. This means that all of the constructors, static members, and instance members have the new 'class scope' of the class as their current scope, which is already matched by the current behavior of the analyzer and the common front end.
Cf. https://github.com/dart-lang/sdk/issues/38588 is an example where it actually matters.
Resolves #550.
Resolves https://github.com/dart-lang/sdk/issues/38588.
=> Eliminate the static scope of a class

specification/dartLangSpec.tex
Generation of a PDF from dartLangSpec.tex fails today, and it fails for earlier versions of dartLangSpec.tex a long way back (at least a year). The failure is a low-level TeX failure, and it seems likely that it has emerged because the underlying LaTeX source was updated.
It couldn't possibly have occurred for all those versions of dartLangSpec.tex during this year, because we have been able to fetch a PDF from https://dart.dev/guides/language/spec all the time, and we've also been able to generate the PDF locally.
The problem is that we can't use `\LiteralSequence{...}` in a `\IndexCustom` after a `@`, apparently because it uses `\!`. This CL changes the offending occurrence of `\IndexCustom` to achieve almost the same thing as `\LiteralSequence{...}` using an `\hspace{}`.
I think it's …
=> Fix LaTeX issue that has emerged recently

accepted/future-releases/small-features-21Q1/feature-specification.md, accepted/future-releases/triple-shift-operator/implementation-plan.md
The small-features-21Q1 spec includes the feature described in #496, except that it does not mention generic function types used as bounds. I think we should include bounds: There is a need to specify a generic function type as a bound if a particular type variable is intended to have a value which is a generic function type, e.g., in order to know how many type arguments to pass in invocations.
```dart
class C<F extends void Function<X>(X)> {
F f;
C(this.f);
void m() { f<int>(42); }
}
class D<F extends void Function<X>(X, [List<X>?]) extends C<X> {...}
```
Also, this PR fixes a typo `tripple-shift` --> `triple-shift`.
=> Small-features-21Q1 fix: Allow generic functions as bounds

specification/dartLangSpec.tex
Cf. https://github.com/dart-lang/language/issues/1434.
=> Adding a sentence about the semantics of >> in JavaScript compiled code

specification/dartLangSpec.tex
I just noticed that 1448 was changed to use `-0x7FFFFFFD` rather than `-0x7ffffffe` at some point. I didn't have a strong opinion about upper/lower case, but the change from `e` to `D` is wrong, it should be `E`. This PR fixes that. It also adds a missing changelog entry, and the promised definition of signed/unsigned shift.
=> Fix typo in PR 1448

working/static metaprogramming/intro.md
This adds an initial document laying out the use cases we would like to solve with static metaprogramming, some rough ideas in terms of the general way we want approach the problem, and the known challenges that we will face.
=> add initial static metaprogramming doc

specification/dart.sty, specification/dartLangSpec.tex
This is a LaTeX clean-up and enhancement PR (no changes to the contents, except for a small change at two locations, which have been marked by a comment from me).
It corrects all `\commentary{}` and `\rationale{}` such that they do not introduce spaces in front or at the end (this is needed in order to avoid spurious extra line breaks when the text fills up the last line of the paragraph). It also reformats the `\commentary{}` and `\rationale{}` to fit in 80 columns.
Finally, it introduces `\DefineSymbol` from the beginning and until & including section 'Enums'. This is a macro that adds the given symbol in the margin, such that it is possible to quickly look up the location where a symbol is defined. Symbols are only shown like this if they are used in more than a few lines of text. So …
=> Clean up \commentary, \rationale, specify \DefineSymbol

accepted/future-releases/small-features-21Q1/feature-specification.md
The grammar already allows the type arguments on metadata. Changed the feature spec accordingly.
=> Adjust feature spec for small features 21Q1

accepted/future-releases/small-features-21Q1/feature-specification.md
In https://github.com/dart-lang/language/pull/1513 I overlooked that the small-features-21Q1 feature spec says in _one more location_ that we have to change the grammar. This PR fixes that.
=> Fix inconsistency in small-features 21Q1 feature spec

specification/dartLangSpec.tex
This corrects an omission in the recent update where extension methods where specified: How to find the static type and execute an identifier reference, when it denotes an extension member.
=> Specify identifier references denoting extension members

specification/dartLangSpec.tex
In preparation for a stable 2.11 language specification release, this PR takes out those few elements in the language specification that are part of the null safety feature bundle.
In particular, it removes `?` from types, `?..` from cascades, `late` from variables, and `required` from formal parameters.
I went over every occurrence of `null` in the specification, but did not see any other elements that are part of null safety (in general, we've avoided adding those things, because we were planning to release a stable version of the pre-null-safety language specification).
@lrhn, can you think of other elements that we need to take out in order to make it a clean 2.11 spec?
It would be really nice to complete the work on adding `\DefineSymbol` at every introductory occurrence of a …
=> Take out the null-safety related elements of the specification

specification/dartLangSpec.tex
Small adjustments to the language specification, as a follow-up on #1468.
=> Post-hoc review response for #1468

specification/dart.sty, specification/dartLangSpec.tex
The current specification of lexical lookup specifies a compile-time error in certain cases where it should specify that a name `$n$` is instead transformed into `\THIS.$n$` (which is an identifier reference or a part of an unqualified function invocation). This PR fixes that.
Note that lexical lookup yields a member signature as a "signal to caller" that the expression should have `\THIS{}` prepended. The static analysis will then proceed from scratch on the transformed expression, and this will allow us to detect that it is a regular getter/method invocation on `\THIS{}` or an implicit extension getter/method invocation.
Update: The information about _which_ member signature was yielded by a lookup was ignored (we just proceed with `this.id` resp. `this.id<...>(...)`), so I changed the …
=> Adjust lexical lookup to include implicit extension method invocation

specification/dartLangSpec.tex
The stable language specification does not include null safety, so it should have a language version number which is lower than 2.12. The most recent stable version with that property is 2.10 (there was no 2.11), so this PR makes that correction.
=> Corrected the version number of the stable spec to 2.10 (there is no 2.11)

specification/dartLangSpec.tex
This reverts commit 9bf9692ea7ffae3b0282fa3f4d2f52ed7fc6a343. This re-adds those few null-safety related elements of the language specification that were already in place (they were taken out temporarily in order to create a stable spec version 2.10).
Further changes amount to only a few words:
```diff
@@ -13,8 +13,8 @@
\usepackage{makeidx}
\makeindex
\title{Dart Programming Language Specification\\
-{5th edition}\\
-{\large Version 2.10}}
+{6th edition draft}\\
+{\large Version 2.13-dev}}
\author{}
% For information about Location Markers (and in particular the
@@ -26,7 +26,11 @@
%
% Significant changes to the specification.
%
+% 2.13 (there was no 2.12)
+% - Revert the CL where certain null safety features were removed (to enable
+%   publishing a stable version of the specification). …
```
=> Revert "Take out the null-safety ... (#1538)"

specification/dartLangSpec.tex
Tiny grammar change, to align the spec with the impl:
The implementations support metadata on parameter types, e.g., `void Function(@deprecated int)`, and the test `language/metadata/metadata_location_test.dart` already contains test cases for that feature.
The language specification grammar does not allow for metadata in this location, but this is most likely by accident, and the feature does not seem to cause any problems.
Hence, this PR updates the language specification to allow it.
=> Add `<metadata>` to parameter types

specification/dartLangSpec.tex
This CL changes symbol literals to allow `#void`, because we have allowed that for several years.
We have had the test `tests/corelib/symbol_reserved_word_test.dart` since 2014, but it is badly flawed. In particular, it is a multi-test, but it tests many cases where a compile-time error is expected using `//# ...: continued`, which means that the test will pass as long as at least one of the desired compile-time errors occur. However, some parts of the test have been executed in a meaningful manner, so we do have a history of behavior from this test. The analyzer has no current failures on this test, so it's a non-breaking change to specify the behavior that it actually tests.
I've changed the test to express the intent stated in comments in that file …
=> Change symbolLiteral to match actual implementation, clean up reserved words formatting

specification/dartLangSpec.tex
Section 'Class Member Conflicts' specifies several conflicts (we can't have a method and a setter with the same basename, etc), but similar rules are missing for top-level declarations.
Only one of these rules is relevant (there are no top-level constructors so we can't have a conflict at the top level involving a constructor, etc.): It is an error to have a setter with basename `n` together with any other declaration with basename `n`, except when that other declaration is a getter.
This PR adds that rule.
Update: The rule in 'Class Member Conflicts' about setter/method conflicts was a bit vague: It referred to "member" with the intent that it should cover both static and instance members. It is now split into two sentences where one says 'the interface of $C$ contains an instance …
=> Tiny fix: A top-level declaration pair (same basename) must be a getter and a setter

specification/dartLangSpec.tex
This CL does not change the contents of the specification. It changes the following formatting properties:
- Lines with normal text (not `\code{}` and not math stuff) >80 chars are split to fit in 80 columns.
- `\code{}` and math elements not at the beginning of a paragraph that are large enough to need their own line are now consistently without indentation (`\noindent`).
- A number of unnecessary `{}` after LaTeX commands have been removed.
- One reference (`\ref{...}`) was undefined. A relevant reference occurred 3 lines earlier, so this undefined one was deleted.
- The wording in 2-3 comments was changed slightly to fit in 80 columns (only comments!).
We have preferred this kind of formatting for a long time, but generally changed long lines as part of other changes. It's a cleaner …
=> Specification clean-up

accepted/2.7/static-extension-methods/feature-specification.md, specification/dartLangSpec.tex
One of the examples about extension specificity gives an incorrect reason for why one is more specific than the other, this PR fixes that.
=> Correct typo about extension specificity

specification/dartLangSpec.tex
As decided at the language meeting yesterday, `void Function() f = o.call;` should no longer be specified to apply generic method instantiation to the call method of a function object, even in the situation where all other conditions are satisfied. The treatment of any other method, including methods named `call` in the interface of a user-written class, remains unchanged.
=> Specify that generic method instantiation doesn't apply to functionType.call

specification/dartLangSpec.tex
Cf. #1631. This PR adds the grammar rule to allow constructs like `super()` and `super<int>()`, and specifies them in the section `Superinvocations`.
The PR also changes a couple of occurrences of `super invocation` to `superinvocation`, for consistency with this term in itself, and for consistency with terms like `superinitializer`.
Finally, this PR adds `\DefineSymbol` (and related commands) such that the section `Superinvocations` is up to date with symbol introductions.
=> Add support for implicit `.call` superinvocations

specification/dartLangSpec.tex
Tiny bug fix, cf. https://github.com/dart-lang/sdk/issues/45916:
The specification currently allows for a `part of` directive where the enclosing library is specified using `<identifier> ('.' <identifier>)*`, but not using `<uri>`. The latter is intended to work, and it has been working in all tools for a while, and this PR just brings the specification up to date.
=> Correct `part of` syntax

specification/dartLangSpec.tex
It is currently specified in the section `Type Aliases` of the language specification that it is an error if a type alias expands to a type variable and it is used as a mixin. So type aliases expanding to a mixin are already covered.
However, it is not specified at various usage locations that type aliases are included. They _are_ mentioned in connection with `extends` and `implements` and `with`, but, for instance, not in the section about mixin application.
This PR adds a paragraph where it is stated that it is in general implied that a term `$S$` can be a type alias that transitively expands to a class when we say things like "let `$S$` be a class".
=> Make it explicit that "let $S$ be a class" can go via a type alias

specification/dartLangSpec.tex
The current text in the section 'Type Aliases' in the language specification implies that it is possible to invoke a static method `staticMethod` of a class `C` via a type alias `F` _with_ type arguments:
```dart
class C<X> {
void staticMethod() {}
}
typedef F<X> = C<X>;
void main() {
F<int>.staticMethod();
}
```
This should be an error, and the tests expect that it is an error, but the spec language said otherwise. This PR changes the spec text to follow the intention and tests, and makes it an error to include type arguments in this kind of static method invocation.
It also changes the grammar such that a type alias can denote a `<type>` rather than just a `<functionType>`, hence "enabling" non-function type aliases in general.
=> Adjust 'Type Aliases' to outlaw explicit type arguments in static method call

working/1426-extension-types/feature-specification-views.md
This PR adds a proposal for a `view` language construct which uses the concept of a 'view' to provide support for zero-cost abstraction.
The basic idea is the same as that of an extension type, but the word `view` matches the actual intention behind this language construct much better than `extension type`. So it's basically a re-wording of the [existing proposal](https://github.com/dart-lang/language/blob/master/working/1426-extension-types/feature-specification.md).
Apart from the terminology there is one substantial difference between the [extension types](https://github.com/dart-lang/language/blob/master/working/1426-extension-types/feature-specification.md) proposal and this proposal: With the extension types proposal, a plain `extension` declaration (available since Dart 2.6) will …
=> Add first version of a `view` proposal

specification/dartLangSpec.tex
Fix a couple of typos in the language specification about class member conflicts, and add a missing compile-time error about cyclic redirecting generative constructors.
=> Fix commentary about class member conflicts and add missing error

accepted/2.1/super-mixins/mixin-inference.md, accepted/2.12/nnbd/feature-specification.md, accepted/2.3/control-flow-collections/implementation-plan.md, accepted/2.5/constant-update-2018/implementation-plan.md, accepted/2.5/contravariant-superinterface-2018/feature-specification.md, accepted/2.7/static-extension-methods/feature-specification.md, accepted/2.7/static-extension-methods/implementation-plan.md, accepted/2.7/static-extension-methods/old/feature-specification-draft14.md, accepted/2.7/static-extension-methods/old/lrn-strawman.md, accepted/README.md, accepted/future-releases/constructor-tearoffs/feature-specification.md, accepted/future-releases/small-features-21Q1/implementation-plan.md, archive/feature-specifications/covariant-overrides.md, archive/feature-specifications/generalized-void.md, archive/feature-specifications/instantiate-to-bound.md, archive/feature-specifications/mixin-inference.md, doc/life_of_a_language_feature.md, resources/type-system/flow-analysis.md, resources/type-system/inference.md, specification/dartLangSpec.tex
This PR just fixes a bunch of typos where the same word is repeated twice, and the author was unlikely to intend that that word should be repeated.
=> Fix several double word typos, cf. dart-lang/language#1682

specification/dartLangSpec.tex
Without this I believe the grammar specifies that the `required` keyword appears before metadata.
If this change doesn't get the LaTex right and it would be easier to just make the change yourself than to explain to me what to do I won't be offended if you just close the PR.
=> Fix placement of metadata in required named parameters

specification/dartLangSpec.tex
Commit 89347169c715d39e5d3e6ae588cd2bdcbb875492 removed two errors from the language specification: It is an error to derive a mixin from a class whose superclass is not `Object`, or a class that explicitly declares a generative constructor. This PR restores those two errors. We do not have the required language design needed in order to lift those restrictions, so they should be restored.
There is no associated implementation effort, the errors have been reported by the CFE and the analyzer all the time.
=> Restore errors about derived mixins

specification/dartLangSpec.tex
This PR adds a couple of paragraphs to the language specification, specifying that constant expressions whose evaluation is a function closurization or a generic function instantiation are canonicalized.
=> Specify function object canonicalization

accepted/future-releases/constructor-tearoffs/feature-specification.md
Seems there was a typo in an example in a Summary section
=> Fix a typo in Constructor tear-off spec

specification/dartLangSpec.tex
The current grammar does not allow an instance variable declaration with modifiers `covariant late final`. However, that should be allowed, because a _late_ final variable does have a setter. This PR adds a grammar rule to enable that.
There is no implementation effort, because this construct is already used in `language/nnbd/late/covariant_instance_field_test.dart`, and that test succeeds on all configurations, cf. https://dart-ci.firebaseapp.com/current_results/#/filter=language/nnbd/late/covariant_instance_field_test&showAll.
=> Grammar fix: Add support for covariant late final instance variables

specification/dartLangSpec.tex
This PR updates the language specification to make it explicit that it is a compile-time error for a member signature _m_ to override another member signature _m2_ if the latter has a parameter which is covariant-by-declaration, and the former does not have that.
This error is independent of the function types of the method signatures, so let's consider an example where the function types are identical (so it's trivially a correct member override in that respect):
```dart
class A { num foo(num n) => 1.1; }
abstract class B { num foo(covariant num x); }
class C extends A with B {} // Error
```
Here, `C` is an error because its interface has a member signature `num foo(covariant num)`, but it has an implementation with signature `num foo(num)` (inherited from `A`), and the `covariant` …
=> Clarify override error for inherited member with non-covariant parameter

accepted/future-releases/constructor-tearoffs/feature-specification.md
The 'constructor-tearoffs' feature specification does not mention cascades. We could make them a compile-time error (because things like `x..instanceMethod<int>` has no effect), but we allow things like `myLocalVariable;` as a statement as well. So I chose to include support for instantiated tearoffs in cascades, but added commentary saying that it isn't likely to be useful.
=> Mention cascades in constructor-tearoffs feature spec

working/modules/feature-specification.md, working/modules/private-imports.md
The terms "white box" and "black box" are less clear in isolation than
"clear box" and "opaque box".
=> Replace "white box" with "clear box" testing

specification/dartLangSpec.tex
In the case where a parameter `p` is covariant-by-declaration in a superinterface, and a concrete member is inherited from a superclass which has a parameter `p1` that corresponds to `p`, the type of `p1` is required to be a subtype or supertype of each type of a parameter that corresponds to `p1` in all superinterfaces.
We already have this rule for a declaration which occurs in the class itself, but (by mistake) we did not have the rule when a method is inherited. This PR adds the rule for that case.
=> Add rule about covariant-by-decl parameter when inherited

accepted/future-releases/constructor-tearoffs/feature-specification.md
The constructor-tearoffs feature spec does not mention abstract classes. This PR adds a short section about this topic, with the obvious rules.
=> Add short section on abstract classes and constructor tearoffs

specification/dartLangSpec.tex
Section Symbols in the language specification had several issues, arising over time and also because of the recent change to allow `Symbol(s)` where `s` is an arbitrary string.
- The section used to specify that certain symbols are _not_ the same object (not `identical`), which is something we otherwise do not specify (because we do not want to preclude compile-time or run-time canonicalization of symbols, where possible, as an optimization).
- The section did not mention canonicalization or equality of symbols obtained from `Symbol(_)`.
This PR adjusts the text such that these issues are resolved, and brings the language specification in sync with the newly written tests about symbol equality/identity.
=> Update section Symbols, resolving several issues

accepted/2.3/spread-collections/benchmarks/.gitignore, accepted/2.3/spread-collections/benchmarks/pubspec.yaml, analysis_options.yaml, specification/.gitignore, specification/pubspec.yaml, specification/scripts/addlatexhash.dart
When opening up the language repo in an IDE that analyzes the dir (and not just open files), previously it would pollute the problem view with over 600 issues.
This fixes all of those by:
- Adding analyzer excludes for some examples which are meant to be standalone snippets and not fully valid code
- Updating the pubspec in the 2.3 spec benchmarks dir to have an sdk constraint (to disable null safety)
- Adding a pubspec to the `specification` dir so that the scripts dir in it is valid
- Fixing up some deprecation warnings
=> fix analyzer issues, add sdk constraints

specification/dartLangSpec.tex
This PR makes the corrections mentioned in review of #1782 after that PR was landed.
=> Make missing corrections to section Symbols, cf. #1782

accepted/future-releases/constructor-tearoffs/feature-specification.md
See https://github.com/dart-lang/sdk/issues/46888 for the rationale.
=> Add `is` and `as` disambiguation tokens to constructor tearoffs proposal.

accepted/2.12/nnbd/feature-specification.md
Cf. issue https://github.com/dart-lang/language/issues/1763. It looks like we can allow a const factory constructor (which is then necessarily redirecting) in a class that has a late final instance variable.
There will be an implementation effort (it is currently, correctly according to the spec, reported as an error).
=> Adjust nnbd spec to allow a const factory in a class with a late final variable

working/macros/feature-specification.md
Here is my WIP specification for how external resources can be loaded.
Note that it is vague enough to allow for reading `http` and potentially custom multi-root resources. This adds some general flexibility for the future, for instance if we wanted to run a compiler in a browser and load sources through http uris. In that case loading resources from http uris that fall under one of those package roots would be allowed.
I am a bit concerned about symlinks in general here still, I would love to hear thoughts on that.
Note that this also means macros can't load resources if there is no package config at all. So standalone dart scripts wouldn't be able to use macros that load resources, unless we carved out some sort of a special exception for this case.
=> Macros: add Resource class specification for reading external resources

specification/dart.sty, specification/dartLangSpec.tex
Update section "Generic Function Instantiation" to allow this operation on an existing function object, in addition to the currently supported cases (where the expression denotes a declaration).
This update does _not_ yet mention explicit instantiation, but I think the work needed to allow the current generalization and the work needed to support explicit instantiation are rather well separated. So it's not a waste of time to those two things in two steps (and we can then do 'constructor-tearoffs' as one single update, which is probably also nice).
=> Allow generic function instantiation of an existing function object

accepted/future-releases/constructor-tearoffs/feature-specification.md
Remove many disambiguation tokens. Allow instantiating function *objects* and *callable objects*.
=> Reduce disambiguation tokens, instantiate function values.

accepted/future-releases/constructor-tearoffs/faq.md
Attempted to do a less-formal FAQ-style introduction to the constructor tear-off feature.
I've seen a lot of questions which suggest that the specification is not accessible enough to casual readers.
=> Add a FAQ for the constructor tear-offs feature

specification/dartLangSpec.tex
It has been an error for years to use `int.toString()` to call the `Object` instance method `toString` on an instance of `Type`. This syntax ("`<typeLiteral> '.' <memberAccess>`") is reserved for static member access.
It is inconsistent if we allow the same syntax to invoke an extension method (because an extension method will always be dominated by an instance method on the static type of the receiver, and hence extension methods are presumed to _always_ be invoked in a situation where we could also invoke an instance method).
The current specification wording does not make this obvious, and you could argue that it allows for `int.myExtensionMethod()` to invoke an extension method on `Type`.
This PR makes it explicit and unambiguous that it is not possible to implicitly call an extension …
=> Specify that C.m, C.m() cannot invoke an extension method

specification/dartLangSpec.tex
This PR adds a new case to the set of possible 'property extraction' expressions: Implicit property extraction. It occurs where an expression `e` has a static type as a callable object, and the context type is a function type. In this case we desugar `e` into `e.call`. Note that this will also serve as the first step in a generic function instantiation, because it is still true that the context type is a function type also in the case where `e.call` isn't assignable to that context type (but we can fix it by means of an implicit instantiation).
Smaller corrections:
The subsubsection about generic function instantiation was turned into a subsection: It used to be the case that a generic function instantiation would necessarily include a function closurization as a sub-action. This is no …
=> Specify callable object closurization

specification/dartLangSpec.tex
I just noticed that the current specification wording does _not_ clearly allow for an implicit tearoff of an extension method. This PR adds a single word in the section about implicit extension member invocation, to make it explicit that this case is included.
=> Support implicit extension method tearoffs

accepted/future-releases/constructor-tearoffs/feature-specification.md
Based on an inquiry in an email thread, we decided that the following generalization is not overly heavy to implement. This PR specifies the generalisation:
- `e<T1..Tk>` is a potentially constant expression when `e` is a potentially constant expression and `T1..Tk` is a type list.
- `e<T1..Tk>` is a constant expression when `e` is constant and `T1..Tk` are constant type expressions (and a few more things, see the actual changes for details).
See https://github.com/dart-lang/sdk/issues/47150 for details.
=> Add rule about constant expressions where generic function instantiation is applied

accepted/future-releases/constructor-tearoffs/feature-specification.md
This PR adds an extra kind of potentially constant expression, namely a type variable (which is necessarily declared by the enclosing class).
It is needed for consistency, because this is a semantics that we can already express using different mechanisms:
```dart
typedef F<X> = X;
class A<Y> {
Type type;
const A(): type = F<Y>; // Might as well allow `type = Y`.
}
```
The PR also moves one more kind of constant to the section about constant expressions, such that this section contains every kind of constant / potentially constant expression in this document which is not derived directly from the corresponding constructor function.
The ones that are based on the corresponding constructor function remain where they are, because it would duplicate a lot of material to refer to the details of …
=> Add support for a type variable as a potentially constant expression

specification/dartLangSpec.tex
New tests concerned with the treatment of parameters that are covariant-by-declaration due to inheritance are introduced by https://dart-review.googlesource.com/c/sdk/+/208504. The language team decided that this kind of inheritance should be allowed (until now, it was specified to be an error), partly for consistency/simplicity and partly because the CFE already generates the required forwarding stubs.
This PR makes the corresponding changes to the language specification. It introduces a new section by splitting the section 'Classes' in two, because the latter half of this section is really not about classes per se, it is about a topic that we should show explicitly as a section title: 'Fully Implementing an Interface'.
=> Adjust the rules about parameters that are covariant due to inheritance: No longer an error

working/0158 - Enhanced Enum/proposal.md
Example of extension on enum is not valid and is not allowed by the current language version.  This PR fixes it
=> Example in Proposal fixed

working/macros/api/builders.dart, working/macros/api/code.dart, working/macros/api/introspection.dart, working/macros/api/macros.dart, working/macros/example/data_class.dart
In this proposal, there are no explicit classes you implement for each phase, there is only a single class to implement based on the type of declaration you will annotate.
Each of these classes has a single visit method which only gets a declaration argument (no builder). They have external `buildTypes`, `buildDeclarations`, and `buildDefinition` methods. These methods take a callback as an argument, and the callback receives the corresponding builder.
Some advantages of this api are:
- Can have some shared state between phases, managed by local variables in the `visit` method.
- Less complicated class  heirarchy - far fewer classes to understand.
- The phases are less directly exposed, you don't really have to understand them so much any more.
Some disadvantages of this api are:
- Can …
=> Alternate macro api proposal, less visible phases

accepted/1847 - FinalizationRegistry/proposal.md, accepted/future-releases/1847 - FinalizationRegistry/proposal.md
* Rename `[Native]FinalizationRegistry` to `[Native]Finalizer`
* Rename `WeakRef` to `WeakReference`
* Remove `WeakMap` typedef
* Make `NativeFinalizer` not inherit from `Finalizer`.
* Move proposal to accepted folder.
=> Address final comments around FinalizationRegistry

working/macros/api/builders.dart, working/macros/api/introspection.dart, working/macros/api/macros.dart, working/macros/example/data_class.dart
Opening for discussion.
This PR moves us back towards the original proposal, where there is a different type to implement for each phase, and each declaration type you can run on.
**Advantages**:
- It is easier for an implementation to know up front exactly which phases a given macro will run in.
- It allows an implementation to do more efficient invalidation safely - since macros can't share state across phases with local variables you are free to run only a specific phase of a given macro.
- Macros are more composable - you have per-phase functions you can directly delegate work to, instead of only a more general function.
- We don't have to worry about  users trying to share objects they shouldn't through local variables (`TypeBuilders` etc).
- Less nesting, avoids the "callback" style …
=> Revert back to original macro api style

working/macros/api/builders.dart, working/macros/api/introspection.dart, working/macros/feature-specification.md
I had originally thought we allowed cycles in the class hierarchy when it comes to interfaces, but it doesn't look like we do, so we can still have a well defined ordering here (which was the only reason I left this off prior).
Also removed the section about adding macro applications to existing declarations. You should be able to just directly invoke the macros inside your macro instead.
=> add `interfacesOf` method to `ClassIntrospector`, and some cleanup

working/macros/feature-specification.md
This was still pointing at my old repo instead of the new api, and referred to some older apis :).
Removes all references to the prototype repo.
=> clean up some out of date portions of the macro spec

analysis_options.yaml, working/macros/example/data_class.dart, working/macros/feature-specification.md
I went with just `macro NameOfYourMacro` and not `macro class NameOfYourMacro`. Sort of like how `mixin` isn't `mixin class`.
I didn't write a full grammar for this, but could. It's just the class grammar with a different keyword and no `abstract` modifier allowed (we only want to identify concrete macro definitions here).
=> add macro keyword

accepted/future-releases/1847 - FinalizationRegistry/proposal.md
Closes https://github.com/dart-lang/language/issues/2015
=> Clarify `detachKey` behavior in `Finalizer`s

accepted/future-releases/enhanced-enums/feature-specification.md
State that `index` and `toString` are inherited from `Enum`.
State that `values` is only added if it would not conflict.
Rephrase the definition in terms of an `enum` declaration
introducing a *class*, not a `class` declaration.
Then put the corresponding class declaration into the
"implementation" section as a desugaring, not a specification.
=> Update enhanced enum feature specification.

.gitignore, working/macros/api/builders.dart, working/macros/api/expansion_protocol.dart, working/macros/api/introspection.dart, working/macros/pubspec.yaml
This adds a `MacroExecutor` interface which is intended for use by language frontends (cfe, analyzer) in order to load and execute macros, as well as create library augmention files.
This should help more clearly define the role of a frontend when it comes to macros (discovery and introspection), as well as provide a unified api for producing the final library augmentations.
It does not actually write files though, we still need to figure out how we want to coordinate that part, and make sure that the CFE and analyzer can consistently talk about these files.
This also allows for multiple different implementations in terms of how macros are actually loaded and executed, without the frontends having to know about them.
Followup PR here https://github.com/dart-lang/language/pull/2022 which …
=> add initial macro expansion protocol

resources/optional-semicolons-prototype.md
[Terminating Tokens](https://github.com/dart-lang/language/blob/9daaad1d2103dcb7ad91f3ebf27a878c13fca985/inactive/terminating-tokens.md) was moved from working to inactive in #1024 but the links were not updated.
=> Fix broken link in `optional-semicolons-prototype`

specification/dartLangSpec.tex
The specification does not currently make it explicit that it is an error for a generative constructor to have a body of the form `=> e;`. This PR adds text to make that error explicit.
=> State explicitly that an => body in a constructor is an error

accepted/future-releases/enhanced-enums/feature-specification.md
Some typos and compile-time errors in examples fixed
=> Typos and compile errors in Enhanced Enums specification fixed

accepted/future-releases/enhanced-enums/feature-specification.md
Just to be explicit. It would be an error for the desugared class as well, but it's better to make it an error up-front.
=> Say that an enum constructor cannot use super-parameters.

accepted/future-releases/enhanced-enums/feature-specification.md
This one typo previously destroyed all formatting in the document after the occurence.
cc @lrhn
=> Fix </code> tag in the `enhanced-enums` spec

working/macros/feature-specification.md
Closes https://github.com/dart-lang/language/issues/2154 and https://github.com/dart-lang/language/issues/2151
We now specifiy the `OmittedTypeAnnotation` subtype of `TypeAnnotation`. This can be given as a part of a `Code` object in any phase, and you can get the actual inferred type through a separate API in phase 3.
=> add a section on omitted types and inference

resources/type-system/inference.md
Corresponding bug fix to analyzer code base (not yet landed): https://dart-review.googlesource.com/c/sdk/+/235941
=> Update subtype constraint generation to account for variance.

working/augmentation-libraries/feature-specification.md
Allow augmenting constructors with all the non-standard types of constructors (redirecting factories or regular constructors and const constructors).
Fixes https://github.com/dart-lang/language/issues/2136
=> Update the grammar to allow augmenting all types of constructors

specification/dartLangSpec.tex
Adjust lexical rules around identifiers, making it explicit that `<IDENTIFIER>` does not derive reserved words or built-in identifiers. Also introduce a few extra rules from `Dart.g` in order to define the different kinds of identifiers more explicitly.
=> Adjust and clarify simple string interpolation, and clarify identifier rules.

specification/dartLangSpec.tex
The section about extensions in the language specification had an imprecise wording about conflicts involving an extension member (static or not) and a member of the class `Object`. This PR clarifies the text: Such conflicts only arise when the member of `Object` is an instance member.
=> Adjust wording about extension vs. static method conflicts

working/0546-patterns/exhaustiveness.md, working/0546-patterns/patterns-feature-specification.md, working/0546-patterns/records-feature-specification.md
- Get rid of declaration matcher patterns. They're syntactic sugar (on
top of syntactic sugar) and seem to be confusing and error-prone.
Taking them out at least for now to simplify.
- Get rid of the Destructure_n_ interface. I'd eventually like some
protocol for user-defined positional destructuring, but it doesn't
seem like this is it.
Removing the latter left some loose ends in record patterns around
typing and inference. I've tried to tie those up in a way that makes
sense.
cc @eernstg @leafpetersen @jakemac53 @natebosch
=> [patterns] Remove some of the less baked parts of the proposal.

specification/dartLangSpec.tex
Cf. https://github.com/dart-lang/language/issues/2279. The grammar rule on `<partDeclaration>` in the language specification fails to include `<metadata>`. This PR adds it.
=> Correct <partDeclaration>

specification/dartLangSpec.tex
The language specification currently has a grammar rule where `<typeIdentifier>` does not include `dynamic`, which is a mistake. This PR adds it. Thanks to @kaby76 for noticing this issue!
`Function` was mentioned in the same context, but `typeIdentifier` should actually not include `Function`. The word `Function` is treated specially in the rules about `<type>`, because it is used in ways that would otherwise give rise to ambiguities.
Resolves https://github.com/dart-lang/language/issues/2276.
=> Correct `typeIdentifier` to include `dynamic`

working/0731 - horizontal inference/feature-specification.md
This PR fixes a typo in a link from the old location for a feature spec (working) to the current one (accepted).
=> Fix URL typo

specification/dart.sty, specification/dartLangSpec.tex
Changes **flatten** to be specified for a static type which is a type variable.
Changes `await` to throw when provided a `Future` value
of a type that could provide an unsound value if awaited.
This differes from the current specification, which instead treats the future as
a value, so `await someFuture` can evaluate to `someFuture`.
It also differs from the current implementation,
which awaits `someFuture` to its value,
whether the result is sound or not.
The result *can* be sound. Compare:
```dart
Object o = await (Future<Object?>.value(3) as FutureOr<Object));
```
which ends up not breaking soundness, with
```dart
Object o = await (Future<Object?>.value(null) as FutureOr<Object));
```
which currently does break soundness.
This change will make both into runtime errors.
(The …
=> Breaking change to await, update to flatten.

working/extension_structs/overview.md
This is an initial sketch of an alternative direction for approaching the view/extension type problem.  Still in a rough state, putting this up here for some preliminary discussion.
=> Initial overview of extension structs

working/extension_structs/overview.md
Match the arguments used for `c1`.
=> Fix constructor arguments for equality

working/0546-patterns/patterns-feature-specification.md
There are a large number of changes here, but structural and meaningful.
- Unify binder and matcher patterns into a single grammar.
- Always treat simple identifiers as variables in patterns.
- Change the `if (expr case pattern)` syntax.
- Change the guard syntax.
- Record patterns match only record objects.
- New patterns for relational operators, `|`, `&`, and `(...)`.
- Get rid of explicit wildcard patterns since they're redundant with
untyped variable patterns named `_`.
=> Revamp the patterns proposal.

working/0546-patterns/records-feature-specification.md
I think this matches the semantics in the struct proposal.
Fix #2390.
=> [patterns] Revise record identical() to be faster.

working/0546-patterns/records-feature-specification.md
A proposal for constant specifying records being constant.
Hope I covered all the corners. 
Basically, only two paragraphs are normative, the rest is elaboration.
Fixes #2337 
@mit-mit
=> Add section on records being constant.

working/0546-patterns/records-feature-specification.md
- Support constant records. Fix #2337.
- Support empty and one-positional-field records. Fix #2386.
- Re-add support for positional field getters Fix #2388.
- Specify the behavior of `toString()`. Fix #2389.
- Disambiguate record types in `on` clauses. Fix #2406.
cc @eernstg @stereotype441 @jakemac53 @natebosch @kallentu @mit-mit
=> Address a bunch of records issues.

working/0546-patterns/records-feature-specification.md
Opens up the opportunity to have static members, and is precise that there are no exposed constructors ("members inherited from `Object`" could be read as ambiguous about a default constructor).
=> Tweak `Records` class description

working/0546-patterns/patterns-feature-specification.md
- Add destructuring assignment. Fix #2438.
- Specify context type for empty list and map patterns. Fix #2441.
- Define grammar for outermost patterns in a declaration. Fix #2446.
- Rename "grouping" to "parenthesized" patterns. Fix #2447.
- Specify behavior of patterns in for loops better. Fix #2448.
There are enough substantive changes that I thought a real review would be worth it instead of just landing. If any of you have the time, I'd appreciate it. If not, I can always just merge.
=> [patterns] Destructuring assignment, clarify patterns in for, etc.

working/0546-patterns/patterns-feature-specification.md
Some patterns fail to match if the value doesn't have a certain type.
We still allow those patterns in irrefutable contexts if the matched
value is statically known to always have that type (or be dynamic).
Instead of specifying by having the refutability state of those patterns
depend on their type, make refutability a syntactic property and then
define the compile-time error for the types during type checking.
Fix #2450.
=> [patterns] Tease apart type testing from refutability.

working/0546-patterns/patterns-feature-specification.md
This makes them consistent with expressions, which should make parsing easier.  There should be no user-observable semantic difference.
=> Make logical patterns left-associative.

accepted/future-releases/records/records-feature-specification.md, working/0546-patterns/patterns-feature-specification.md
- Clarify that patterns can call extension members. Fix #2457.
- Non-boolean results throw in relational patterns. Fix #2461.
- Maps and extractors are evaluated in source order. Fix #2466.
- Specify non-exhaustive switch errors and warnings. Fix #2474.
- Allow `final` before type annotated variables. Fix #2486.
- Rename some grammars to align with Analyzer AST names. Fix #2491.
=> [patterns] A handful of mostly small changes to patterns and records:

working/1426-extension-types/feature-specification-views.md
This PR uses recent ideas (from the extension struct proposal and several other sources) to create a substantially revised version of the views proposal.
In particular:
- Views no longer have an `implements` clause.
- Views no longer support boxing. 
- Views allow for the use of a 'primary constructor' (a parenthesized list occurring right after the name and type parameters). Hence, the "wrapped" object is denoted by the name declared in this constructor, and `this` has the enclosing view as its type.
- Views use an `export` declaration in the body rather than a `show`/`hide` clause in the header to provide access to members of the underlying representation type.
- Views come in only two variants: Plain ones where the representation type and the view type are unrelated, and `implicit` …
=> Revise the views feature specification substantially

working/1426-extension-types/feature-specification-views.md
This is a draft revision of the views proposal, changing it to use `implements` rather than `extends` to declare superviews, and eliminating the support for `show` and `hide` in superviews (so every conflict has to be handled by overriding).
Added changes discussed at the meeting today Wednesday Sep 21: Deleted everything about the `export` declaration and everything about `show` and `hide`. Changed `view` to `view class` at the beginning of a view declaration.
=> Adjust views to use `implements`, and to not have show/hide

accepted/future-releases/records/records-feature-specification.md
Changelog reads:
> Allow positional fields in record types named hashCode, runtimeType, noSuchMethod, or toString.
So, I think, that it is a compile-time error to have a _named_ field with the name equal any of `Object` members
=> [Records] Fix typo. It's an error to have named field hashCode, etc..

working/1426-extension-types/feature-specification-views.md
Hi, @stereotype441, could you take a look? This update includes several changes motivated by your feedback, plus some symbol rename operations for consistency (such that the representation type is always called `R` and there are always `s` type parameters, etc).
=> Views spec updates based on discussion Sep 28

accepted/future-releases/records/records-feature-specification.md
I believe we decided to do this in a previous language meeting, just catching the proposal up to that.
=> [records] Allow "()" as an empty record expression.

specification/dartLangSpec.tex
This PR is a revert of lines 15992..16003 to the previous version of the same location. It removes the otherwise newly added run-time error during evaluation of an `<awaitExpression>`.
=> Remove a newly added run-time error for await evaluation

working/0546-patterns/patterns-feature-specification.md
Context: https://github.com/dart-lang/language/issues/2554
If a list/map pattern has an explicit type argument, use that as the element/key/value types used to match sub-patterns against, not the element type of the matched value.
This makes a difference for something like:
```dart
var <num>[x] = <int>[1]; /*1*/
var <num>[y] = <int>[1] as dynamic; /*2*/
```
where the declared type of `x` will be taken from the `<num>` instead of being `int` for `/*1*/`, and the declared type of`y` will also be `num` instead of `dynamic`.
Some wording tweaks.
=> Update type-checking of patterns to use type arguments.

working/sealed-types/feature-specification.md
I forked this off from the larger type-modifiers strawman for a few reasons:
*   That strawman also proposed disallowing mixing in classes which is a larger breaking change that will require a migration. We almost certainly can't get that done in time for patterns.
*   There is a lot more motivation around keyword choices in that doc which is useful to have tracked, but not super relevant for a feature spec, at least not at that level of detail.
*   The "closed" and "base" modifiers in that proposal are small features with no breakage, and can likely be done quickly. But they'll still probably be behind a separate experiment flag from "sealed", so I thought it made sense to propose those separately.
I also changed the keyword from "switch" to "sealed". While some liked the former, my …
=> Write separate more detailed spec for sealed types.

working/0546-patterns/patterns-feature-specification.md
Fix #2553.
I think this captures the discussion on #2553 and what we talked about today, but let me know if I missed something. One restriction I ended up *not* doing is making it an error to have the same variable in different cases with different types. It's only an error to try to *use* it in the body. I didn't see any need to make it an error since we treat the variables in each case as separate declarations anyway.
Instead, we synthesize a scope for the body that has all variables declared by any of the cases. Then we determine at compile-time which ones do appear in all cases with the same type and finality. Those are the only ones that you can use inside the body. This feels fairly natural to me, but let me know if it seems hard to implement.
cc @leafpetersen @lrhn @eernstg …
=> [patterns] Refine variable scoping rules for cases that share a body.

accepted/future-releases/0546-patterns/feature-specification.md
Get rid of "case" and "default" and use "," to separate.
Fix #2126.
=> Tweak the switch expression syntax.

accepted/future-releases/0546-patterns/feature-specification.md
Change the "variables" part of section "Type checking and pattern required type" to consistently refer to the unpromoted type of the variable as its static type rather than its declared type.  Rationale: in the implementations, the term "declared type" is consistently used to refer to a type that's explicitly specified by the user for the variable pattern (and is `null` if the type is inferred).
This change is consistent with the following text from the "Pattern variable sets" section:
> Each variable in the set has a unique name, a static type (the declared or inferred type, but not its promoted type), and whether it is final or not.
=> Patterns: adjust nomenclature of variable pattern types.

accepted/future-releases/0546-patterns/feature-specification.md
The required type of a subpattern of a record isn't well defined (required type isn't defined for all pattern types), and besides, we weren't doing anything with it anyhow.
=> [Patterns] drop unused reference to record subpattern required types.

accepted/future-releases/0546-patterns/feature-specification.md
The pattern type schemas for logical-or, null-check, constant, and relational patterns were not meaningful because pattern type schemas are only used in irrefutable contexts, and these patterns are not allowed to appear in irrefutable contexts.
In particular, the definition of pattern type schema for constant patterns was causing confusion because it appeared to cause a circularity: it defined the pattern type schema for a constant pattern to be the inferred type of the constant; however text elsewhere specifies that the type of the constant is inferred based on the type of the scrutinee, and the pattern type schema is used to infer the type of the scrutinee.  However this wasn't a real problem, because constant patterns are illegal in precisely the circumstances in whch pattern type …
=> [Patterns] remove irrelevant specification of pattern type schemas.

resources/type-system/upper-lower-bounds.md
This would have avoided the confusion that caused me to file https://github.com/dart-lang/language/issues/2648.
=> Add links from UP/DOWN (as defined on types) to UP/DOWN (as defined on type schemas).

accepted/future-releases/0546-patterns/feature-specification.md
The subpattern must be a variable pattern not in all cases but in case of `: pattern` only. Without this change it can be read as if subpattern always must be a variable pattern
=> [Patterns] Small clarification added

working/base-interface-final/feature-specification.md
Here's a new proposal for a set of capability modifiers on types. It supersedes my earlier "closed" and "base" proposal (#2592), which I'll close. It's heavily based on @leafpetersen's proposal (#2595), incorporates a suggestion from @natebosch to use a metadata annotation for `@reopen` and Erik's discussion of invariants you get from removing capabilities (which I hope I captured OK here).
Let me know what you think!
@mit-mit @stereotype441 @jakemac53 @kallentu
=> Proposal for "base", "interface" and "final" type modifiers.

specification/dartLangSpec.tex
Cf. https://github.com/dart-lang/language/issues/2611. The section 'Assignable Expressions' in the language specification is rather confusing. This PR makes it more explicit how we obtain the subterm of any given assignable expression that needs to be evaluated, if any (in `e.x = 42`, we need to evaluate `e`). It no longer specifies bottom-up how to evaluate forms like `e[v]`: It notes that when this subterm is an expression, it is evaluated following the same rules as any other expression.
=> Clarify section 'Assignable Expressions'

accepted/future-releases/0546-patterns/feature-specification.md
- Specify exhaustiveness checking of switch elements.
- Resolve ambiguity with `=>` in switch expression guards.
- Compile error if map pattern has identical keys.
Fix #2672.
Fix #2657.
=> [patterns] More small fixes.

working/base-interface-final/feature-specification.md
I went ahead and took the more aggressive step of also saying that you can't mixin a class unless it has the "mixin" modifier. However, that rule is gated by a language version so that it's not breaking.
Since "mixin class" allows you to preserve the previous behavior of class+mixin, I think we can get away with doing this change in one step. Basically, whenever you upgrade your library to the latest version, you add "mixin" to whatever classes you want to support being used as mixins and you're done.
If you think that's too aggressive, let me know and I can change this. If we do that, though, it ends up meaning that the "mixin" modifier doesn't actually *do* anything (except yell at you if you apply it to a class with a generative constructor or non-Object superclass).
Lasse, I really …
=> Add "mixin class" to the "base-interface-final" proposal.

accepted/future-releases/0546-patterns/feature-specification.md
This might be too specific. The real intent here is just that if it's a local variable or parameter and you can assign to it outside of a pattern, then you can assign to it in one too. If I correctly captured those rules, great. If not, let me know and I'll tweak it.
=> [patterns] Clarify which variables are valid in pattern assignments.

accepted/future-releases/0546-patterns/feature-specification.md
=> [patterns] Clarify when map key primitive `==` comes into play.

accepted/future-releases/0546-patterns/exhaustiveness.md, accepted/future-releases/0546-patterns/feature-specification.md
Some small fixes I found in going over the text, and replace `?` with `_` for type schemas to be consistent with the current syntax in `inference.md`.
=> Minor fixes to the patterns proposal

accepted/future-releases/0546-patterns/feature-specification.md
When I "fixed" #2636, I typo-ed the grammar and got it wrong.
This makes it what I meant to write.
=> [patterns] Fix the grammar for "||" and "&&" patterns.

specification/dartLangSpec.tex
Adjust definition of flatten to ensure that `flatten(X) == X` when `X` is a type variable which is unrelated to future types. It deletes the case which is explicitly dealing with type variables, and relies on the existing cases where the given type is related to `FutureOr` or `Future`, but adds one thing: The `FutureOr` case is applicable to types that are _bounded_ by `FutureOr<S>` for some `S`, not just the ones that _are_ `FutureOr<S>`, and this includes `X extends FutureOr<S>`.
=> Adjust definition of flatten

working/1426-extension-types/feature-specification-views.md
Hi Michael, I think it is important to include a note into the Views feature specification about the renaming to 'inline classes'. In particular, the Flutter@Google newsletter included a link to the views feature specification. This PR does that, and adds a link to the PR (to be updated to the landed document when landed). WDYT?
=> Add note about renaming to "inline class"

specification/dart.sty, specification/dartLangSpec.tex
The definition of flatten needed yet another revision in order to cover intersection types properly.
=> Update flatten definition

accepted/future-releases/0546-patterns/feature-specification.md
Object pattern grammar is
```
objectPattern ::= typeName typeArguments? '(' patternFields? ')'
```
So, there should be a `typeName`, not an `objectName`
=> [Patterns] Fixed typo in the specification

accepted/future-releases/inline-classes/feature-specification.md, working/1426-extension-types/feature-specification-views.md
This PR adds a feature specification of 'inline classes', which was obtained by taking the current version of the feature specification of 'views' and rename the construct from 'view class' to 'inline class'. It also removes the support for primary constructors (such that we get more time to get that feature just right and introduce it in general, not just for inline classes).
Finally, this PR adjusts the text accordingly. In particular, it changes the word 'superview' to 'superinterface', and it specifies that it is a compile-time error for an inline class to have a type `T` in the `implements` clause unless `T` is an inline class.
The rules about name clashes among "inherited" names are unchanged: It is a compile-time error if an inline class `V` has superinterfaces `V1` and `V2`, and …
=> Add feature specification for inline classes

specification/dartLangSpec.tex
Cf. https://github.com/dart-lang/language/pull/2052. This PR changes an example in the language specification section on `noSuchMethod` such that it is correct with null safety (it is correct without null safety as well, so we can do it now, and it will simply be there when we land the null safety updates).
=> Change noSuchMethod example to be correct with null safety

accepted/future-releases/0546-patterns/feature-specification.md
If this syntax were allowed, one would expect it to bind the variables from both patterns.  The way to do that is with "&&".
Also fix a minor typo, in a separate commit.
=> [patterns] Fix "||" vs "&&" in rationale for no repeated named fields

accepted/future-releases/inline-classes/feature-specification.md
This PR specifies that an inline class declaration can be `final`. No other type modifiers can be used with an inline class declaration.
Close #2734.
=> Add rules about type modifiers on inline class declarations

specification/dartLangSpec.tex
This PR updates the language specification such that the notion of having a 'primitive operator `==`' is replaced by the notion of having 'primitive equality', and it adds constraints on the objects and classes such that they only have primitive equality if they satisfy some constraints on operator `==` (same as before) and on `hashCode` (which is new).
The point is that we wish to maintain that equality as a whole (involving operator `==` as well as `hashCode`) can be relied upon to have a behavior which is known by language processing tools (such as compilers and analyzers). The rules of today (before this PR) allow `hashCode` to be overridden arbitrarily, and this implies that constant sets and non-constant hash sets would have different semantics in the case where the overridden …
=> Adjust `primitive operator ==` to `primitive equality`, and include `hashCode`

accepted/2.17/enhanced-enums/feature-specification.md
The specified grammar does not support an `<enumEntry>` of the form `name.new(...)` or `name.new<...>(...)`. We do have a test for this case, and it seems reasonable to allow it. This PR adds support for `new` to occur in that position to the feature spec.
(There is no associated implementation work because the test already runs without failure.)
=> [enhanced enums] Add support for NEW in enumEntry

accepted/future-releases/0546-patterns/feature-specification.md
-   Allow object pattern fields to tear off methods.
-   No exception for non-exhaustive switch statements that don't need
to be exhaustive.
-   Promoted types and bounds can be always-exhaustive.
-   Fix incorrect static error with cast patterns in assignments.
-   Clarify that patterns are not const contexts.
Fix #2561.
Fix #2698.
Fix #2765.
Fix #2758.
=> [patterns] Fix a handful of small-ish patterns issues:

accepted/future-releases/class-modifiers/feature-specification.md
Specifies that a `class C = S with M;` declaration cannot  be made a `mixin class`, but can use the other modifiers. Specifies that a `mixin class` (or a non-`mixin` `class` used as a mixin inside the same library) can declare *trivial* generative constructors.
Small tweaks.
=> Allow trivial constructors on mixin classes.

accepted/future-releases/0546-patterns/feature-specification.md
I'm finding the document is too long to navigate just by scrolling.
Also fixed one of the "Rest elements" subheadings (which was clearly meant to be nested under "Map pattern"), and renamed one of the "Pattern uses" headings to disambiguate it.
=> Clean up some headings in the patterns proposal.

accepted/future-releases/0546-patterns/feature-specification.md
There are no user-visible syntax or semantic changes here. It only changes how the grammar is organized.
Fix #2714.
=> [patterns] Disambiguate identifiers in the pattern grammar.

accepted/future-releases/0546-patterns/feature-specification.md
Before the change there was another error `The value of type 'int' is not assignable to the required type 'List<int>'`
=> [Patterns] Fixed typo in the variable declaration scope example

accepted/future-releases/0546-patterns/feature-specification.md
This got slightly broken when I moved identifiers out to a separate pattern grammar. This PR puts it back to right.
Fix #2795.
I took the opportunity to slightly clean things up too. Thanks for noticing, @sgrekhov!
=> [patterns] Fix spec for context type schema of variable and identifiers.

accepted/future-releases/0546-patterns/feature-specification.md
The exhaustiveness algorithm defines when a case is unreachable, but the proposal didn't actually do anything with that information. This closes that gap.
cc @lrhn @johnniwinther
=> Warn if a switch case is unreachable because prior cases cover it.

accepted/future-releases/class-modifiers/feature-specification.md
It looks like the prose (which I think is correct) got out of sync with the grammar. This fixes that.
I also tweaked the Markdown formatting a bit because I'm a little obsessive. I'm sorry.
cc @eernstg @kallentu
=> [class mods] Fix grammar to prohibit "mixin" on mixin applications.

accepted/future-releases/inline-classes/feature-specification.md
Turns out that there was a stray Control-T at some point, swapping two characters and thus messing up a URI. This PR fixes it.
=> Fix typo in URI

specification/dartLangSpec.tex
Cf. https://github.com/dart-lang/language/issues/1461.
This PR updates the 'rationale' paragraph about the Dart type system and its status as sound or unsound. The previous wording had not been changed for several years (if at all?), and it gave rise to some confusion because it stated that the Dart type system is unsound. The new text puts the emphasis on the static typing guarantees that we actually have, and mentions that Dart typing has developed over time to be more and more strict.
=> Specify not unsound

accepted/future-releases/0546-patterns/feature-specification.md
This PR changes several locations in the patterns feature specification where the 'required type' of a pattern is discussed. It adds rules about the required type in some cases where it was left unspecified. In particular, it says that the constant expression in a relationalPattern is type checked with the context type `_` (I can't see that we have anything else). The required type of a relationalPattern is kept open (`Object?`). The actual checks associated with this kind of pattern are performed during the traversal of the pattern, and there is no single type `T` would would make the same checks occur just by being the matched value type.
The changes include a somewhat controversial part: The definition of "assignable". The new text changes the order of the two bullet points where …
=> Adjust several locations where required types are discussed

working/augmentation-libraries/feature-specification.md
I removed the line about `abstract` and instead chose to say that all class modifiers must be present on both the augmentation type and the original type. This is I think consistent with the requirement to duplicate the type parameters, and it ensures people won't be confused about the modifiers on a class when looking at only the augmentation.
Open for debate certainly though! We could go the opposite direction and drop the `class/mixin/enum` keywords from augmentation libraries, as well as duplicate type parameters, thus eliminating all redundant information. So you could augment any class/mixin/enum by doing just:
```
augment <typename> {
<members>
}
```
=> Update augmentation library spec for class modifiers

accepted/future-releases/0546-patterns/feature-specification.md
We now unconditionally prohibit function literals inside guards, regardless of whether their bodies take the form `=> expression` or a block.  This matches what was implemented in the parser.
See discussion in https://github.com/dart-lang/sdk/issues/51482.
=> Change the disambiguation rule for function literals inside guards.

accepted/future-releases/0546-patterns/feature-specification.md
Fixes #2770.
Note that this behaviour has already been fully implemented--see https://github.com/dart-lang/sdk/commit/c358118e9f09e24add2c4f93339bbe5faafce9fd.
=> Specify that downwards inference of object pattern required types uses instantiate to bounds.

accepted/future-releases/0546-patterns/exhaustiveness.md
This is based on Johnni's excellent implementation. I tried to follow the semantics of the implementation as closely as I could, and mostly stuck to the terminology too. The main change is that the implementation uses "type" to also sort of do some restriction stuff, and I tried to keep that separate here such that a "type" on a space always refers to a static type.
I'm sure there are some mistakes here (but I of course don't know where they are). I imagine it will take some iteration between the implementation, the spec, and the tests before they settle on some kind of fixpoint. But this should hopefully be enough to start writing some co19 tests.
cc @sgrekhov
=> Rewrite the exhaustiveness specification.

accepted/future-releases/class-modifiers/feature-specification.md
* Tighten the modifiers implied on anonymous mixin class applications.
* Claim that `enum` declarations are `final`.
* Allow pre-feature libraries to mix in platform no-mixin classes if they could before.
* A little rephrasing, to allow reusing a concept.
But do not allow `interface mixin class` etc. anyway.
@munificent @kallentu
=> Update class modifiers specification.

.github/workflows/dart.yml, accepted/2.3/spread-collections/benchmarks/bin/lrhn_benchmark.dart, accepted/2.3/spread-collections/benchmarks/bin/profile.dart, accepted/2.3/spread-collections/benchmarks/bin/profile_list_spread.dart, accepted/2.3/spread-collections/benchmarks/bin/profile_map.dart, accepted/2.3/spread-collections/benchmarks/pubspec.yaml
This may be controversial, but I wanted to send it out anyways to see what kind of reaction it gets :).
This also migrates an old benchmark to null safety so it can be ran with Dart 3. I will separate out that change if we don't land this PR. I already submitted other fixes upstream, I just missed that one :).
This is helpful because otherwise all the diagnostics become pointless/unusable, as you are drowned in a sea of them (there were well over 100 until yesterday, and I previously cleaned up a similar amount). It also just looks unprofessional IMO if our repo has a bunch of diagnostics when you clone it.
This repo is constantly collecting new diagnostics today, so the problem just gets worse and worse. I suspect most of the language team are not heavy users of IDEs which report …
=> Add a github actions workflow for dart analysis and tests

accepted/future-releases/class-modifiers/feature-specification.md
Regarding reopened mixins and reopening mixins, I think @eernstg [worded it well](https://github.com/dart-lang/linter/pull/4235#discussion_r1152164227):
> It is not possible to reopen a mixin or a mixin class: It has the modifier `base` or no modifier, and no subtype of a `base` declaration can exist without a modifier which is at least as strong as `base`.
Based on this, I made these changes:
* removed "or mixin" from the things which can be annotated with `@reopen`
* removed "or mixin" from the things which can be extended or mixed in and be modified with `interface` or `final`
* spread a sentence which has 7 "or"s in it 🤣 across two bullet points.
CC @pq @kallentu @munificent
=> Remove "mixin" from some positions in the @reopen text.

specification/dartLangSpec.tex
The use of a lexical token named `NEWLINE` plus a vague wording caused some confusion about the treatment of source code line breaks when they occur in a multi-line string literal. This PR clarifies it.
=> Clarify the meaning of newline characters in multi-line string literals

accepted/future-releases/0546-patterns/feature-specification.md
The implementation only prohibits function literals inside the guards of switch expressions.  This change adjusts the spec to match.
Fixes https://github.com/dart-lang/sdk/issues/51905.
=> Fix function literal ambiguity resolution.

accepted/future-releases/class-modifiers/feature-specification.md
Cf. https://github.com/dart-lang/language/issues/2998: This PR adds a paragraph where it is stated that every enum declaration is considered to be a `final` declaration with respect to the rules where certain class modifiers are required to exist.
The changelog says that the feature spec already says so, but I couldn't find it.
=> Mention that enums are implicitly final

accepted/future-releases/0546-patterns/feature-specification.md
This shouldn't affect the implemented behavior but it avoids an unclear specification corner where two record map keys could or could not be considered the same since record identity is deliberately unspecified.
Fix #2979.
=> Clarify the compile error for "same" map keys.

accepted/future-releases/class-modifiers/feature-specification.md
This PR adds an error to the class modifiers feature spec for the case where an `on` type is `final` and from a different library.
=> Add an error for `on F` where `F` is final and outside the current library

analysis_options.yaml, working/macros/example/benchmark/simple.dart, working/macros/example/benchmark/src/data_class.dart, working/macros/example/benchmark/src/injectable.dart, working/macros/example/benchmark/src/shared.dart, working/macros/example/bin/injectable_main.dart, working/macros/example/bin/run.dart, working/macros/example/lib/injectable.dart, working/macros/example/lib/util.dart, working/macros/example/pubspec.yaml
This adds a basic Dagger2-like DI framework example, loosely based on this youtube video https://www.youtube.com/watch?v=oK_XtfXPkqw. There are 3 macros, `@Injectable` (for injectable classes), `@Provides` (for modules, it is how they provide specific implementations), and `@Component` which takes a bunch of modules and uses them to provide the final instances of things.
Feel free to just rubber stamp this if you want, there is a lot of just basic restructuring I had to do in order to generalize things so I could see some actual output. But it a lot of code to just push without at least giving an opportunity to get a review :).
The interesting stuff is in `working/macros/example/lib/injectable.dart`, if you just want to look at that :).
Also keep in mind this is all quite prototype-y so I …
=> Dependency injection example for macros

accepted/future-releases/0546-patterns/feature-specification.md
Cf. https://github.com/dart-lang/language/issues/2907.
=> Add void whitelist item for switch expression case

accepted/future-releases/0546-patterns/feature-specification.md
This spec change reflects the discussion at https://github.com/dart-lang/sdk/issues/52199#issuecomment-1526297771.
Test cases are here: https://dart-review.googlesource.com/c/sdk/+/300320
=> Prohibit variable and identifier patterns from being named `when` or `as`, to simplify parsing.

accepted/future-releases/class-modifiers/feature-specification.md
@leafpetersen @eernstg 
If that is what we want, this might do it.
=> Allow `extends Object` and `= Object with N` for mixin classes.

.github/workflows/ci.yml, .github/workflows/dart.yml
these haven't been running since the branch name switch
=> Update github workflows to run against main

working/augmentation-libraries/feature-specification.md
Closes https://github.com/dart-lang/language/issues/3041
This reverses the previous behavior for `external`, so that `augment super` is always allowed but may throw at runtime.
=> specify some semantics around augmenting external members

working/augmentation-libraries/feature-specification.md
Closes https://github.com/dart-lang/language/issues/3046.
Partly resolves https://github.com/dart-lang/language/issues/3041.
I altered the proposal to simply disallow augmenting getters and setters with variables. While this is potentially possible to specify, I think it is difficult to explain the behavior and wouldn't be intuitive. We can always add it back later.
In particular, I think we may later add the ability to augment abstract/external getters/setters with variables.
@johnniwinther do you know if this would cause any problems for the patch file -> augmentation library conversions? Do we implement any getters and/or setters with fields?
=> update how variable augmentations work

working/macros/feature-specification.md
Closes https://github.com/dart-lang/language/issues/1929 by allowing all constant expressions, but they can only contain literals.
=> allow all constant expressions as long as they contain only literals

working/macros/feature-specification.md
The real intention of allowing Identifiers was to allow types, but we also want to allow type arguments. This removes the ability to have arbitrary Identifier arguments and replaces that with TypeAnnotation arguments.
We might want to add Identifier arguments also, to handle non-type identifiers, but I don't really have a use case.
=> Update arguments spec to allow TypeAnnotations instead of Identifiers

working/macros/example/analysis_options.yaml, working/macros/example/benchmark/simple.dart, working/macros/example/benchmark/src/functional_widget.dart, working/macros/example/bin/run.dart, working/macros/example/lib/auto_dispose.dart, working/macros/example/lib/data_class.dart, working/macros/example/lib/functional_widget.dart, working/macros/example/lib/injectable.dart, working/macros/example/lib/json_serializable.dart, working/macros/example/lib/observable.dart
This adds a new macro `@FunctionalWidget(<identifier>)`. It generates a widget with the given name (from the identifier) from a function. Fields are inferred from the parameters, for example:
```dart
@FunctionalWidget(MyApp)
Widget _buildApp(BuildContext context, ValueNotifier<int> counter,
{String? appTitle, String? homePageTitle}) {
return MaterialApp(
title: appTitle ?? 'Flutter Demo',
theme: ThemeData(primarySwatch: Colors.blue),
home: MyHomePage(counter,
title: homePageTitle ?? 'Flutter Demo Home Page'));
}
```
Would generate this widget class:
```dart
class MyApp extends StatelessWidget {
final ValueNotifier<int> counter;
final String? appTitle;
final String? homePageTitle;
const MyApp(this.counter, {this.appTitle, this.homePageTitle, Key? key})
: super(key: key);
@override
Widget …
```
=> Add functional widget macro example

working/macros/feature-specification.md
Closes https://github.com/dart-lang/language/issues/3036.
=> specify conditional imports and introspection

working/macros/feature-specification.md
Related to https://github.com/dart-lang/language/issues/1931 and https://github.com/dart-lang/language/issues/1908
=> Make it an error to generate macro applications that apply to previous phases

specification/dart.sty, specification/dartLangSpec.tex
Leaf and Lasse, I believe you might discuss this PR and decide on whether one of you would give it a review. For now I'm just putting it on github such that reviewing can start whenever it fits (I guess it makes sense to wait for #2023).
This PR updates the sections 'Variables' and 'Local Variable Declarations' of the language specification to fit the language with null safety.
It is part of a larger PR, but provided in smaller pieces in order to make the reviewing task manageable. Because of this, the updated text contains a handful of undefined `\ref{...}` references. They refer to newly added sections which are included in https://github.com/dart-lang/language/pull/2023.
Apart from that, this PR changes `dart.sty` to a new version of the file which will work with all the null safety …
=> Specify null safety: Sections 'Variables' and 'Local Variable Declarations'

working/macros/feature-specification.md
In the phases example, it uses an unnamed type `Owner`. This changes it to `Human` so it is easier for the reader to follow.
Fixes: [#3225](https://github.com/dart-lang/language/issues/3225)
---
<details>
- …
=> Update macros readme to make phases example easier to understand

specification/dartLangSpec.tex
The language specification currently uses an `<identifier>` as the name of an `<extensionDeclaration>`. Implementations require this name to be a `<typeIdentifier>`, just like class and mixin declarations.
I see no value in forcing implementations to accept a built-in identifier as the name of an extension. This PR changes the language specification accordingly, which ensures that it is in sync with the implementations. This is arguably more consistent, and yields more readable code.
Added another small cleanup, cf. https://dart-review.googlesource.com/c/sdk/+/288981: Moves `?` from `typeNotVoidNotFunction` rule to usages, such that we do not (syntactically) allow constructs like `extends C?`, which are errors anyway.
Cf. https://github.com/dart-lang/sdk/issues/51751.
=> Change `<extensionDeclaration>` to use `<typeIdentifier>`

specification/dartLangSpec.tex
In issue #3148, it is reported that there is a soundness issue with the computation of the element type of a generator function whose declared return type is `FutureOr<Iterable<int>?>`, and similar issues with other union types.
This PR changes the definition of this element type such that return types are simplified to `Iterable<...>` or `Stream<...>` before the element type is computed, if possible. `Object` and top types still yield the element type `dynamic`.
Moreover, this PR also adjusts the specification of the dynamic type of the returned iterable/stream accordingly.
NB: This PR introduces null-safety related material into the existing language specification. We have done this in other cases as well. In general, we're aiming to integrate all the null-safety related material into …
=> Adjust generator element type, cf. dart-lang/language#3148

accepted/future-releases/extension-types/feature-specification.md
This PR changes the requirement on a non-extension type `T` that occurs in `implements ... T ...` in an extension type declaration: It must be a supertype of the representation type. Before this change it had to be a supertype of the erasure of the representation type, but that rule has some counter-intuitive and conceptually dubious consequences.
Cf. https://github.com/dart-lang/language/issues/3261 for more details.
=> Adjust the rule about `implements NonExtensionType`

accepted/3.0/patterns/feature-specification.md
I did some testing and it looks like the implementations are already doing the right thing and caching trailing list elements across patterns, so we may as well update the proposal to match.
This should help ensure we specify it right when it ends up in the spec.
Fix #2922.
=> Fix how trailing list subpatterns are cached

accepted/future-releases/extension-types/feature-specification.md
[Edit: This PR is now much simpler. Adjusted the description accordingly.]
This PR adds a covariance rule for subtyping of extension types, specifies that it is a compile-time error for an extension type member to be abstract, and it specifies that the last case in en the type function UP (that is, the Dart 1 algorithm for computation of the 'least upper bound' of two types) will work on a slightly extended superinterface graph.
=> [extension-types] Add rules about non-extension types

accepted/future-releases/extension-types/feature-specification.md
The current rule about instance variable declarations in an extension type declaration is that every instance variable declaration is a compile-time error (we only allow the implicitly induced instance variable which is caused by the parameter declaration in the primary constructor which is now syntactically the `<representationDeclaration>`, because we don't yet have primary constructors).
However, it is not an error to declare an external getter and/or setter, and an `external` instance variable declaration is just a convenient notation for exactly that.
This PR just clarifies that an external instance variable is not an error.
Fixes https://github.com/dart-lang/language/issues/3301.
=> Clarify that an extension type _can_ have instance variables which are external

working/0107 - implicit-constructors/feature-specification.md
This PR adds a proposal to the working directory about implicit constructors, provided as members of static extensions.
=> Specify implicit construction

accepted/2.15/constructor-tearoffs/feature-specification.md, accepted/future-releases/extension-types/feature-specification.md
This PR changes the wording of one commentary in the extension type feature specification, and adds missing type arguments in the return type of a tear-off of a constructor of a generic class in the constructor tear-off feature specification.
=> Small feature specification fixes

working/macros/example/bin/checks_main.dart, working/macros/example/bin/run.dart, working/macros/example/lib/checks_extensions.dart, working/macros/example/pubspec.yaml, working/macros/feature-specification.md
This macro generates extensions for a list of types, for use with `package:checks`. It isn't yet runnable as I need to do a bit of upstream work, but should be a good start.
I also updated the spec for extensions, allowing introspection on the `on` type _as well as all generic type parameters_. @munificent I added you to review that part. I also reworded that section just a bit and added a bit more general clarification.
=> add basic checks extension macro

working/augmentation-libraries/feature-specification.md
Per our conversation today, this:
- Removes all mention of concrete variables.
- Augmenting with a variable now only ever means augmenting the initializer of the augmented variable.
- Disallow augmenting external and abstract variables with variables.
=> remove mention of concrete variables, simplify rules around variable augmentation

accepted/future-releases/extension-types/feature-specification.md
We have a rule saying that it is an error to have a getter returning `R` and a corresponding setter whose parameter type is `S` if `R` is not a subtype of `S`.
This PR introduces the same rule for an extension type declaration.
=> Clarify that the usual getter/setter type rule exists for extension types as well

accepted/future-releases/extension-types/feature-specification.md
We used to have a hint in the extension type feature specification that the representation variable can be promoted just like a final local variable. This is not true (cf. https://github.com/dart-lang/sdk/issues/53446#issuecomment-1715131920). This PR changes the feature specification such that it does not make that claim any more.
Correction: Promotion of the representation variable _is_ sound, cf. https://github.com/dart-lang/sdk/issues/53446#issuecomment-1715782114. However, this PR still cleans up the text.
Another PR will follow when we have decided on the applicability of promotion to representation variables, cf. https://github.com/dart-lang/language/issues/3342.
=> Removed incorrect claim about promotability

.github/workflows/spec.yml
Update the specification validation workflow:
- always validate the specification - try to create the spec pdf
- only perform the firebase upload step if the triggering event is a PR merge
This should address the issue where automated dependabot PRs to update our github actions deps fail CI (ala https://github.com/dart-lang/language/pull/3316).
---
<details>
- Most changes should add an entry to …
=> update the specification validation workflow

accepted/future-releases/extension-types/feature-specification.md
The extension type feature specification does not specify how to deal with `super` when it is used in the body of a member declaration. This PR adds the rule that it is a compile-time error to do so.
We should probably indicate a different way to specify this semantics. One possible approach is to invoke a constructor that does not perform any computations (`super.m()` will then be something like `V3(this).m()`), or using a cast (`(this as V3).m()`), or using an intermediate extension type (such that we can write a forwarding member `m2` in a context where the redeclaration that gave rise to this need in the first place does not exist: `V.m` calls `VIntermediate.m2` which calls `V3.m`).
=> Added rule that `super` in an extension type member is an error

working/macros/feature-specification.md
This moves us to a more user friendly format (all augmentations for a single type grouped together), and removes the incorrect statements about source offset stability.
Closes https://github.com/dart-lang/language/issues/3350
=> Change the specified augmentation library structure for macros

accepted/2.7/static-extension-methods/feature-specification.md
This PR adds a few words in the 'Status' paragraph to indicate that the static extension methods feature has been integrated into the language specification.
=> Mark extension methods as integrated into the language specification

accepted/future-releases/extension-types/feature-specification.md
In response to the discussion in https://github.com/dart-lang/language/issues/3383, this PR introduces a new compile-time error to the extension type feature specification: It is an error if the representation type is `Never` (or something with the same meaning).
=> Make it an error for the representation type of an extension type to be a bottom type

accepted/future-releases/extension-types/feature-specification.md
The extension type feature specification used to have a paragraph about invocations of members of `Object` (`hashCode`, operator `==`, etc). It stated that the signature was taken from `Object?`. This is not consistent with a situation like the following, because all other non-extension type members would be treated according to the signature known from the traversal of the superinterface graph.
This PR changes the given paragraph to commentary, and changes the text to simply say that members of `Object` receive exactly the same treatment as all other non-extension type members. This yields the following behavior:
```dart
class A {
void foo() {}
}
class B implements A {
@override
void foo([int i = 0]) {}
@override
String toString([bool whatever = true]) => super.toString();
}
extension …
```
=> [extension types] Adjust the paragraph about Object members: They do not need special treatment

accepted/future-releases/extension-types/feature-specification.md
This PR adds an error for `implements ... T ... T ...` which is identical to the corresponding rule about classes, mixins, and enums. It is still an opinion rather than a soundness requirement or any "hard" requirement like that, but we might as well have it everywhere, and then we can change it everywhere in the future, if needed.
=> [extension-types] Add error for duplicate `implements` type

accepted/future-releases/extension-types/feature-specification.md
This PR adds an error  to extension types that corresponds to a similar rule for classes, mixins, etc: It is a compile-time error for a type variable declared by an extension type to occur in a non-covariant position of a superinterface. For example:
```dart
extension type E1<X>(int i) {}
extension type E2<X>(int i) implements E1<void Function(X)> {} // Error: `X` occurs contravariantly.
```
=> Add error for non-covariant type variable in superinterface

accepted/3.0/records/feature-specification.md
See https://github.com/dart-lang/sdk/issues/53679.
This PR adds a short section to the records feature specification to define `NNBD_TOP_MERGE` in the case where it is applied to record types.
=> Define NNBD_TOP_MERGE on record types

working/macros/aspect-macros.md, working/macros/example/benchmark/src/shared.dart, working/macros/feature-specification.md, working/macros/motivation.md
Updates to annotation introspection based on recent discussions, and in anticipation of changing the rules around shadowing.
The primary concrete change here is that we only allow access to identifiers/constructors from separate strongly connected components. This works around any issues with the constants changing between phases.
I decided not to try and restrict the API to code objects that came from annotations, so this does enable general purpose const evaluation, but it doesn't seem any more problematic to me than allowing the evaluation of const expressions from annotations. Please correct me if I am wrong :).
cc @scheglov @johnniwinther
=> specify the annotation introspection API and constant evaluation API

accepted/future-releases/extension-types/feature-specification.md
Based on the discussion in https://github.com/dart-lang/language/issues/3397, this PR introduces a relaxation in the rule about the required typing relationship between the representation type `R2` of an extension type `E2` and an implemented extension type `E1` with instantiated representation type `R1`:
The existing rule requires that `R2` is a subtype of `R1`. The new rule includes the old rule, but also allows the situation where `R2` is a subtype of `E1`.
Example, allowed before and now:
```dart
extension type FancyWidget(Widget _) {
// Something
}
extension type FancyListWidget(ListWidget _) implements FancyWidget {
// Something
}
```
Example, allowed now (but used to be an error):
```dart
extension type FancyString(String it) implements String {
// Something
}
extension type …
```
=> [extension types] Relax rule on representation/implements type relation

specification/dart.sty, specification/dartLangSpec.tex
This PR adjusts the Dart grammar such that the name of an `extension` declaration can not be `type`, without turning `type` into a built-in identifier. This eliminates an ambiguity where the same declaration could at the same time be an extension type declaration and an extension declaration. See https://github.com/dart-lang/language/issues/3258 for more details.
=> Update the grammar to prevent an extension from having the name `type`

working/macros/feature-specification.md
Closes https://github.com/dart-lang/language/issues/3446
=> Allow macro application annotations to be introspectable

working/macros/feature-specification.md
Closes https://github.com/dart-lang/language/issues/3348
cc @scheglov
=> change shadowing rules to remove need for multiple resolutions

resources/type-system/upper-lower-bounds.md
This PR moves the rules about intersection types up to an earlier position in the definition of `UP`, such that no results are of the form `(X & B)?`. (Types of that form should never exist, so `UP` shouldn't produce them.)
This is a much nicer solution than https://github.com/dart-lang/language/pull/2427, but it may have to be considered as a breaking change.
We should probably try it out and see how much breaks. Otherwise we can adopt #2427.
[Edit: The `X extends B` rules are no longer moved along with the `X & B` rules, that was a more substantial breaking change, and not useful.]
=> Move up the intersection type rules in the definition of `UP`

accepted/2.17/enhanced-enums/feature-specification.md
It is possible to use a constant redirecting generative constructor in an extension type together with a constant redirecting factory constructor in an `enum` declaration to create enumerated values of that enum that aren't distinct.
This PR introduces a compile-time error for enumerated value declarations that give rise to an invocation of a factory constructor, such that this situation cannot arise.
See https://github.com/dart-lang/language/issues/3460 for further information.
=> Add error about factory constructor generating an enum value

accepted/future-releases/extension-types/feature-specification.md
See the proposal in https://github.com/dart-lang/language/issues/3415. This PR changes the extension type feature specification such that the nullability of the representation type does not matter for the determination of the superinterface graph and subtype relationships of the types expressed based on a given extension type declaration:
An extension type is always a proper subtype of `Object?`, and as such it is potentially nullable (unless some further subtype relations exist). An extension type can declare that it `implements T` for various `T`, and this may cause the extension type to be a subtype of `Object` (directly or indirectly). In this case the extension type is non-nullable.
This change is a substantial simplification because the superinterface graph is shared among of all …
=> Change extension types such that they must declare subtype relations to `Object`

accepted/future-releases/extension-types/feature-specification.md
Background: See https://github.com/dart-lang/sdk/issues/53717, https://github.com/dart-lang/sdk/issues/53719, https://github.com/dart-lang/sdk/issues/53720.
This PR changes the extension types feature specification such that a method declaration in an extension type will shadow an "inherited" setter, and vice versa. This eliminates a setter/method conflict which couldn't otherwise be resolved.
For example:
```dart
extension type E1(int i) {
set m1(_) {}
void m2() {} 
get m3 => 1;
set m4(_) {}
}
extension type E2(int i) implements E1 {
void m1() {} // OK, and `E2` does not have a setter named `m1=`.
set m2(_) {} // OK, and `E2` does not have a method named `m2`.
set m3(_) {} // OK, and `E2` has the full getter/setter pair.
get m4 => 1; // OK, and `E2` has the full getter/setter pair.
} …
```
=> [extension types] Specify that a method shadows an "inherited" setter, and vice versa

specification/dartLangSpec.tex
This PR changes the specified ordering of the dynamic error that occurs if `p` is a deferred prefix of a non-loaded deferred library, and an invocation of the form `p.f(...)` is executed: The error occurs before any actual arguments to `f` are evaluated.
This change is motivated by the fact that the actual implemented behavior is as specified _with_ this PR, whereas the currently specified behavior differs from the actual behavior.
This is not a breaking change because the actual behavior will not change, we are simply adjusting the specification to say what the implementations already do, and have indeed done for several years.
=> Specify ordering of dynamic error for p.f(...) where p is a deferred prefix

working/macros/feature-specification.md
=> Update macro spec to allow more introspection in Phase 2.

accepted/future-releases/extension-types/feature-specification.md
See https://github.com/dart-lang/sdk/issues/53719#issuecomment-1828272923 for some background.
This PR adds rules to specify that a precluded member does not contribute to a conflict. This is a small adjustment to the rules which were added in https://github.com/dart-lang/language/pull/3470.
For example:
```dart
extension type E1(int it) {
void foo() {}
}
extension type E2(int it) {
int get foo => 0;
}
extension type E3(int it) implements E1, E2 {
set foo(_) {} // No setter/method conflict occurs here.
}
void main() {
var e3 = E3(1);
e3.foo = true; // OK, `E3` has this setter.
e3.foo; // OK, `E3` has this getter.
e3.foo(); // Error, `E3` does not have this method, and the getter doesn't return a function.
}
```
The rationale is as follows: If `E3` had had `implements E1` then `E3` would …
=> [extension types] Member conflicts ignore precluded members 

specification/dartLangSpec.tex
Thanks to @modulovalue for [reporting](https://github.com/dart-lang/sdk/issues/54218) this grammar fault!
It is possible to import 'dart:core' with a prefix `p`. This causes the built-in class `Function` to be denoted by the term `p.Function` (whereas the plain identifier `Function` is a lookup failure, or it denotes something else, or it actually works because we're _also_ explicitly importing 'dart:core' without a prefix).
In any case, we should allow `p.Function` in the grammar. This PR changes said grammar rule such that this is achieved.
=> Correct grammar rule for `<typeNotVoidNotFunction>` to allow prefix

specification/dartLangSpec.tex
See #3468 where the underlying issue was reported. This PR changes the definition of constant expressions such that `e1 ~/ e2` is allowed with `int` and/or `double` operands, whereas the current specification only allows `int`. There is no implementation effort, both the CFE and the analyzer behave in this manner already.
=> Correct constant expression spec per #3468

specification/dartLangSpec.tex
It has been a compile-time error (possibly a syntax error) for many years if an `initializerExpression` is a function literal. For example:
```dart
class A {
var x;
A() : x = () {}; // Error.
}
```
The reason for this is that the block, `{}`, could be the  body of the constructor (at least in the case where the formal parameter declarations can be an expression, which includes cases like `()` and `(x)` and `(x, y)`), and we will not know whether the block is the body of a function literal or the body of the constructor until we encounter (or do not encounter) a semicolon at the very end.
This rule has been around for a long time, and it is there for a good reason, but it wasn't specified. This CL adds a paragraph to the language specification that specifies this rule.
This CL also adds …
=> Specify that an `initializerExpression` cannot be a function literal

accepted/3.0/patterns/feature-specification.md
See https://github.com/dart-lang/sdk/issues/54246 where @modulovalue raised this issue.
This PR changes the syntax of `<objectPattern>` such that it allows `Function` to be the denotation of a type (for example: `Function(: var toString)`).
The analyzer and the common front end already implement this behavior, hence there's no implementation effort.
=> Adjust objectPattern to allow `Function()`

specification/dartLangSpec.tex
The compile-time error which is reported by the common front end for a declaration of a formal parameter as an initializing formal (`this.name`) was not specified precisely until now (it was just mentioned in commentary and never spelled out in normative text).
This PR changes the commentary to normative text.
One question may still give rise to debate: Can external constructors have initializing formals? This would be an enhancement, and it is handled in https://github.com/dart-lang/language/issues/3516. If that enhancement is accepted then we will change the specification later on in a different PR&mdash;this PR just specifies the current situation and makes it an error.
There will be an implementation effort in any case: If this PR is landed and the error reported by the CFE follows …
=> Specify precisely where it is an error to declare an initializing formal

accepted/3.0/patterns/exhaustiveness.md
This PR changes the definition of the lifted space union of a cast pattern, cf. the discussion in https://github.com/dart-lang/sdk/issues/54125 and the soundness issue https://github.com/dart-lang/language/issues/3488. The specification is intended to be well aligned with the [upcoming implementation](https://dart-review.googlesource.com/c/sdk/+/333922).
=> [patterns] Adjust cast pattern space definition

specification/dartLangSpec.tex
See https://github.com/dart-lang/language/issues/3491 where this change was discussed.
This PR makes it a compile-time error for a mixin `on` type to be super-bounded. This rule is similar to several other cases (it is an error for a type in an `extends`, `implements`, or `with` clause to be super-bounded as well). For mixins it is justified by the fact that it is impossible to use a mixin with a super-bounded `on` type.
There is no implementation effort because this is already the implemented behavior.
=> Add rule to make it an error for a mixin `on` type to be super-bounded

working/macros/example/benchmark/src/functional_widget.dart, working/macros/example/lib/functional_widget.dart, working/macros/example/lib/inherited_widget.dart
This would reduce the "Scoped Data Propagation" example [here](https://www.jetpackcompose.app/compare-declarative-frameworks/JetpackCompose-vs-SwiftUI-vs-Flutter) to the following (when used with FunctionalWidget):
```dart
@InheritedWidget()
class CustomInheritedWidget {
final String data;
}
@FunctionalWidget()
Parent _parent(BuildContext context, String data) => CustomInheritedWidget(
data: data,
child: Intermediate(),
);
@FunctionalWidget()
Intermediate _intermediate(BuildContext context) => Child();
@FunctionalWidget()
Child _child(BuildContext context) {
final data = CustomInheritedWidget.of(context).data;
return Text("Received data: $data");
}
// Usage
Parent(data: "Some data")
```
I also cleaned up FunctinalWidget a bit while I was at it.
cc @goderbauer wdyt about a macro like this?
=> add InheritedWidget macro example and fix up FunctionalWidget

working/macros/example/benchmark/simple.dart, working/macros/example/benchmark/src/json_serializable.dart, working/macros/example/lib/json_serializable.dart
- Add support for a `toJson` method.
- Directly apply separate FromJson/ToJson macros in the declaration phase, instead of scanning the class for methods.
This is a precursor to moving this macro into the SDK as a language test, possibly the last update to this macro in this repo.
=> Updates to the JsonSerialization macro example.

working/macros/feature-specification.md
=> [macros] Appling a macro in the wrong place is an error.

accepted/future-releases/extension-types/feature-specification.md
See the discussion in https://github.com/dart-lang/language/issues/2710.
This PR introduces the notion of a type which is _incompatible with await_ and uses that to specify the compile-time error which occurs in the case where `await e` is encountered, and the static type of `e` is incompatible with await. The main case is when said static type is an extension type that does not implement `Future` (that's the case that we had already), but this new rule includes more cases, e.g., the case where the static type is `E?` where `E` is an extension type that does not implement `Future`.
=> Adjust the rule about await e where the type of e is an extension type

accepted/future-releases/extension-types/feature-specification.md
See https://github.com/dart-lang/language/issues/3524#issuecomment-1875649080 for background information.
This PR adds a rule to the extension type feature specification, specifying that an extension type is always-exhaustive if and only if its instantiated representation type is always-exhaustive (note that this rule may be applied repeatedly because the representation type could itself be an extension type).
Example:
```dart
extension type SmartBool(bool b) {}
String foo(SmartBool sb) {
switch (sb) { // This switch must be exhaustive.
case SmartBool(b: true): return 'True';
case SmartBool(b: false): return 'False';
}
}
```
=> Add a rule to determine which extension types are always-exhaustive

specification/dartLangSpec.tex
I'm working on a larger doc to explain this but here's a proposed small change to the spec to say that warnings don't have to be reported.
@dart-lang/language-team
=> Update spec to say that reporting warnings is not mandatory.

accepted/future-releases/extension-types/feature-specification.md
This PR adds a rule to the extension type feature specification saying that if `e` is an expression whose type is an extension type that has a method named `call`, and `e` has a context type which is a function type or the type `Function`, then it is treated as `e.call`. This is just a word-for-word replication of the [corresponding rule](https://github.com/dart-lang/language/blob/d4813d54ccc04bfc6ff2470eb74d2202be6707ef/specification/dartLangSpec.tex#L14742) for other kinds of type, except that it's about extension types.
This mechanism is also known as "implicit `call` tear-offs".
The language team decided that we should allow implicit `call` tear-offs here: https://github.com/dart-lang/language/issues/3467#issuecomment-1854515768.
The implementation was handled here: …
=> Specify that implicit `call` tear-offs are supported for extension types

accepted/future-releases/extension-types/feature-specification.md
The PR https://github.com/dart-lang/language/pull/3560 introduced the notion of a type which is 'incompatible with await' and used that to introduce an error on `await e` when the static type of `e` is such a type.
This PR adjusts the definition of 'incompatible with await' such that `X & S` is incompatible with await when `S` is incompatible with await. This is a bit more strict than the previous version. It is motivated by the fact that a promotion of a variable of type `X` to a type `X & S` where `S` isn't compatible with await is a strong signal that it should not be awaited.
Of course, `await (e as T)` for some suitable value of `T` can always be used to force the await.
The change is not breaking because 'incompatible with await' has not yet been implemented in any release.
=> Adjust incompatible-with-await to be more strict on intersections

accepted/3.0/records/feature-specification.md
If the context of a record literal is the same shape as the record literal, but the actual type of one or more fields is not a subtype of the corresponding field in the context type, and no coercion is possible, then the implementations do not necessarily issue an error. They only issue an error if the type mismatch leads to an assignability error during subsequent analysis.
An example of a circumstance where the type mismatch doesn't lead to an assignability error is if the context resulted from assignment to a previously promoted local variable. For example:
f(Object o) {
if (o is (int,)) {
o = ('',); // OK; demotes `o` back to `Object`.
}
}
This change adjusts the spec to agree with what was implemented.
---
<details>
- See our …
=> Fix records type inference rules to match implementations.

working/macros/example/benchmark/src/data_class.dart, working/macros/example/benchmark/src/shared.dart
- When benching augmentation library creation, include results from earlier stages 
- Only do formatting at the very end
- Add code optimization at the very end
- Make comparisons fair, only call `run` once inside the synchronous benchmarks.
Results for code optimization look fairly reasonable, ~25μs (total macro execution takes around 2ms prior to that, ignoring formatting).
Formatting is slower but maybe reasonable, around 450 μs.
Example run here https://gist.github.com/jakemac53/096b8380db41aa2eda46ae189a510c29.
cc @jacob314
=> Updates to data class macro benchmarks, add code optimizer benchmark

accepted/3.0/records/feature-specification.md
See https://github.com/dart-lang/sdk/issues/55008#issuecomment-1964229795 for some background information.
The feature specification about records does not specify the meaning of `const` in front of a record expression, but it does allow `const` in that position. This PR adds a paragraph about this question. The idea is that `e` occurs in a constant context if it occurs as `const (..., e, ...)` or if `e` occurs in a record expression `(..., e, ...)` that occurs in a constant context.
This would not be a breaking change: The CFE already behaves in this way. The analyzer accepts `const (...)` where `(...)` is a record expressions where one or more field expressions are non-constant, so there is a certain amount of work to do on the analyzer.
=> Specify the interaction between record expressions and constant contexts

specification/dartLangSpec.tex
See https://github.com/dart-lang/sdk/issues/54628 for some background information.
This PR changes the definition of 'derives a future type' (which is used to define _flatten_) such that it includes some additional cases (in particular, it will recursively handle `?` on types, which was not the case previously).
=> Enhance the definition of "derives a future type"

working/augmentation-libraries/feature-specification.md
This PR updates various grammar rules of the augmentation library feature specification. In particular, it adds rules to specify augmented extension, extension type, and enumerated declarations, and it makes several adjustments to the `topLevelDecrlaration` and `declaration` derivation rules in order to be up to date with other features.
=> Update grammar rules of augmentation library feature specification

working/augmentation-libraries/feature-specification.md
Based on the response in https://github.com/dart-lang/language/issues/3646, this PR specifies a compile-time error which occurs if a main library _L_ which is being augmented along with all augmentation libraries _A<sub>1</sub> .. A<sub>k</sub>_ reachable from _L_ via one or more `import augment` links forms a graph that has a cycle.
This PR also makes it an error for a `<uri>` in an `import augment` directive to denote a regular library, it must be an augmentation library. This change is also based on #3646.
Finally, this PR makes it an error for a `<uri>` in a regular `import` directive (not `import augment`) to denote an entity which is not a library (including: it's an error if it is an augmentation library).
=> Specify errors about wrong `import augment`/`import` structures

working/augmentation-libraries/feature-specification.md
It is a compile-time error for an extension augment to specify `on` clause. Extension also cannot specify `extends`, `implements` or `with` clauses, so it's unecessery in this list
=> Extension augment can't specify `on` and other clauses

working/augmentation-libraries/feature-specification.md
The feature specification includes examples where an `enum` value has the form `augment <identifier>`, but the grammar doesn't allow for the keyword `augment` in that position. This PR adds the missing grammar rule.
=> Add an `enumEntry` grammar rule

working/333 - shared memory multithreading/proposal.md
Initial proposal attempting to introduce shared memory multithreading.
/cc @leafpetersen @lrhn @eernstg @munificent 
/cc @a-siva @alexmarkov @mkustermann @dcharkes @liamappelbe @chinmaygarde 
/fyi @syg @kevmoo
=> Shared Memory Multithreading

working/augmentation-libraries/feature-specification.md
In response to https://github.com/dart-lang/language/issues/3687, this PR changes the grammar rule `<extensionDeclaration>` such that an augmenting extension declaration does not have an `on` clause syntactically. The compile-time error caused by having such an `on` clause is removed (it is now a syntax error). The text about extensions is adjusted slightly elsewhere to fit these changes.
This resolves a contradiction: An `augment extension` declaration used to be a syntax error if it did not have an `on` clause, but an `augment extension` declaration _with_ an `on` clause was a compile-time error.
=> Adjust the extensionDeclaration syntax

working/macros/feature-specification.md
fixes https://github.com/dart-lang/language/issues/3709
=> fix link to macro API docs

working/augmentation-libraries/feature-specification.md
This PR adds a compile-time error to the feature specification about augmentations. See https://github.com/dart-lang/language/issues/3702 for some background.
The newly specified error occurs when a function augmentation body contains `augmented(...)`, and the augmented declaration has no implementation, for example:
```dart
// Library 'main.dart'.
import augment 'augment.dart';
class C {
void f(); // Allowed when implemented in an augmentation.
}
// Library augmentation 'augment.dart'.
augment library 'main.dart';
augment class C {
augment void f() {
augmented(); // Compile-time error (not today, but if this PR is landed).
}
}
```
I do not think there is any other reasonable response than reporting a compile-time error:
Another option could be to allow this at compile time and throw at …
=> Add compile-time errors about `augmented`

working/wildcards/feature-specification.md
This PR adds rules to the wildcards feature specification about super parameters of the form `super._`, and about representation declarations in extension types whose representation variable name is `_`.
In particular, `super._` is an error because super parameters that can't be referenced from the initializer list are inherently broken. In contrast, `extension type E(int _) {}` is allowed: The representation variable name will be `_` and the formal parameter will be inaccessible (which makes no difference at this time, but will matter if a more general primary constructors feature is introduced).
=> Add rules about super and extension types to wildcard spec

working/0015-infer-required/feature-specification.md
This PR adds a feature specification of the feature whereby `required` is added implicitly to parameters of concrete function and method declarations when it would be an error to not have that modifier.
=> Add a proposal about inference of the modifier `required`

specification/dartLangSpec.tex
The association that binds each metadatum in a Dart program to a language construct is specified in a way that is somewhat inconsistent with the grammar. For example, it associates the metadata declared in front of a `<libraryName>` with the keyword `library`, not with the library name directive as a whole.
This PR changes the wording such that metadata which occurs at the beginning of a grammar rule is associated with the construct as a whole. If the metadata occurs in any other location in the rule then we continue to use the rule which is specified prior to this PR: The metadata is associated with the program construct which is derived from the following non-terminal. The latter rule works well with cases like `<classDeclaration> ::= ... (<metadata> <classMemberDeclaration>)* ...`. …
=> Update the specification section about metadata

working/wildcards/feature-specification.md
This PR adds information about the existing [`no_wildcard_variable_uses`](https://dart.dev/tools/linter-rules/no_wildcard_variable_uses) lint which should help the migration of the wildcards feature. 
It's already a core lint and should be enabled in most projects, meaning that the breakage for the wildcards feature should be small.
Anyways, writing is hard -- so let me know if I should add/remove/change something. Thanks 😄
=> [wildcard-variables] Add 'no_wildcard_variable_uses' lint to breaking change section.

working/wildcards/feature-specification.md
Updates the spec from discussion on the two following issues: https://github.com/dart-lang/language/issues/3791 and https://github.com/dart-lang/language/issues/3790.
I wanted to update the spec to make some parts clearer to future readers.
Can you both take a look and let me know how I can wordsmith this better?
=> [wildcard-variables] Add more explicit details on functions and records.

working/wildcards/feature-specification.md
This PR addresses Erik's comments in https://github.com/dart-lang/language/pull/3802#pullrequestreview-2059953529.
=> [wildcard-variables] Clarify wildcard behaviour on functions.

working/0323-null-aware-elements/feature-specification.md
Stuffing the `?` directly inside `expressionElement` and `mapEntryElement` lets us reuse some existing specification around leaf elements, but is otherwise confusing because it makes the case analysis for the different kinds of elements non-disjoint.
This fixes that by defining entirely separate rules for null-aware elements.
=> Use separate grammar rules for null-aware elements.

resources/type-system/inference.md
This is just the beginning of my effort; I'm sending it around to get feedback on the style and general approach I'm taking.
What's included here:
- Some overview information, including some text about soundness guarantees (I want to include informal proofs of soundness as non-normative text along with the inference algorithm, so I need to define some terms).
- Details about coercions (not complete).
- Inference for the following expression types: `null`, numbers, boolean literals, string literals (including interpolation), symbol literals, `throw`, `this`, logical boolean expressions, and `await`.
- Thanks for your contribution! Please replace this text with a description of what this PR is changing or adding and why, list any relevant issues, and review the contribution guidelines …
=> Initial efforts at specifying inference in function bodies and initializers

working/wildcards/feature-specification.md
Unnamed (and private) extensions are non visible after the import. To make the example valid an extension should have a name
=> [wildcard-variables] Fix typo in 'imports' example.

working/wildcards/feature-specification.md
Missing `extends` added
cc @kallentu
=> [wildcard-variables] Fix a typo in the super parameters example.

working/macros/dart_model/README.md, working/macros/dart_model/dart_model/lib/delta.dart, working/macros/dart_model/dart_model/lib/model.dart, working/macros/dart_model/dart_model_analyzer_service/lib/dart_model_analyzer_service.dart, working/macros/dart_model/macro_client/lib/macro_client.dart, working/macros/dart_model/macro_host/bin/main.dart, working/macros/dart_model/macro_host/lib/macro_host.dart, working/macros/dart_model/testing/benchmark/bin/main.dart, working/macros/dart_model/testing/benchmark/lib/random.dart, working/macros/dart_model/testing/benchmark/lib/trivial_macros/input_generator.dart, working/macros/dart_model/testing/benchmark/lib/trivial_macros/macros.dart, working/macros/dart_model/testing/benchmark/lib/workspace.dart, working/macros/dart_model/testing/benchmark/pubspec.yaml, working/macros/dart_model/testing/presubmit, working/macros/dart_model/testing/scratch/lib/scratch.dart, working/macros/dart_model/testing/test_macros/bin/main.dart, working/macros/dart_model/testing/test_macros/lib/equals_macro.dart, working/macros/dart_model/testing/test_macros/lib/hash_code_macro.dart, working/macros/dart_model/testing/test_macros/lib/to_string_macro.dart
https://github.com/dart-lang/language/issues/3706
=> [macros] Add benchmark case generator, ToString() macro

working/macros/host-notes.md
Add host implementation notes doc.
=> [macros] Add host implementation notes.

working/macros/dart_model/README.md, working/macros/dart_model/testing/json_benchmark/bin/main.dart, working/macros/dart_model/testing/json_benchmark/lib/json_benchmark.dart, working/macros/dart_model/testing/json_benchmark/lib/json_buffer.dart, working/macros/dart_model/testing/json_benchmark/lib/json_buffer_subject.dart, working/macros/dart_model/testing/json_benchmark/lib/json_subject.dart, working/macros/dart_model/testing/json_benchmark/lib/subject.dart, working/macros/dart_model/testing/json_benchmark/pubspec.yaml, working/macros/dart_model/testing/json_benchmark/test/json_buffer_test.dart, working/macros/dart_model/testing/presubmit, working/macros/dart_model/testing/pub_get
=> [macros] JSON benchmarks, JsonBuffer experiment.

working/wildcards/feature-specification.md
Added a section for unnamed optional parameters and them not needing default values.
Fixes: https://github.com/dart-lang/language/issues/3807
=> [wildcard-variables] Add section on unnamed optional parameters and their default values.

working/macros/dart-model.md
=> [macros] Add dart_model proposal.

README.md
The funnel was using legacy projects, which are scheduled to be discontinued in the late summer, so migrated it to a regular project, which changes the url.
---
<details>
- Changes to packages require …
=> Fix funnel link

README.md
Default branch is now `main` not `master` so link needs fixing
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing) …
=> Fix badge link in readme

accepted/2.7/static-extension-methods/feature-specification.md
I think all of these headings are mistakenly too low. Resolution etc. should not be under "Declaring ..."
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding …
=> Tweak headings so not everything is under "Declaring Static Extension Methods"

working/2364 - primary constructors/feature-specification.md, working/2364 - primary constructors/scripts/inline_class.json, working/2364 - primary constructors/scripts/inline_const_class.json, working/2364 - primary constructors/scripts/inline_generic_class.json, working/2364 - primary constructors/scripts/inline_named_class.json, working/2364 - primary constructors/scripts/inline_named_const_class.json, working/2364 - primary constructors/scripts/inline_subtyped_class.json, working/2364 - primary constructors/scripts/inline_subtyped_const_class.json, working/2364 - primary constructors/scripts/inline_subtyped_generic_class.json, working/2364 - primary constructors/scripts/inline_subtyped_generic_const_class.json, working/2364 - primary constructors/scripts/show_primary_constructors.dart
This PR makes adjustments to the proposal about primary constructors such that it is in line with the results from discussions at the recent physical language team meeting.
In particular, it removes support for a `primary` constructor which is declared in the body of the class/enum/etc, and only allows for the form which is part of the header of the class declaration. It also removes the ability to infer the modifier `required` in a formal parameter declaration.
(Inferred `required` is now a separate proposal, see https://github.com/dart-lang/language/blob/main/working/0015-infer-required/feature-specification.md.)
It preserves the ability to omit `final` from every parameter when the primary constructor is constant, because we already have the ability to omit `final` in the primary …
=> Update the primary constructors proposal

specification/dartLangSpec.tex
The PR https://github.com/dart-lang/language/pull/3495 changed the rule about `e1 ~/ e2` as a constant expression. This PR removes a spurious reference to the operator symbol `~/` (it should no longer be mentioned in the rule which doesn't cover `e1 ~/ e2` any more).
=> Remove spurious reference to `~/` in constant rule

specification/dartLangSpec.tex
This PR modifies the language specification by adding references to section 'Type dynamic' where the static typing of members of `Object` which is used with receivers of type dynamic at the locations where that static typing is used, that is: 'Ordinary Invocation' and 'Getter access and method extraction'.
=> Specify dynamic Object member invocations

resources/type-system/inference.md
The following changes (mostly based on suggestions by Leaf and Erik) are included:
- The text is now under a heading called "expression inference" rather than "body inference" (which was confusing).
- Instead of trying to describe the output of type inference using a vague notion of "expression artifacts" whose runtime behavior is described in prose, I'm specifying it using a Dart-like syntax called "elaborated expressions". Elaborated expressions look generally like Dart expressions, except they have some limitations (types are fully specified, and complex constructs like null shorting are desugared, and type checks are explicit) and support some extra forms (such as "let" expressions).
- I've simplified the terminology I use to describe the three things that can happen when an …
=> Rework expression inference spec draft based on review comments.

resources/type-system/inference.md, specification/dartLangSpec.tex
The lemma is that for all types `T`, `T <: FutureOr<flatten(T)>`. The lemma was claimed (without proof) in `dartLangSpec.tex`, so I've added a (non-normative) proof of it to the spec, right after the claim.
This made it possible to significantly simplify the reasoning around the soundness of `await` in `inference.md`.
Thanks to @lrhn for the core idea behind this.
---
<details>
- Most changes …
=> Simplify reasoning about await soundness using a lemma about flatten.

working/wildcards/feature-specification.md
Remove this behaviour from the spec. Linked to the discussion in the changelog.
Fixes: https://github.com/dart-lang/language/issues/3807
=> [wildcard-variables] Remove unnamed optional wildcards with no default.

working/augmentation-libraries/feature-specification.md
Closes https://github.com/dart-lang/language/issues/3879
=> specify that types can be omitted from augmenting declarations, and will be inferred from the original

working/augmentation-libraries/feature-specification.md
Thanks to @sgrekhov for pointing out that the following is a typo:
> *... `augmented` is just a normal identifier when it occurs anywhere other than inside an augmented declaration.
This PR corrects 'augmented' to 'augmenting'.
=> Fix typo in comment about `augmented`

working/augmentation-libraries/feature-specification.md
Closes https://github.com/dart-lang/language/issues/3417
Setters still use `augmented = <value>` and getters are still just `augmented`, but operators are now invoked using regular function syntax.
=> invoke augmented operators using function syntax

working/augmentation-libraries/feature-specification.md
Follow up to some comments on https://github.com/dart-lang/language/pull/3940 after it was merged
=> follow-up to omitting types in augmentations

working/augmentation-libraries/feature-specification.md
Closes https://github.com/dart-lang/language/issues/3957.
- Allows all declarations to be augmented with metadata/doc comments explicitly.
- Allows fields to be augmented with fields that contain no initializer. The augmented initializer is left in tact.
- Allow enum values to be augmented with no argument list. The augmented enum value keeps its original argument list in tact.
- Allow all function, getter, setter augmentations to have no body. The augmented body is left in tact.
- Unrelated, but I cleaned up many usages of "original" => "augmented"
I did not introduce an error to have a totally useless augmentation with no initializer/body, doc comments, or metadata, but I didn't see the need to introduce one. We could though if people think we should.
=> Allow augmentations of metadata and doc comments only for all kinds of augmentations

working/2364 - primary constructors/feature-specification.md
Two obvious enhancements from the language team meeting and from your proposal: Allow primary constructors to have assertions, and allow optional parameters to obtain their declared type from the default value.
=> Add assertions and variable types inferred from default values

working/2364 - primary constructors/feature-specification.md
By accident, this wasn't included when 3961 was landed.
=> Review response for 3961

working/augmentation-libraries/feature-specification.md
There are no semantic changes here, I just found the prose a little unclear on first read. In particular:
```
*   If the `part` directive including the file that contains *A*
is syntactically before the `part` directive including the file that
contains *B* in source order, then *A* is before *B*.
```
Is ambiguous because "includes" is transitive, so there may be multiple files whose `part` directives include A or B and it's not clear what that means when those `part` directives aren't in the same file.
Also made a couple of style and copy tweaks while I was at it.
I like the semantics!
=> Slightly clarify and copy-edit the augmentation ordering.

working/augmentation-libraries/feature-specification.md
The PR https://github.com/dart-lang/language/pull/3980 made a couple of changes by mistake which were essentially undoing the effect of #3954. This PR corrects that mistake.
=> Restore the changes made in version 1.23

working/augmentation-libraries/feature-specification.md
Closes https://github.com/dart-lang/language/issues/3998
- Clarifies some error cases for augmenting the getters/setters introduced by abstract and external variables.
- Removes an error blocking augmentation of an abstract/external variable with a variable. This is allowed as long as it retains it abstract/external keyword. It can be used to add comments or annotations.
=> clarify augmentations of abstract and external variables

working/augmentation-libraries/feature-specification.md
Closes https://github.com/dart-lang/language/issues/3689, will land after https://github.com/dart-lang/language/pull/4000 to keep the changelog in order.
We should be able to safely re-allow this later if a use case comes up. But I think simplifying it for now is better.
=> No longer allow altering enum value constructor invocations

working/augmentation-libraries/feature-specification.md
Closes https://github.com/dart-lang/language/issues/3694, will merge after https://github.com/dart-lang/language/pull/4002 for changelog consistency purposes.
I went for the simplest answer here, since I don't see a motivating use case for anything more complex.
- The "original" extension type declaration _must_ include the representation type.
- Augmentations of extension types _must not_ include the representation type.
There is a TODO for updating the grammar, I think the simplest option is to make the representation type optional for both regular extension type declarations and augmenting ones, and have the error introduced at a later stage. This would have better behavior for tooling so that the file can still be parsed (ie: the formatter can still format in the face of this error). …
=> update extension type augmentations to be more strict

working/augmentation-libraries/feature-specification.md
Closes https://github.com/dart-lang/language/issues/3977
Closes https://github.com/dart-lang/language/issues/3725
- Specify that the implicit null initialization of nullable fields does not happen unless no augmentation adds an initializer.
- Specify that variables which require an initializer do not have to define it initially - it may come from an augmentation.
To be merged after https://github.com/dart-lang/language/pull/4004 for changelog consistency
=> clarify some behavior around initializers

working/augmentation-libraries/feature-specification.md
This PR changes the grammar such that an augmenting extension type declaration does not specify a primary constructor. This means that there is no `const` modifier (which is optional on the introductory declaration, but it is not allowed at all on an augmenting extension type declaration). Also, there is no "parameter list" (known as the `<representationSpecification>` in the grammar).
=> Change the syntax of augmenting extension type declarations

working/unquoted-imports/feature-specification.md
Fix #3983.
Fix #3984.
cc @dart-lang/language-team
=> Allow reserved words in unquoted imports but disallow whitespace.

doc/life_of_a_language_feature.md
This PR adds the following information:
- Information about kick-off meetings
- How to create implementation tracking issues
- How to create a feature flag
- How to do language testing
- A note to remember to do Google3 testing (details of which will be described in a separate Google-internal document).
It also removes references to implementation plan documents, since we haven't created implementation plan documents for years.
=> Update life of a language feature documentation

working/augmentation-libraries/feature-specification.md
In issue #4015, it is argued that several system provided members of an enumerated declaration should not be augmentable, namely: `index`, `hashCode`, operator `==`, and `values`. This PR makes it a compile-time error to augment them.
It was also suggested that it should be an error to declare or augment a member of an enum named `name`, because this identifier should denote the system provided extension getter `name`. This PR does not introduce any rules about `name`, because it would be a breaking change to prevent `enum` declarations from declaring a member whose name is `name` (instance or static).
Resolves https://github.com/dart-lang/language/pull/4015.
=> Make adjustments following issue #4015

working/augmentation-libraries/feature-specification.md
With support for augmentation, variables can be declared with no initializing expression in a couple of new cases where this was previously a syntax error, namely constant and final top-level variables as well as constant and final static variables. This PR changes the grammar to allow this kind of declaration. The point is that the omitted initializing expression can be provided by augmentation. Similarly for factory constructor declarations, they do not have to have a body when the body can be provided by augmentation. Finally, static getters, setters, and methods are also generalized to allow omitting the body, that is, they are allowed to look like "abstract static members", again because the body can be provided by augmentation.
The set of elements that are required for each …
=> Enable various variables and factories with no implementation

working/0649 - Import shorthand/proposal.md
The file `working/0649 - Import shorthand/proposal.md` no longer contains said proposal, it has been moved to `archive/...`. The file in the original location just contains a link to the new location. Said link was broken, this PR corrects it.
=> Correct forwarding link about archived import shorthand proposal

working/augmentation-libraries/feature-specification.md
This PR adjusts some rules in the grammar such that it is possible to omit the implementation from certain declarations (similarly to #4106, but adding support in some cases that were omitted from #4106 by accident).
In particular, it allows external top-level declarations to be augmented (e.g., to add a DartDoc comment or metadata), and it allows an augmenting declaration of a top-level getter/setter/function to omit the body (which would then be provided by some other augmentation, or by the introductory declaration). Similarly for declarations of members in a class, mixin, enum, etc.
With these changes, _every_ alternative in the rule about `<declaration>` had `'augment'?` as the first part, which was redundant. So I moved `'augment'?` out of the `<declaration>` rule and into the …
=> Update the grammar to handle omitted implementations and broader augmentation

working/333 - shared memory multithreading/proposal.md
This revises shared memory multithreading proposal based on discussions we had internally and current implementation direction. 
The biggest change is complete removal of `Shareable` type marker - instead we accept that most likely destination for us would be _shared **anything** multithreading_.  
Another change is that proposal now describes in more details the intermediate _shared **native** multithreading_: which does not introduce any fundamentally new capabilities (only native memory can truly be shared), but at the same time addresses a lot of ergonomics issues around interoperability and concurrency model mismatch between Dart and native.
fyi @a-siva @johnmccutchan
=> Revise shared memory multithreading proposal

accepted/future-releases/0323-null-aware-elements/feature-specification.md
It seems in the second example given in the specification, both `'track'` and `'genre'` should be prefixed with `?`, as their initial form are exactly the same as `'title'` and `'year'`, respectively.
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#mak …
=> fix (apparent) typo in the null-aware-elements example

working/3616 - enum value shorthand/proposal-simple-lrhn.md
Makes `==` only special-case second operand.
*   Keeps context type for second operand, set its shorthand context instead.
*   Remember to mention `== e` pattern.
*   Clean-up and reflow.
=> Update enum shorthand, `==` and reflow edition.

working/3616 - enum value shorthand/proposal-simple-lrhn.md
I was reading the latest changes and noticed a duplicated sentence. And once I fixed that, I started noticing other things...
There are no semantic changes. This is just making it hopefully easier to read.
=> A little copy-editing on the enum shorthand proposal.

working/2364 - primary constructors/feature-specification.md
This PR updates the primary constructor feature specification based on recent ideas in an email thread. In particular, it introduces support for an initializer list in a primary constructor in the header of the enclosing declaration (of a class or an enum), and allows parameters to be declared without introducing an instance variable iff they are used for another purpose (such as `this.v = x` or `super.name(x)`).
I haven't reintroduced the in-body primary constructors (but we can easily do that, if requested).
As we've done on some earlier occasions, I'll land this document now (it is 'working'). The language team can then discuss it and adjust it as needed in further PRs.
=> Update primary constructor proposal based on email thread

working/augmentation-libraries/feature-specification.md
This PR introduces an error for the case where a redirection (`this(...)`) is augmented by another redirection, and similarly for a redirecting factory.
This follows the treatment of super-initializers, for which it is also an error to include one in an augmenting declaration if the augmented declaration already has an explicitly declared super-initializer.
Other than that, it clarifies the terminology of the augmentation feature specification slightly, such that we keep `this(...)` and `this.x = 42` clearly separated.
'redirecting initializer' is changed to 'redirection' when talking about generative redirecting constructors. The term is derived from `<redirection>`, and the word redirection is used in other specification documents about this kind of term. This also helps avoiding the …
=> Add an error and adjust the terminology slightly about augmented redirecting constructors

working/2364 - primary constructors/feature-specification.md
Yet another update to the primary constructors proposal, this time to use `this` as the "magic word" that turns a body constructor into a primary constructor.
=> Update body primary constructors to use `this`

working/declaring-constructors/feature-specification.md
-   Apply review feedback from Lasse.
-   Add section for inferring public parameter names from private ones.
-   Update grammar to allow `var` followed by a type.
-   Add lint for using `final` on parameters.
- Thanks for your contribution! Please replace this text with a description of what this PR is changing or adding and why, list any relevant issues, and review the contribution guidelines below.
=> Revise "declaring constructors".

working/3616 - enum value shorthand/proposal-simple-lrhn.md
`Endian.little` is not an enum value but a static constant. Fixed comment and added a real enum value example.
=> Update example in Static access shorthand proposal

working/augmentation-libraries/feature-specification.md
This is a paired down version of https://github.com/dart-lang/language/pull/4164.
It contains only the changes to the proposal we had previously discussed, making `augmented` have no special meaning in generative constructor bodies.
It does not change rules around initializing formals or super parameters (these must be consistent across the introductory and any augmenting declarations still).
I wanted to separate out this change from the much more complicated explanation of how these constructors should be evaluated.
=> Update specification for generative constructors

working/3616 - enum value shorthand/proposal-simple-lrhn.md
The feature specification about static access shorthands mentions constant expressions of the form `e!`. They do not exist so there's no need to discuss them. This PR removes that sentence.
=> Remove sentence about `e!` being constant

working/enhanced-constructors/feature-specification.md
This proposal extends the set of actions that can be performed in the body of a non-redirecting generative constructor to include writing to non-late final fields and explicitly invoking super constructors.
This makes constructors more flexible, avoids the need for constructor initializer lists, and allows constructor augmentations to behave more consistently with function augmentations.
To preserve soundness, flow analysis is enhanced to ensure that a reference to `this` cannot escape from a constructor body before the object has been completely constructed.
Once this change has landed I will create the appropriate "feature" issue.
---
<details>
- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) …
=> Initial draft of enhanced constructors proposal.

accepted/future-releases/unquoted-imports/feature-specification.md
In #4038, Lasse suggests that we shouldn't allow unquoted `part of` directives but change what they mean to be package references since that will likely just break silently and confuse users. Unquoted imports (with the new proposed semantics) in part directives aren't really useful anyway since parts should always be in the same package and the quoted syntax is shorter for that.
So this PR changes the proposal to not apply the new syntax to `part` and `part of` directives. It also makes a language versioned breaking change to remove support for unquoted library names in `part of` directives entirely since the syntax is long deprecated, problematic, and would become very confusing in the context of other unquoted imports.
@dart-lang/language-team, PTAL since this proposal is already …
=> With "Unquoted Imports" disallow unquoted part of library names.

resources/type-system/flow-analysis.md
In fully sound null safety mode, flow analysis should know that a test like `expr == null` is guaranteed to evaluate to `false` if the static type of `expr` is non-nullable. But in unsound null safety mode, no such guarantee can be made.
Since support for unsound null safety was only recently removed from the CFE (see
https://github.com/dart-lang/sdk/commit/0060b0f665ac5b6865fdb9d91e8735a20ee3b160), flow analysis still conservatively assumes that an expression with a non-nullable static type might, nonetheless, still be `null`.
This change updates the spec to match the implementation in this regard, and adds a reference to
https://github.com/dart-lang/language/issues/3100, where we are discussing the possibility of changing the behavior.
- Thanks for your contribution! Please replace this …
=> [flow analysis] Update the spec to match implementation of `==`.

working/333 - shared memory multithreading/proposal.md
Amend shared native memory multithreading proposal to require that all captured variables are marked with `vm:shared` to make the closure shareable. This makes it clearer which values are crossing the boundary between isolates - which is significant for mutable values like `TypedData`. It is complete parallel to `vm:shared` annotations on static fields.
(This makes tear-offs not shareable - at least for now).
=> Require that captured variables are marked with vm:shared

specification/dartLangSpec.tex
See https://github.com/dart-lang/sdk/issues/60375 for background. This PR changes the rule about (pre-nnbd) switches such that they accept cases of the form `case e` where `e` is a constant expression whose value is an instance that has primitive equality (previously it was required that the class of this instance must have primitive equality, which is not true for, say, type literals).
=> Change switches to accept instances with primitive equality

resources/type-system/flow-analysis.md
This change fix three spec inaccuracies:
1. The spec claimed that when flow analysis encounters an expression `N` of the form `V = E` (a local variable assignment), it would set `true(N)` and `false(N)` based on `true(E)` and `false(E)`. Note that we *could* have implemented flow analysis this way; if we had, then a test like `if (v1 = v2 is T)` would have promoted `v2` to `T`. But we didn't implement that functionality.
2. The spec failed to document the special behavior of expressions of the form `E is Never`. Flow analysis knows that expressions of this form cannot evaluate to `true`.
3. The spec failed to document the special behavior of expressions of the form `E is! T`. `E is! T` is understood by flow analysis to behave the same as `!(E is T)`.
Fixes …
=> [flow analysis expressions] Fix instance check and assignment to match implementation.

specification/.gitignore, specification/Makefile, specification/dartLangSpec.tex, specification/pubspec.yaml, specification/scripts/addlatexhash.dart, specification/scripts/simplify_specification.dart
The language specification uses semantic line breaks and rather short lines. This means that it gets somewhat inconvenient to search in a number of situations. For example, we may find the command `\Error{compile-time error}` on one line and the text that describes which error it is on the next line. Also, when searching the language specification for hard facts it may create some noise that a rather large portion of the language specification is commentary, rationale, and comments.
This PR adds a small script that processes the language specification such that it is more convenient to search for hard facts: It removes comments, commentary, and rationale, and it joins paragraphs written as several lines into a single line. This terse version of the language specification can be created by …
=> Create a script to simplify the language specification

resources/type-system/flow-analysis.md
The `promotedTypes` list in a `VariableModel` is now consistently ordered from least promoted type to most promoted type, matching the list used in the implementation.
Also, the use of `top::rest` to refer to a stack is changed to `[...rest, top]`. This is consistent with the way some stacks are represented in the flow analysis implementation (as a list where pushing and popping happens at the end of the list).
Fixes https://github.com/dart-lang/language/issues/4367.
=> [flow analysis] Clean up promoted types ordering and use of `::`

resources/type-system/flow-analysis.md
This formulation will be consisent with the behavior of the implementation once https://dart-review.googlesource.com/c/sdk/+/427920 lands.
Fixes https://github.com/dart-lang/sdk/issues/60646.
=> [flow analysis] Rework demotion and type of interest promotion.

specification/dartLangSpec.tex
Following the decision at the language team meeting on May 14 2025, this PR changes the language specification such that `s?.length` is a constant expression when `s` satisfies certain requirements.
=> Add `s?.length` as a constant expression

working/4271 - static enough metaprogramming/proposal.md
This moves content from https://github.com/dart-lang/language/issues/4271 into a markdown file in the repository to make discussion and revisions easier.
I have incorporated some of the feedback from discussions on the issue - but I continue to maintain focus on this as a toolchain feature. I have added some remarks that analyzer can't constant fold everything anyway because it does not have access to the compilation environment.
I would like to collect a few rounds of feedback and then rejuvenate the prototype implementation to get something experimental working across all platforms in the SDK so that we can have an idea of how well this could work in a real world.
=> Create Static Enough Metaprogramming proposal

working/2364 - primary constructors/feature-specification.md
This PR adjusts the primary constructor proposal to use the approach where the in-header form is considered to be syntactic sugar for an in-body form ("moving the parameter list to the header"). In particular, this allows even the in-header constructor to have all features (initializer list, superinitializer, body), declared in the body.
It does not introduce abbreviations of non-primary constructor declarations (like `const();` as a short form for `const MyClass();`). That's a separate feature which can be handled elsewhere.
The description of the parameter list as "being moved to the header" implies that the parameter list will have the same semantics when declared in-body and in-header. In particular, the in-header form _does_ require an explicit token for a parameter to be declaring …
=> Refresh the primary constructor proposal to use new syntax

working/4213-generic-constructors/feature-specification.md
Here is a first version of said feature specification, based on the proposal in https://github.com/dart-lang/language/issues/4213.
=> Add feature specification of generic constructors

working/2364 - primary constructors/feature-specification.md
This PR updates the primary constructors proposal to include support for access to header parameters in non-late instance variable initializers, and in general updates the static analysis and semantics to the new syntax introduced by #4428.
The approach relies on a very simple change to the scoping structure: The primary header parameters are added to a new scope which is the enclosing scope of the class body scope. This is completely standard according to the syntactic structure, just like the scoping around a function body and its formal parameter declarations.
This means that header parameters with a fresh name (that is, not clashing with the names declared in the class body) are in scope in the class body. It is an error to refer to them in any other location than an initializing …
=> Update the primary constructors proposal to give the body access to header parameters

working/2509-private-named-parameters/feature-specification.md
Talk a bit about how the feature might be confusing at first and suggest ways we can mitigate that.
cc @bwilkerson for thoughts on error messages with this feature.
=> Add a "Concerns" section to "Private Named Parameters".

resources/type-system/flow-analysis.md
This change adjusts the specification of flow analysis for the following kinds of statements and expressions, to match what was actually implemented:
- conditional expressions
- if-null expressions
- logical and/or expressions
- null check operators
- break statements
- continue statements
- return statements
- if statements
- while statements
- for statements
- do while statements
- for each statements
- switch statements
- try statements
Also, the paragraphs describing "Local variable conditional assignment" and "Conditional assignment to a non local-variable" are dropped. These paragraphs were quite inaccurate, and the necessary infrastructure isn't in place yet to replace them with more accurate descriptions.
Finally, there's a minor fix: the definition of a promotion chain was …
=> [flow analysis] Rework control flow statements and expressions.

working/2509-private-named-parameters/feature-specification.md
Fix #4479.
This is a much more narrowly scoped solution to #4479. It doesn't change any scoping rules and there's nothing normative. But it aims to guide doc generators to hide the private implementation details of APIs.
If that's not a strong enough guarantee for the core libraries to rely on, then it may make sense for those libraries to not use private initializing formals in public APIs.
But for most users, I think this is plenty robust enough, and it avoids adding unnecessary complexity to the language.
If this one looks OK, then I'll close #4486.
=> Revise the section on documenting private parameters.

doc/life_of_a_language_feature.md
Add a few updates to the doc
- Tracking doc checklist
- Updating team names
- Add a forwarding stub when moving the spec
- Publicizing the feature after release
- Updating the SDK DEPS
=> Update language cycle doc with tracking doc, publicity, and release information

specification/dartLangSpec.tex
Update: This PR removes everything in the language specification that is concerned with documentation comments. The treatment of this topic area is now fully determined by each tool team.
---
Previous description:
The language specification specifies the syntax that makes a comment a DartDoc comment, which is unchanged. This PR adds a paragraph of 'rationale' text explaining that everything else is tool specific behavior, and it removes the rules about scoping in DartDoc comments.
There were no rules about the locations where a DartDoc comment can occur, which means that it is still "any location where a comment can occur".  Moreover, each tool can freely choose that a DartDoc comment is processed in a specific way when it occurs in a specific kind of location (including that it is …
=> Remove rules about DartDoc comments in the language specification

specification/dartLangSpec.tex
Was very under-specified.
This change changes the responsiveness of a `yield*` to be that of `StreamController.addStream`, meaning that it *immediately* reacts to pause and cancel and forwards it to the inner stream. Unlike `await for`, a `yield*` is at the yield for the entire duration of the inner stream, and can cancel at any time, not only when control reaches a `yield` inside the loop.
Experience has taught us that with `async*` functions, `await for` and `yield*`, back-pressure using `cancel` or `pause` *must* be acted on immediately, to avoid a stream computation continuing when it has nothing meaningful to do, and the caller knows that and tries to stop it.
For example, if you do `stream.first`, it should cancel after the first event, before starting on the computation of the next …
=> Update spec for yield*.

accepted/future-releases/primary-constructors/feature-specification.md
This PR corrects a couple of mistakes in the feature specification about declaring and primary constructors. It also introduces support for using `new` rather than the class name in declarations of non-declaring constructors (that is, all the kinds that we have today).
=> Update the declaring constructors feature specification
