dart-lang/language

background/README.md, background/how-other-languages-manage-breakage.md
This is based on a conversation Leaf and I had about whether we need to add some explicit notation to Dart in order to opt into new feature so that they aren't breaking changes.
=> Add doc with some background on how other languages approach breakage.

working/spread-collections/feature-specification.md
Addresses [this comment and below](https://github.com/dart-lang/language/issues/47#issuecomment-436784286).
=> Clarify null handling in spread expressions.

working/0107 - implicit-constructors/feature-brainstorm.md
I think I did everything right RE https://github.com/dart-lang/language/pull/105#pullrequestreview-178570718
=> Update implicit conversion doc with pointers to related issues

working/0110-incremental-sound-nnbd/roadmap.md
@lrhn @eernstg @mit-mit @munificent @vsmenon 
I've been hacking on a writeup of our discussions about an incremental  path to NNBD, and I think it's at a state where some broader feedback would be useful.  I'm putting this up as a PR for now just to make it easy to comment on, but I will probably land it and iterate on it tomorrow.  Please take a look, comments and feedback welcome (on the PR or via email).  This is still very much a high level roadmap, but If we broadly still think this is in line with what we want to propose to do, we should get this out in draft form to leads for discussion next week.
=> Add roadmap proposal for incremental sound nnbd

working/0110-incremental-sound-nnbd/roadmap.md
Added a detailed summary of my understanding of what our agreed on roadmap looks like, clarifying as many details as possible.  Also added an overview of what the external migration process should look like.
cc @mit-mit @dgrove @vsmenon @srawlins @Hixie
=> Update roadmap with migration details.

accepted/future-releases/spread-collections/implementation-plan.md
- call out that we'll need to update the IntelliJ parser (and, early in the process)
- refactor categories to call out where work will happen
=> Update the spread collections implementation plan

accepted/future-releases/control-flow-collections/feature-specification.md
Just an oversight on my part. Fix #154.
=> Include the set grammar changes in "Spread Collections".

resources/old-non-nullable-types.md
I'll close out the old PR in the SDK repo.
=> Add the old NNBD proposal as a resource.

accepted/future-releases/spread-collections/benchmarks/Makefile, accepted/future-releases/spread-collections/benchmarks/bin/profile.dart, accepted/future-releases/spread-collections/performance.md
I was feeling stuck without enough information to make an informed recommendation, so I went ahead and got as much benchmark data and tried my best to understand what the numbers were saying. Here's what I got.
What do you think? If you're OK with it, I'll also run it by the leads and see what they think. (And also so they can bikeshed my benchmarking methodology, naturally. 😄)
=> Add new spread benchmark and write up analysis of results.

resources/optional-semicolons-prototype.md
There's nothing actionable about this doc, so it doesn't need to be perfect. But I think it's worth landing to record my thoughts before they evaporate.
=> Write up summary of optional semicolon prototypes.

.travis.yml, specification/dartLangSpec.tex
Trim down installation size by using smaller packages rather than textlive-full
=> Trim travis install size

.travis.yml, specification/firebase.json
Auto-deploy a draft spec to https://dart-specification.firebaseapp.com/DartLangSpecDraft.pdf whenever dartLangSpec.tex changes
=> Update .travis.yml: Deploy draft PDF spec to Firebase

.travis.yml
=> Only run on updates to the master branch

specification/dartLangSpec.tex
This is the version of the language specification that includes implicit new and const.
=> Integrated implicit creation into the language specification

specification/dartLangSpec.tex
TBR: The changes made in response to the review of #249 were not uploaded; this PR does that.
=> Review response fixes for PR #249 (omitted by accident)

accepted/future-releases/unified-collections/feature-specification.md
=> Clarify spec for const ifElements.

specification/dartLangSpec.tex
I think this is what is intended?
=> Fix typo in assignableExpression grammar

accepted/future-releases/constant-update-2018/feature-specification.md, accepted/future-releases/triple-shift-operator/feature-specification.md
refering to #346 
I created a new PR.
=> fixed small errors

accepted/nnbd/roadmap.md
Start with just the roadmap, I'll land the draft feature spec shortly.
=> Move nnbd roadmap to accepted.

accepted/future-releases/language-versioning/language-versioning.md
- Restrict override syntax to only `// @dart = 2.3` format.
- Specify experiment flag behavior.
- Update `.packages` file format to contain entire SDK version. Needed by experiment flag behavior.
- Change `*:defaultPackage` to `:defaultPackage` because `*` was already a valid package name in the [`.packages` file specification](<https://github.com/lrhn/dep-pkgspec/blob/master/DEP-pkgspec.md>).
=> Update versioning feature specification.

accepted/future-releases/static-extension-methods/implementation-plan.md
(Blatantly copied from the control-flow-collections implementation plan).
=> Initial implementation plan for Static Extension Methods

specification/dartLangSpec.tex
Just two typo fixes that prevent LaTeX'ing.
=> Fixed two typo level latex errors

accepted/2.2/set-literals/implementation-plan.md, accepted/2.3/control-flow-collections/feature-specification.md, accepted/2.3/spread-collections/performance.md
=> Fix broken links

accepted/future-releases/static-extension-methods/feature-specification.md
=> a few typos

.github/ISSUE_TEMPLATE/1-PROBLEM_STATEMENT.md, .github/ISSUE_TEMPLATE/2-FEATURE.md, .github/ISSUE_TEMPLATE/3-BUG.md, README.md
Towards #584
Start with some rough descriptions on the types of issues we'd like to
see filed.
=> Add issue templates and contributing guide

working/0546-patterns/goals-and-constraints.md
Like I did with ui-as-code, I thought it would be good to start with a
high level picture of what we're hoping to achieve. This doc is that.
=> Starting to gather and formalize my thoughts around pattern matching.

specification/dart.sty, specification/dartLangSpec.tex
TBR: Merged PR #615 before uploading the last round of changes in response to review, by mistake. This PR contains those missing changes.
=> Review response to #615 re-uploaded

specification/dartLangSpec.tex
=> Fix spawnUri reference in spec

accepted/future-releases/nnbd/feature-specification.md
This incorporates several clarifications that have come up in discussions.
cc @MichaelRFairhurst @crelier @bwilkerson @stereotype441 @rakudrama @nshahan @stefantsov
=> Small updates to NNBD spec

accepted/future-releases/static-extension-methods/feature-specification.md
It is believed that the current implementations of both analyzer and front-end allows `E(e)?.foo` where `E` is an extension. This was previously not allowed by the design document.
It has a reasonable behavior, and we have chosen to allow it. This updates the design document to do so, and specify the behavior.
There will be tests.
=> Allow `E(e)?.id` in extension methods.

accepted/future-releases/nnbd/feature-specification.md, resources/type-system/upper-lower-bounds.md
Small clarifications to the NNBD spec and a bug fix to the DOWN algorithm.
=> Textual clarifications and lower bound bug fix

accepted/future-releases/nnbd/feature-specification.md
This specifies how the signatures induced by legacy and opted in classes interact.
=> Specify legacy interface interaction

resources/type-system/flow-analysis.md
Per feedback from @scheglov .
cc @lrhn @munificent @eernstg @johnniwinther @scheglov @stereotype441
=> Make definite assignment in try/finally better, clarify initialization promotion

accepted/future-releases/nnbd/feature-specification.md
Hoping this is a valid change.. if not feel free to close the PR
=> fix typo in changelog date

accepted/future-releases/nnbd/feature-specification.md, resources/type-system/normalization.md, resources/type-system/subtyping.md
This batches up a number of clarifications and changes that have accumulated.  
cc @lrhn @munificent @eernstg @scheglov @stefantsov @liamappelbe @crelier @nshahan @fishythefish @sigmundch @johnniwinther
=> Batched up spec updates

specification/dartLangSpec.tex
Cf. https://github.com/dart-lang/sdk/issues/40596.
=> Adjust static analysis of ordinary method invocation to admit callable object

resources/type-system/flow-analysis.md
Fixes to the flow analysis spec.
=> Flow analysis fixes

accepted/2.1/int-literal-as-double-value/feature-specification.md
Note: third addition/deletion (identical) is made by github itself, I don't know why.
=> Correct a typo

specification/dartLangSpec.tex
Cf. https://github.com/dart-lang/language/issues/896.
=> Define T bounded types, to allow f() where f has type X extends Function

accepted/future-releases/nnbd/feature-specification.md
Of course, I forgot to push the very last change, so #897 got landed without it. Here it is.
=> Updated changelog to describe effects of PR #897

accepted/future-releases/nnbd/feature-specification.md
Per discussion [here](https://github.com/dart-lang/language/issues/922).
Proposed test from @natebosch  [here](https://dart-review.googlesource.com/c/sdk/+/143329).
cc @munificent @lrhn @eernstg
=> Change default type of catch clause.

specification/dartLangSpec.tex
Nobody should be shamed for asking. Asking is the primary way to learn.
=> Remove passive aggressive language from the spec

accepted/future-releases/abstract-external-fields/feature-specification.md
Tests and Dart.g update in https://dart-review.googlesource.com/c/sdk/+/148324.
=> Add feature specification of external/abstract variables

accepted/future-releases/abstract-external-fields/feature-specification.md
Various adjustments of the text, cf. late comments on PR #969.
=> Response to late comments on PR #969

accepted/future-releases/nnbd/feature-specification.md
See https://github.com/dart-lang/sdk/issues/42603.
=> Clarify static behavior of `super == other` under NNBD.

resources/type-system/flow-analysis.md
For the corresponding fix to the implementation, see
https://github.com/dart-lang/sdk/commit/36e89f845b41eab06111b7fc479a5169a2b05cb5.
=> Ensure that restrictV never produces a promoted captured variable.

accepted/future-releases/nnbd/number-operation-typing.md
Alternative proposal.
Only infer static types of `int`, `double` or `num`, not the static type of the first operand if that happens to be a proper subtype of those.
=> Alternative which won't preserve the type of the first operand

resources/type-system/flow-analysis.md
See https://github.com/dart-lang/sdk/issues/41981
Corresponding implementation change is here:
https://dart-review.googlesource.com/c/sdk/+/154624
=> Flow analysis: promotion to `Never` makes code unreachable.

specification/dartLangSpec.tex
Cf. https://github.com/dart-lang/language/issues/1199.
=> Simplify the Dart grammar a bit

resources/type-system/flow-analysis.md
Note: this CL adjusts the implementation to match: https://dart-review.googlesource.com/c/sdk/+/162480
=> Specify flow analysis of for-each loops.

resources/type-system/flow-analysis.md
Fixes https://github.com/dart-lang/language/issues/1203.  Corresponding implementation change is here: https://dart-review.googlesource.com/c/sdk/+/162483
=> Flow analysis: specify for loops and fix types of interest for for/while loops

archive/feature-specifications/README.md, archive/feature-specifications/assert-in-initializer-list.md, archive/feature-specifications/covariant-from-class.md, archive/feature-specifications/covariant-overrides.md, archive/feature-specifications/dynamic-members.md, archive/feature-specifications/extreme-upper-lower-bounds.md, archive/feature-specifications/generalized-void.md, archive/feature-specifications/generic-function-instantiation.md, archive/feature-specifications/generic-function-type-alias.md, archive/feature-specifications/generic-method-syntax.md, archive/feature-specifications/implicit-creation.md, archive/feature-specifications/instantiate-to-bound.md, archive/feature-specifications/int-to-double.md, archive/feature-specifications/int64.md, archive/feature-specifications/interface-conflicts.md, archive/feature-specifications/invalid_returns.md, archive/feature-specifications/mixin-declaration.md, archive/feature-specifications/mixin-inference.md, archive/feature-specifications/nosuchmethod-forwarding.md, archive/feature-specifications/optional-new-const.md, archive/feature-specifications/subtyping.md, archive/feature-specifications/super-bounded-types.md
=> Copy "informal" feature specifications to language repository.

specification/dartLangSpec.tex
=> Remove unused non-terminal <variableDeclaration>

specification/dartLangSpec.tex
I'm sorry, I forgot to press enter so the review related changes weren't uploaded before #1374 was landed. Here they are.
=> Review based corrections to #1374

accepted/future-releases/generalized-typedef-2018/implementation-plan.md
=> Update generalized typedef implementation plan

specification/dart.sty, specification/dartLangSpec.tex
This PR integrates the extension methods feature spec into the language specification.
=> Specify extension methods

working/static metaprogramming/feature_specification.md
For now this is just out for review to @munificent for a quick once-over for grammatical or other such comments.
In order to comment on the proposal itself, please file issues with the `static-metaprogramming` label, thanks!
=> Start on a three phase macro feature specification doc

working/static metaprogramming/feature_specification.md
Just trying to give readers some terminology and lay of the land.
=> [macros] Add a short into to the proposal.

working/macros/feature-specification.md
Trying to give readers a little more context on the challenges and pin
down the semantics a bit more precisely. For now, I'm just going with
the simplest approach for separate compilation, but I put a TODO in
there pointing to modules since we'll likely end up going there.
=> [macros] Flesh out some of the ordering behavior a little more.

working/macros/feature-specification.md
Nothing major here. I just tried to add a little motivation and context,
then did some copyediting to try to make things more concise and/or
clear. Let me know if you like any of the existing prose more. I'm happy
to iterate on it.
=> Revise the prose around phases.

working/macros/feature-specification.md
This doc is starting to get longer so I think a TOC is in order :).
=> add table of contents to macro doc

working/macros/feature-specification.md
I chose for now to make it an error to introduce an ambiguity. Open to discuss other options though :)
=> initial pass on the scoping section

specification/dartLangSpec.tex
Sorry! -- the last few updates on 1833 did not get uploaded before I landed #1833. They are here.
=> Remaining review response from #1833

working/0158 - Enhanced Enum/feature_specification.md
Correct a mismatch between the usage and definition.
=> Fix named constructor name

working/macros/feature-specification.md
This is a fairly high level imperative process for how a Dart
implementation could process macros and generate an augmentation. I
didn't want to go into too much unnecessary detail, but hopefully it's
concrete enough.
cc @leafpetersen @bwilkerson @johnniwinther
=> First pass at a guide for compiling macros to augmentations.

working/0158 - Enhanced Enum/feature_specification.md
=> Typo in Enhanced Enums specification fixed

accepted/future-releases/constructor-tearoffs/test-plan.md
Not sure exactly what I'm aiming for here.
Tried to make an overview of the new features, and things that might be worth testing.
That's a potentially big matrix of combinations.
=> Create test-plan/overview for constructor tear-off

working/macros/example/data_class.dart
I believe the cases are current reversed.
=> Add ? to nullable

working/macros/feature-specification.md
This is kind of split into two sections, and it wasn't very clear in this first part that there are 2 different kinds of arguments so I reworked it just a bit to try and clarify that and link the sections together.
=> clarify a bit around macro arguments

working/macros/feature-specification.md
- Adds async apis to the `Resource` class now that we allow async code
- Adds a todo for a random access resource api.
- [A question](https://github.com/dart-lang/language/issues/1482#issuecomment-1025120108) came up about listing directories/files, so added a todo to evaluate that, as well as random access files.
=> Update the Resource API spec

specification/dartLangSpec.tex
Cf. https://github.com/dart-lang/sdk/issues/48502.
=> Clarify rethrow

working/macros/example/benchmark/simple.dart
feel free to merge on approval
=> update the macro benchmark with the new apis

analysis_options.yaml, working/macros/example/bin/run.dart, working/macros/example/bin/user_main.dart, working/macros/example/lib/auto_dispose.dart, working/macros/example/lib/data_class.dart
More of an FYI than anything else, this is where the example macros live (at least for now), and here is an example of a not entirely trivial macro (ported from my original prototype repo).
=> add auto dispose macro example

working/0731 - horizontal inference/feature-specification.md
Initial attempt at a spec to address #731.  I believe this correctly reflects what I've prototyped.
This is my first feature spec, so I would not be surprised if I'm missing some important details.  Let me know what you think!
=> Initial feature specification for horizontal inference

working/macros/feature-specification.md
=> mention that omitted types cannot be emitted in phase one

resources/type-system/inference.md
Update to fix for https://github.com/dart-lang/language/issues/1035 .
=> Update left top rule order in constraint solving

working/0546-patterns/patterns-feature-specification.md
OK, I've revamped the patterns proposal to resolve (hopefully once and for all!) how we want to handle variable binders.
I think this is overall a significant improvement over the current proposal. It's roughly similar to the original proposal, but still retains the unified grammar in terms of how its specified and is, I think, easier to understand.
cc @stereotype441 @natebosch @jakemac53 @kallentu 
Note that there is a "CHANGELOG" section at the end of the proposal that goes into more detail about what actually changed.
=> Explicit binders in cases

accepted/future-releases/records/records-feature-specification.md, working/0546-patterns/patterns-feature-specification.md
This has been accepted, moving to its own directory under future_releases.  cc @munificent
=> Move records proposal to accepted

specification/dartLangSpec.tex
=> Fix some misuses of the indefinite article

working/extension_structs/overview.md
I think the intention here is to increment zero to 3 and compare.
=> Fix incorrect comparison

working/0546-patterns/patterns-feature-specification.md
Fix #2473.
Fix #2485.
Fix #2533.
cc @johnniwinther @chloestefantsova @scheglov
=> [pattern] Clarify variable scoping and shared case body rules.

accepted/future-releases/records/records-feature-specification.md
Fix #2599.
cc @jakemac53, @kallentu, @leafpetersen, @natebosch, @stereotype441
=> [records] Always treat "on" as an on clause after a try block.

working/0546-patterns/patterns-feature-specification.md
=> [patterns] Support "..." rest patterns in list and map patterns.

specification/dartLangSpec.tex
Before this change:
After this change:
=> Fix missing whitespace

specification/dartLangSpec.tex
=> Fix pluralization typo

.github/dependabot.yml, .github/workflows/ci.yml, .github/workflows/no-response.yml
Dependabot
GitHub Action
No Response
=> blast_repo fixes

accepted/future-releases/0546-patterns/exhaustiveness.md
=> [patterns] Correct how patterns are lifted to spaces.

accepted/future-releases/class-modifiers/feature-specification.md
=> [class mod] Clarify how language versioning affects modifiers.

accepted/future-releases/0546-patterns/feature-specification.md
=> [patterns] Fix soundness hole in map patterns.

specification/dartLangSpec.tex
The last commit in #2106 was omitted by accident.
TBR.
=> Correction of #2106

accepted/future-releases/records/records-feature-specification.md
=> Start record positional field getters at 1.

accepted/future-releases/0546-patterns/feature-specification.md
=> Ensure list patterns are exhaustive even with negative length lists.

LICENSE
Fixes https://github.com/dart-lang/language/issues/2791
=> Fix link to SDK license

accepted/future-releases/0546-patterns/feature-specification.md
Fix #2671.
cc @eernstg @stereotype441
=> [patterns] In lists, don't call v[e] if the subpattern is a wildcard.

accepted/future-releases/0546-patterns/feature-specification.md
cc @scheglov
Follow-up on: https://github.com/dart-lang/co19/issues/1734#issuecomment-1386774555
=> Move warnings to a separate section and suggest some more.

accepted/future-releases/0546-patterns/feature-specification.md
=> [patterns] Specify the behavior of pattern-for collection elements.

accepted/future-releases/0546-patterns/feature-specification.md
This is a series of 6 small changes, in separate commits for ease of review.
Three of them fix small errors. The other three are rewordings that I'd like to think make things clearer; perhaps you'll agree.
=> [patterns] Small fixes and clarifications

accepted/future-releases/0546-patterns/feature-specification.md
Pattern-for statement was mentioned twice
=> [Patterns] A typo fixed

working/1426-extension-types/feature-specification-views.md
Should this be moved to an obsolete directory, tooo?
=> Update note in view/extension types proposal

accepted/future-releases/0546-patterns/feature-specification.md
=> [Patterns] Typo fixed. Boolean replaced by bool

accepted/future-releases/records/records-feature-specification.md
fix wrong linked tuple. add link to product type.
=> Fix wrong links in records-feature-specification.md

specification/dartLangSpec.tex
Cf. https://github.com/dart-lang/sdk/issues/51565.
Closes #2873.
=> Change `==` in constant expressions to use primitive equality

accepted/future-releases/class-modifiers/feature-specification.md
See conversation in https://dart-review.googlesource.com/c/sdk/+/278888.
/cc @munificent @kallentu @lrhn
=> update `@reopen` lint name

accepted/future-releases/class-modifiers/feature-specification.md
I sent this in an email to some folks for comment, and the response was positive enough that it seemed worth including in the spec.
=> Thoughts about errors, error recovery, and fixups for class modifiers

accepted/future-releases/0546-patterns/feature-specification.md
Fix #2914 based on our discussion at this week's language meeting.
cc @dart-lang/language-team
=> [patterns] Specify that coercions don't happen during destructuring.

accepted/future-releases/0546-patterns/exhaustiveness_prototype/lib/space.dart, accepted/future-releases/0546-patterns/exhaustiveness_prototype/lib/static_type.dart, accepted/future-releases/0546-patterns/exhaustiveness_prototype/lib/subtract.dart, accepted/future-releases/0546-patterns/exhaustiveness_prototype/test/expand_type_test.dart, analysis_options.yaml
Mostly this is small cleanups in the patterns proposal to conform to lints, and then excluding an old directory.
=> fix analysis diagnostics by excluding some dirs and fixing up others

accepted/future-releases/0546-patterns/feature-specification.md
Fix #2861.
cc @dart-lang/language-team, @johnniwinther, @scheglov, @bwilkerson, @srawlins, @sgrekhov
=> Remove implicit length checks from map patterns.

working/augmentation-libraries/feature-specification.md
Closes https://github.com/dart-lang/language/issues/2892
=> add a restriction that augmented types must duplicate all keywords

accepted/future-releases/0546-patterns/feature-specification.md
cc @chloestefantsova @johnniwinther
=> Clarify the restriction on pattern variables in guards.

accepted/future-releases/class-modifiers/feature-specification.md
=> [Class modifiers] Typo in example fixed

resources/type-system/strict-raw-types.md
| Before  | After |
| ------------- | ------------- |
| <img width="257" alt="before" src="https://user-images.githubusercontent.com/18245704/235647007-3c8e0163-27a1-4258-b8c5-f5adea37c77a.png">  | <img width="257" alt="after" src="https://user-images.githubusercontent.com/18245704/235647093-e077132c-a2b1-44d0-90d9-8f2574162c89.png">  |
=> Fix the indent in strict-raw-types.md.

working/augmentation-libraries/feature-specification.md
closes https://github.com/dart-lang/language/issues/2978
=> Add support for augmenting enum values, specify language versioning constraints

working/augmentation-libraries/feature-specification.md
Closes https://github.com/dart-lang/language/issues/2325
Closes https://github.com/dart-lang/language/issues/2324
=> Add clarifying section on the semantics of `super augment` in various augmenting contexts

working/augmentation-libraries/feature-specification.md
closes https://github.com/dart-lang/language/issues/2131
cc @srawlins
=> specify that doc comments are allowed in augmentations

working/augmentation-libraries/feature-specification.md
Closes https://github.com/dart-lang/language/issues/2120
cc @lrhn
=> make augment a built-in identifier

working/macros/feature-specification.md
closes https://github.com/dart-lang/language/issues/2157
=> define ordering of members during introspection

.github/workflows/ci.yml, .github/workflows/dart.yml
This PR contains changes created by the blast repo tool.
- `github-actions`
=> blast repo changes: github-actions

working/macros/feature-specification.md
Actually resolve https://github.com/dart-lang/language/issues/1917 - I missed this section in the proposal.
We already chose option 4 so I removed the other options and elaborated on the chosen strategy.
=> clarify static state section of macros proposal

working/macros/feature-specification.md
Closes https://github.com/dart-lang/language/issues/1934
=> solidify and clarify the API versioning strategy for macros

accepted/3.0/patterns/exhaustiveness.md
This moved to the `/accepted` folder, so I'm assuming the `Status` on line 5 should also be `Accepted`? Or maybe there's still some part in work, in which case we can close this.
---
<details>
- Changes to …
=> Update exhaustiveness.md status

working/2364 - primary constructors/feature-specification.md
- Thanks for your contribution! Please replace this text with a description of what this PR is changing or adding and why, list any relevant issues, and review the contribution guidelines below.
---
<details>
- …
=> Delineate before and after examples more clearly

working/1426-extension-types/feature-specification-inline-classes.md, working/1426-extension-types/feature-specification-views.md, working/1426-extension-types/feature-specification.md
Avoiding confusion and out-of-date information for visitors to the previous iterations.
\cc @eernstg
=> Link to new extension type specification

working/augmentation-libraries/feature-specification.md
Closes https://github.com/dart-lang/language/issues/3367
=> specify that multiple augmentations of one declaration are allowed

working/macros/example/pubspec.yaml
Fixes https://github.com/dart-lang/language/issues/3390
=> update macro example language version

working/macros/example/benchmark/simple.dart, working/macros/example/benchmark/src/json_serializable.dart, working/macros/example/benchmark/src/shared.dart, working/macros/example/lib/checks_extensions.dart, working/macros/example/lib/json_serializable.dart
This also has the effect of allowing me to see the actual output, which was really my goal 🤣
=> add json serializable benchmark

working/macros/feature-specification.md
Per discussion with Konstantin.
=> [macros] Clarify introspection StateError on retry.

specification/dartLangSpec.tex
Incorporates feedback from:
https://github.com/dart-lang/language/pull/3570.
=> Revise spec language on warnings.

working/macros/feature-specification.md
Add a brief note about MacroException.
=> [macros] Update StateError->MacroIntrospectionCycleException.

README.md
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).
Note that many Dart repos have a weekly cadence for reviewing PRs - …
=> Add Kallen and Morgan to the list of language team members

working/augmentation-libraries/feature-specification.md
=> Specify how extension types and their constructors are augmented.

working/macros/example/benchmark/simple.dart, working/macros/example/benchmark/src/checks_extensions.dart, working/macros/example/benchmark/src/data_class.dart, working/macros/example/benchmark/src/functional_widget.dart, working/macros/example/benchmark/src/injectable.dart, working/macros/example/benchmark/src/json_serializable.dart, working/macros/example/benchmark/src/shared.dart, working/macros/example/lib/auto_dispose.dart, working/macros/example/lib/checks_extensions.dart, working/macros/example/lib/data_class.dart, working/macros/example/lib/functional_widget.dart, working/macros/example/lib/inherited_widget.dart, working/macros/example/lib/injectable.dart, working/macros/example/lib/json_serializable.dart, working/macros/example/lib/observable.dart, working/macros/example/lib/util.dart, working/macros/example/pubspec.yaml
Fixes https://github.com/dart-lang/language/issues/3677
=> update to use package:macros

working/333 - shared memory multithreading/proposal.md
=> Small tweaks to shared memory proposal

working/macros/example/analysis_options.yaml
=> exclude injectable example from analysis

working/macros/example/bin/json_serializable_main.dart, working/macros/example/lib/json_serializable.dart
Fixes https://github.com/dart-lang/language/issues/3719
=> add external keyword to the json macro for now

resources/type-system/inference.md
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).
Note that many Dart repos have a weekly cadence for reviewing PRs - …
=> Fix typo: `:<` should be `<:`.

working/wildcards/feature-specification.md
Added a small section on imports.
Let me know if I can write it clearer.
=> [wildcard-variables] Add section on imports.

working/wildcards/feature-specification.md
Changed the section on `super._` to allow it and described a few cases.
Let me know if I got anything wrong or can write something better.
Bob's out, so if either/both of you can take a look, that'd be great!
=> [wildcard-variables] Allow super._.

working/macros/dart_model/macro_client/lib/socket_host.dart, working/macros/dart_model/macro_host/lib/macro_host.dart, working/macros/dart_model/macro_host/lib/socket_client.dart, working/macros/dart_model/macro_protocol/lib/host.dart, working/macros/dart_model/macro_protocol/lib/message.dart, working/macros/dart_model/testing/test_macros/lib/equals_macro.dart, working/macros/dart_model/testing/test_macros/lib/hash_code_macro.dart, working/macros/dart_model/testing/test_macros/lib/to_string_macro.dart
=> [macros] Batch augmentations.

working/macros/dart_model/dart_model/lib/query.dart, working/macros/dart_model/dart_model_analyzer_service/lib/dart_model_analyzer_service.dart, working/macros/dart_model/dart_model_analyzer_service/pubspec.yaml, working/macros/dart_model/dart_model_repl/lib/dart_model_repl.dart, working/macros/dart_model/dart_model_repl/pubspec.yaml, working/macros/dart_model/macro_client/lib/socket_host.dart, working/macros/dart_model/macro_host/bin/main.dart, working/macros/dart_model/macro_host/lib/macro_host.dart, working/macros/dart_model/macro_host/lib/socket_client.dart, working/macros/dart_model/macro_host/pubspec.yaml, working/macros/dart_model/macro_protocol/lib/host.dart, working/macros/dart_model/macro_protocol/lib/message.dart, working/macros/dart_model/testing/test_macros/lib/equals_macro.dart, working/macros/dart_model/testing/test_macros/lib/hash_code_macro.dart, working/macros/dart_model/testing/test_macros/lib/to_string_macro.dart
=> [macros] Split generation explicitly into numbered rounds.

.github/workflows/dart.yml
Fixes https://github.com/dart-lang/language/issues/3656
=> still run tests if analysis fails

working/macros/dart_model/dart_model/.gitignore, working/macros/dart_model/dart_model/lib/model.dart, working/macros/dart_model/dart_model/lib/query.dart, working/macros/dart_model/dart_model/lib/schema.json, working/macros/dart_model/dart_model/test/model_test.dart, working/macros/dart_model/dart_model/test/query_test.dart, working/macros/dart_model/dart_model/tool/generate_schema_dart, working/macros/dart_model/dart_model_analyzer_service/goldens/lib/g1.json, working/macros/dart_model/dart_model_analyzer_service/lib/dart_model_analyzer_service.dart, working/macros/dart_model/dart_model_analyzer_service/pubspec.yaml, working/macros/dart_model/dart_model_analyzer_service/test/golden_test.dart, working/macros/dart_model/macro_client/lib/class_generator_macro.dart, working/macros/dart_model/testing/pub_get
For #3872 
The schema and schema validation in Dart seem to work fine, except that we hit what I think is a bug in `package:json_schema` https://github.com/Workiva/json_schema/issues/190
=> Json schema

working/macros/dart_model/README.md, working/macros/dart_model/testing/benchmark/bin/main_json.dart, working/macros/dart_model/testing/benchmark/lib/json_macro/input_generator.dart, working/macros/dart_model/testing/benchmark/lib/json_macro/macros.dart, working/macros/dart_model/testing/benchmark/lib/json_macro/scratch.dart
=> [macros] Add JSON macro benchmark.

resources/type-system/inference.md
This addresses comments from @lrhn that I didn't see before landing https://github.com/dart-lang/language/pull/3920.
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding …
=> Follow-up tweaks to await handling.

working/macros/feature-specification.md
Closes https://github.com/dart-lang/language/issues/3459
=> specify that default constructors should only appear after phase 2

working/augmentation-libraries/feature-specification.md
closes https://github.com/dart-lang/sdk/issues/56341
cc @sgrekhov
=> specify that representation objects for extension types cannot be augmented

working/augmentation-libraries/feature-specification.md
Closes https://github.com/dart-lang/language/issues/3936, will merge after https://github.com/dart-lang/language/pull/4003 for changelog consistency.
=> specify that static and instance members cannot have the same name

working/augmentation-libraries/feature-specification.md
Closes https://github.com/dart-lang/language/issues/4017
=> Remove some errors around abstract and external variables

working/macros/dart_model/analysis_options.yaml, working/macros/dart_model/dart_model/pubspec.yaml, working/macros/dart_model/dart_model_analyzer_service/pubspec.yaml, working/macros/dart_model/dart_model_repl/pubspec.yaml, working/macros/dart_model/macro_client/pubspec.yaml, working/macros/dart_model/macro_host/pubspec.yaml, working/macros/dart_model/macro_protocol/pubspec.yaml, working/macros/dart_model/testing/benchmark/pubspec.yaml, working/macros/example/analysis_options.yaml, working/macros/example/pubspec.yaml
After https://github.com/dart-lang/sdk/commit/2c77c6749d0e74fd1467b069cf64cc36bb78b125 it's needed for macros in the analyzer.
=> Enable enhanced parts experiment for macros code.

working/augmentation-libraries/feature-specification.md
Wihout the fix is hard to understand what this statement really mean. Seems that it should be read as the fix isuggests.
=> [Augmentations] Fix small typo

working/0649 - Import shorthand/proposal.md
- Thanks for your contribution! Please replace this text with a description of what this PR is changing or adding and why, list any relevant issues, and review the contribution guidelines below.
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a- …
=> Cross-link to new imports spec

working/augmentation-libraries/feature-specification.md
*   Remove recommend path ordering lint. Commit to making `part` directive
order meaningful and acceptable to rely on.
*   Allow enum declarations without values.
*   Specify signature matching for implicit setters from abstract variables.
*   Clarify that you can't augment an extension type constructor and add a body.
*   Don't allow augmenting mixin application classes.
Fix #3849.
Fix #4356.
Fix #4022.
Fix #4047.
Fix #4060.
=> Fix a handful of augmentations issues.

accepted/future-releases/extension-types/feature-specification.md
- Fix a quote missing in feature-specification.md
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).
Note that …
=> Fix a quote missing in feature-specification.md

working/2509-private-named-parameters/feature-specification.md
I really like the text you proposed on the issue, so here it is. :)
Fix #4471.
=> Revise "Private Named Parameters".

working/2509-private-named-parameters/feature-specification.md
=> Clarify some vague text in "Private Named Parameters".
